### ISSUE TITLE
2. 配置文件  3. 执行 git_pull.sh 进行脚本更新以及定时文件更新 cp: cannot create regular file '/root/jd/config/config.sh': No such file or directory cp: cannot create regular file '/root/jd/config/cookie.sh': No such file or directory cp: cannot stat '5865JdDir/sample/crontab.list.sample': No such file or directory cp: cannot create regular file '/root/jd/config/sharecode.sh': No such file or directory Can't open /root/jd/config/crontab.list: No such file or directory.

### ISSUE THREAD

**Issue by jackli201** [lan-tianxiang/JS_TOOL#10]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by jdyuxu** [comment]
之前版本安装部署都成功了，每天不到200个豆，很快就每天40左右个豆。后决定升级到新版，反复卸载安装到现在，找不到相关文件，尤其是Can't open /root/jd/config/crontab.list: No such file or directory.没有定时任务文件，挂不挂机也没啥用，能执行单个脚本，在文件管理器也看不到crontab.lis这个定时任务文件，不足什么原因，卸载重装也不行。
