### ISSUE TITLE
希望大佬融合一下

### ISSUE THREAD

**Issue by Tsukasa007** [lan-tianxiang/JS_TOOL#102]
### 想要增加什么样的功能或者哪里存在不足之处呢？
https://github.com/zero205/JD_tencent_scf

**Comment by lan-tianxiang** [comment]
已修复第三方脚本库功能，请打开后，自行添加即可。可选择覆盖模式
![image](https://user-images.githubusercontent.com/42911023/121654207-0f156200-cad0-11eb-8cbc-ec6ecdb7d276.png)

**Comment by Tsukasa007** [comment]
膜拜～
