### ISSUE TITLE
关于第三方库重复优先问题

### ISSUE THREAD

**Issue by Tsukasa007** [lan-tianxiang/JS_TOOL#104]
### 想要增加什么样的功能或者哪里存在不足之处呢？
比如同步第三方的时候，检测原库是否有同名js，如果有就以原库优先，不更新加入cron，如不存在，则加入，如果有个开关就很棒棒～

**Comment by lan-tianxiang** [comment]
已经有了，你用更新工具更新一下

**Comment by lan-tianxiang** [comment]
![image](https://user-images.githubusercontent.com/42911023/121665973-57864d00-cadb-11eb-845c-1c104e29c3c9.png)

**Comment by Tsukasa007** [comment]
牛皮
