### ISSUE TITLE
第三方库与本地库重复问题

### ISSUE THREAD

**Issue by Tsukasa007** [lan-tianxiang/JS_TOOL#105]
### 想要增加什么样的功能或者哪里存在不足之处呢？

第三方库为这个
https://github.com/zero205/JD_tencent_scf.git

经过刚刚测试，同步下载的时候原库有的js脚本，第三方库也会加入cron文件

**Comment by Tsukasa007** [comment]
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# 更新所有脚本（包括自用thirdpard脚本）
22 * * * * sleep 38 && jd update >> /root/jd/log/jd.log 2>&1

# 删除 RmLogDaysAgo 指定天数以前的旧日志，本行为不记录日志：
57 13 * * * jd clean

# 导出所有互助码清单，日志在log/helpcode下
48 * * * * jd myhelp

# 重启挂机程序
# 33 13 * * * jd hangup

# DIY任务区域
# 需自行将脚本放在scripts文件夹下




# thirdpard任务区域
# 定时区域thirdpard开始，误删

15 0,6,13,19,21 * * * thirdpard /root/jd/thirdpard/hyzaw_scripts/ddo_pk.js

0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_chb.js
10 1,12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_coin.js
30 16-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_half_redrain.js
10 0-21/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_steal.js
30 8,16,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxd.js
10 0,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_necklace.js
1 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_super_redrain.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_tyt.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xsmh.js

2 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_change.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_home.js
1 7,12,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_beauty.js
20 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_big_winner.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_blueCoin.js
1 8,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bookshop.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car_exchange.js
0 0-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_carnivalcity.js
2 0-23/4 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash.js
0,1,2 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash_exchange.js
5 8,13,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cfd.js
5 0,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_club_lottery.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_bonus.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_daily_egg.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_dreamFactory.js
1 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_family.js
5 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_fruit.js
20 13 * * 6 thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_get_share_code.js
13 1,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_gold_creator.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdfactory.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdzz.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jin_tie.js
15 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy.js
15 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_feedPets.js
0 0-16/8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_reward.js
15 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_run.js
1 0,11,21 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jump.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxlhb.js
0 9,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxnc.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_kd.js
10-20/5 12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live.js
0,30 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live_redrain.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_market_lottery.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mcxhd.js
0 0,1-23/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mohe.js
3 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_moneyTree.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_ms.js
35 1,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_nzmh.js
15 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pet.js
12 0-23/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pigPet.js
1 7-21/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_plantBean.js
11 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_rankingList.js
1 1,2,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_redPacket.js
20 8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_sgmh.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_shop.js
16 22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_small_home.js
20 0,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_redpocke.js
0 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_sign.js
0 1,21 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_star_shop.js
11 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_superMarket.js
10 0,7,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_syj.js
55 23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_unsubscribe.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg_help.js
5 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zoo.js
0-59/30 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zooCollect.js
# 定时区域thirdpard结束，误删


# jd任务区域，运行jd_scripts脚本，仅列出长期任务作初始化用，AutoAddCron=true时，将自动添加短期任务。
# 请保留任务名称中的前缀"jd_"，去掉后缀".js"，如果有些任务你不想运行，注释掉就好了，不要删除。
# 非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。
5 9 * * * jd jd_bean_change
20 10 * * * jd jd_bean_change
23 1,12,22 * * * jd jd_bean_home
4 0,9 * * * jd jd_bean_sign
41 7,12,19 * * * jd jd_beauty
10,40 * * * * jd jd_big_winner
0,30 0 * * * jd jd_blueCoin
38 8,12,18 * * * jd jd_bookshop
0 0 * * * jd jd_car
0,1,2,3 0 * * * jd jd_car_exchange
0 1,12,18,21 * * * jd jd_carnivalcity
10 */4 * * * jd jd_cash
5 7,12,18 * * * jd jd_cfd
6 0,23 * * * jd jd_club_lottery
30 7,23 * * * jd jd_crazy_joy
10 12 * * * jd jd_crazy_joy_bonus
28 * * * * jd jd_daily_egg
13 1,22,23 * * * jd jd_daily_lottery
#20 9 * * 6 jd jd_delCoupon
50 * * * * jd jd_dreamFactory
10 6,7 * * * jd jd_family
15 6-18/6 * * * jd jd_fruit
23 7 * * * jd jd_get_share_code
0 1,22 * * * jd jd_gold_creator
13 1,6,22 * * * jd jd_health
5-45/20 * * * * jd jd_health_collect
26 * * * * jd jd_jdfactory
6 0-5/1,11 * * * jd jd_jdzz
5 0 * * * jd jd_jin_tie
45 */2,23 * * * jd jd_joy
35 */1 * * * jd jd_joy_feedPets
0 0-16/8 * * * jd jd_joy_reward
10 13-20/1 * * * jd jd_joy_run
15 0,12,22 * * * jd jd_jump
30 1,6,12,21 * * * jd jd_jxlhb
15 0,12,22 * * * jd jd_jxmc
30 9,12,18 * * * jd jd_jxnc
47 1 * * * jd jd_kd
30-50/5 12,23 * * * jd jd_live
1,31 0-23/1 * * * jd jd_live_redrain
0 0,12,23 * * * jd jd_lotteryMachine
10 10,23 * * * jd jd_market_lottery
20 1,21 * * * jd jd_mcxhd
0 0-23/4 * * * jd jd_mohe
23 */2 * * * jd jd_moneyTree
10 6,21 * * * jd jd_ms
35 1,22 * * * jd jd_nzmh
35 6-18/6 * * * jd jd_pet
32 0-23/6 * * * jd jd_pigPet
10 7-22/1 * * * jd jd_plantBean
#41 0,23 * * * jd jd_price
21 9 * * * jd jd_rankingList
12 0-23/4 * * * jd jd_redPacket
47 8,22 * * * jd jd_sgmh
6 0 * * * jd jd_shop
46 6,23 * * * jd jd_small_home
45 0,23 * * * jd jd_speed_redpocke
21 1,6 * * * jd jd_speed_sign
0 1,21 * * * jd jd_star_shop
31 0,1-23/2 * * * jd jd_superMarket
12 * * * * jd jd_syj
45 23 * * * jd jd_unsubscribe
0 0 * * * jd jd_xtg
0 0 * * * jd jd_xtg_help
0 */2 * * * jd jd_zoo
20,40 * * * * jd jd_zooCollect
`

**Comment by lan-tianxiang** [comment]
的确，定时等伙改改

**Comment by Tsukasa007** [comment]
谢谢大佬
