### ISSUE TITLE
扫码后 cookie 保存在哪里的？

### ISSUE THREAD

**Issue by QQ1142057049** [lan-tianxiang/JS_TOOL#106]

**Comment by QQ1142057049** [comment]
![image](https://user-images.githubusercontent.com/67356618/121680139-c5d30b80-caeb-11eb-8666-f2836f53b0a7.png)

**Comment by QQ1142057049** [comment]
找不到它说的那个文件

**Comment by wintsa123** [comment]
.......???docker安装的这都不知道，就这个配置文件啊，网页填写
