### ISSUE TITLE
安装docker后crontab原有定时任务被覆盖

### ISSUE THREAD

**Issue by ChellyL** [lan-tianxiang/JS_TOOL#109]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：我的系统为Debian，使用脚本一键安装docker后，使用crontab -e查看定时任务，发现原有的定时任务被覆盖，不清楚这是否为个例……

### (2) 详细日志
A：

**Comment by cq535454518** [comment]
我也发现了  zoo脚本根本控制不住 一点更新脚本文件 自己设置的规则就会被覆盖。。而且用户配置中想要限制某个账号不运行某个脚本的功能一直没成功过  用了3个月了

**Comment by CACAVOK** [comment]
> 我也发现了 zoo脚本根本控制不住 一点更新脚本文件 自己设置的规则就会被覆盖。。而且用户配置中想要限制某个账号不运行某个脚本的功能一直没成功过 用了3个月了

确实，我想限制zoo的时间，直接被覆盖了，然而jxmc的我随便改都没变动
