### ISSUE TITLE
群满了，老哥

### ISSUE THREAD

**Issue by yang7758258** [lan-tianxiang/JS_TOOL#11]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lukemin** [comment]
群满了，无法加入，如何获取授权码？

**Comment by Dlian-Zero** [comment]
同求啊

**Comment by jindaolu** [comment]
同求

**Comment by nfyb** [comment]
+1

**Comment by Yves81** [comment]
+1
