### ISSUE TITLE
关于助力码问题

### ISSUE THREAD

**Issue by xiaorizi01** [lan-tianxiang/JS_TOOL#113]
开启了自动配置助力码，其他都正常，唯独运行惊喜农场和财富岛的时候，一直提示您提供了0个助力码！日志里面明明已经配置了农场和财富岛的助力码

**Comment by lan-tianxiang** [comment]
好的，我看看

**Comment by xiaorizi01** [comment]
好的。辛苦看下是什么情况，我看了下日志，这几个有的显示的是，你提供了0个助力！还有的显示已经提供了全部助力码，但是不会按账号内部ck顺序互助，变成了随机！配置设置的按账号ck顺序优先互助

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lan-tianxiang ***@***.***&gt;
发送时间: 2021年6月13日 09:43
收件人: lan-tianxiang/JS_TOOL ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lan-tianxiang/JS_TOOL] 关于助力码问题 (#113)





 
好的，我看看

**Comment by yeslight** [comment]
+1，设置助力按cookie顺序优先，但自动导出的助力码是各帐号均等助力，而且在config中的sharecode.sh没办法覆盖helpcode

**Comment by lan-tianxiang** [comment]
@yeslight  优先级改好了，config中的手动互助码可以生效了。  自动导出的助力码我再优化一下

**Comment by xiaorizi01** [comment]
意思现在暂时需要先手动填写助力码是吧！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lan-tianxiang ***@***.***&gt;
发送时间: 2021年6月15日 11:29
收件人: lan-tianxiang/JS_TOOL ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lan-tianxiang/JS_TOOL] 关于助力码问题 (#113)





 
@yeslight  优先级改好了，config中的手动互助码可以生效了。  自动导出的助力码我再优化一下

**Comment by lan-tianxiang** [comment]
可以手动，手动填写优先级最高，其次到自动配置的helpcode

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xiaorizi01 ***@***.***&gt;;
发送时间：2021年6月15日(星期二) 中午11:32
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 关于助力码问题 (#113)
-----------------------------------

 

 意思现在暂时需要先手动填写助力码是吧！ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: lan-tianxiang ***@***.***&amp;gt; 
 发送时间: 2021年6月15日 11:29 
 收件人: lan-tianxiang/JS_TOOL ***@***.***&amp;gt; 
 抄送: xiaorizi01 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: 回复：[lan-tianxiang/JS_TOOL] 关于助力码问题 (#113) 
 
 
 
 
 
   
 @yeslight  优先级改好了，config中的手动互助码可以生效了。  自动导出的助力码我再优化一下

**Comment by xiaorizi01** [comment]
现在自动配置助力 和助力逻辑 修复了吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lan-tianxiang ***@***.***&gt;
发送时间: 2021年6月15日 12:39
收件人: lan-tianxiang/JS_TOOL ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lan-tianxiang/JS_TOOL] 关于助力码问题 (#113)





 可以手动，手动填写优先级最高，其次到自动配置的helpcode 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 
 --------------原始邮件-------------- 
 发件人："xiaorizi01 ***@***.***&amp;gt;; 
 发送时间：2021年6月15日(星期二) 中午11:32 
 收件人："lan-tianxiang/JS_TOOL" ***@***.***&amp;gt;; 
 抄送："lan-tianxiang ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [lan-tianxiang/JS_TOOL] 关于助力码问题 (#113) 
 ----------------------------------- 
 
   
 
  意思现在暂时需要先手动填写助力码是吧！  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: lan-tianxiang ***@***.***&amp;amp;gt;  
  发送时间: 2021年6月15日 11:29  
  收件人: lan-tianxiang/JS_TOOL ***@***.***&amp;amp;gt;  
  抄送: xiaorizi01 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: 回复：[lan-tianxiang/JS_TOOL] 关于助力码问题 (#113)  
   
   
   
   
   
     
  @yeslight  优先级改好了，config中的手动互助码可以生效了。  自动导出的助力码我再优化一下

**Comment by yeslight** [comment]
> @yeslight 优先级改好了，config中的手动互助码可以生效了。 自动导出的助力码我再优化一下

感谢回复，目前群晖docker中问题仍存在上述问题

**Comment by lan-tianxiang** [comment]
@yeslight   上述问题指的是
①config中的sharecode.sh没办法覆盖helpcode
②自动导出的助力码是各帐号均等助力

问题还存在对吗

**Comment by lan-tianxiang** [comment]
问题①我已经修复了，问题二到时候我出一个助力配置的选项

**Comment by yeslight** [comment]
> @yeslight 上述问题指的是
> ①config中的sharecode.sh没办法覆盖helpcode
> ②自动导出的助力码是各帐号均等助力
> 
> 问题还存在对吗

是的，刚在sharecode.sh 只配置了一个变量测试，内容仅这一行
ForOtherFruit2="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}"
但是手动执行时，日志显示帐号2是按照helpcode中的助力码进行助力的，是我理解上有问题吗

**Comment by lan-tianxiang** [comment]
@yeslight  已经新增帮助数量的参数了，你更新一下就行了。
至于按照helpcode中的助力码，我测试了一下，没有问题。
