### ISSUE TITLE
Docker 配置好 Cookie 之后是每天自动运行任务的吗，还是需要runall才行？小白不太懂。

### ISSUE THREAD

**Issue by Google-Skillshop** [lan-tianxiang/JS_TOOL#114]
### 想要增加什么样的功能或者哪里存在不足之处呢？

Docker 配置好 Cookie 之后是每天自动运行任务的吗，还是需要runall才行？
Readme没有说明，小白不太懂。

**Comment by Google-Skillshop** [comment]
另外，如果是自动运行的，那么 bash jd.sh paneloff 之后，还可以自动运行吗？

**Comment by lan-tianxiang** [comment]
> 另外，如果是自动运行的，那么 bash jd.sh paneloff 之后，还可以自动运行吗？

可以的，那个只是面板的命令，不影响整体自动运行

**Comment by Google-Skillshop** [comment]
> > 另外，如果是自动运行的，那么 bash jd.sh paneloff 之后，还可以自动运行吗？
> 
> 可以的，那个只是面板的命令，不影响整体自动运行

### Thanks
