### ISSUE TITLE
我这边屏蔽Cookie出现了问题，失效的Cookie逻辑问题

### ISSUE THREAD

**Issue by ghost** [lan-tianxiang/JS_TOOL#115]
屏蔽的是15 17 18
具体是这样比如15 推送失效却是16失效，导致以为是16失效，本来就是15失效，16未失效。

**Comment by ghost** [comment]
刚才再试了下输出助力码，我还是屏蔽的15 17 18，可是还是输出了15 17 18 ，输出的15 17 18却不是他们的助力码，逻辑问题。一共18个，屏蔽了3个 最后输出的第15个

**Comment by lan-tianxiang** [comment]
好的，感谢你的反馈，我重新看一下
