### ISSUE TITLE
群辉docker 每天半夜12点意外停止

### ISSUE THREAD

**Issue by qzsun02** [lan-tianxiang/JS_TOOL#117]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ x] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：群晖docker 每天半夜12点一定会显示容器意外停止，自动重启容器后cookie和设定全部恢复初设状态。跟着群晖docker教程一步步操作的，希望大佬们解答一下，谢谢。

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
这样啊，请问一下能不能给我看一下意外停止前的日记呢

**Comment by qzsun02** [comment]
> 这样啊，请问一下能不能给我看一下意外停止前的日记呢

请问是哪里的日志？我看容器的日志是从意外停止后重启开始的。

**Comment by lan-tianxiang** [comment]
有意外重启前的容器日记吗，没有的话不好分析问题在哪

**Comment by qzsun02** [comment]
> 有意外重启前的容器日记吗，没有的话不好分析问题在哪

没有找到，或者我用其他部署方法试试。谢谢大佬的回复。
