### ISSUE TITLE
终端文件部署的问题「mac os Big Sur」

### ISSUE THREAD

**Issue by iChoix** [lan-tianxiang/JS_TOOL#118]
ichoixhackintosh@changdeAir ~ % wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/linux_install_jd.sh -O linux_install_jd.sh && chmod +x linux_install_jd.sh && bash linux_install_jd.sh

开始部署jd_shell

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
#####################################################

正在为您安装环境（依赖）：
git wget curl perl moreutils node.js yarn/npm

#####################################################
除了安卓，由于其它系统安装软件可能需要使用sudo，本脚本除安装环境外不会调用再次任何root的执行权限

若担心安全风险，可选择自行安装环境!!

#####################################################
检测到系统似乎为 Macos ,请输入你的系统对应序号 :

1   debian/ubuntu/armbian/OpenMediaVault，以及其他debian系

2   CentOS/RedHat/Fedora等红帽系

3   Termux为主的安卓系

4   环境已安装，直接开始部署脚本

5   自己手动安装环境(退出)

时间2021-06-13 07:55

#####################################################

4   已安装(继续)

依赖已安装,开始部署脚本，否则按 Ctrl + C 退出！

1. 获取源码
fatal: could not create work tree dir '/jd': Read-only file system

2. 配置文件
linux_install_jd.sh: line 103: /jd/old_crontab: No such file or directory

3. 执行 git_pull.sh 进行脚本更新以及定时文件更新
mkdir: /jd: No such file or directory
cp: /jd/sample/config.sh.sample: No such file or directory
cp: /jd/sample/cookie.sh.sample: No such file or directory
cp: /jd/sample/crontab.list.sample: No such file or directory
cp: /jd/sample/sharecode.sh.sample: No such file or directory
bash: /jd/jd.sh: No such file or directory

注意：原有定时任务已备份在 /jd/old_crontab

安装完成！！！！

 是否启用TG机器人功能，需额外占据200mb左右的空间，可能出现占用较大运行内存，cpu资源加重等情况

 任意键暂不启用，后续仍可以开启。输入 1 现在开启。

获取源码出现错误，read only 错误请问怎么解？另外交流群搜索不到了。有tg群或者别的讨论群联系方式吗？

**Comment by lan-tianxiang** [comment]
是这样的，你必须要在可读写的区域运行这个命令

**Comment by lan-tianxiang** [comment]
不要在系统分区运行它，切换到用户的目录运行就可以了
