### ISSUE TITLE
建议加一个单独第三方脚本更新命令

### ISSUE THREAD

**Issue by gitlicong** [lan-tianxiang/JS_TOOL#119]
### 想要增加什么样的功能或者哪里存在不足之处呢？

能不能加一个只更新三方脚本的命令呢，现在只能全部更新，一更新的话lxk脚本就会变回旧版本了。

**Comment by lan-tianxiang** [comment]
能问一下旧版本是什么吗

**Comment by lan-tianxiang** [comment]
或者是有新版的脚本来源吗

**Comment by gitlicong** [comment]
我一更新，jd_zoo.js等就会变回5月31号的，lxk最后一版本不是这个时间。
A1能自定义内置仓库地址嘛

**Comment by lan-tianxiang** [comment]
暂时不支持更换内置库的地址，我等等更新上

**Comment by lan-tianxiang** [comment]
@gitlicong  已经加上了

**Comment by zhangleqin** [comment]
> 
> 
> @gitlicong 已经加上了

更新一下JD_ZOO的脚本吧 这个有原版 还能更新

**Comment by lan-tianxiang** [comment]
已经修复zoo了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："zhangleqin ***@***.***&gt;;
发送时间：2021年6月13日(星期天) 中午12:06
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 建议加一个单独第三方脚本更新命令 (#119)
-----------------------------------

 

  
@gitlicong 已经加上了
  
更新一下JD_ZOO的脚本吧 这个有原版 还能更新

**Comment by zhangleqin** [comment]
> 
> 已经修复zoo了
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："zhangleqin ***@***.***&gt;; 发送时间：2021年6月13日(星期天) 中午12:06 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 建议加一个单独第三方脚本更新命令 (#119) ----------------------------------- @gitlicong 已经加上了 更新一下JD_ZOO的脚本吧 这个有原版 还能更新 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没更新啊 update之后又回去了 有最新6/13日版 这个是最近最有用的JS
