### ISSUE TITLE
Docker无法启动

### ISSUE THREAD

**Issue by hysbeta** [lan-tianxiang/JS_TOOL#12]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：首次启动docker成功后能访问面板，重启docker或更改配置后报错，无法访问面板

### (2) 详细日志
A：
您的操作系统为：UnKnow 架构：aarch64
/usr/local/bin/jd: line 546:   486 Killed                  nohup ./ttyd -p 9999 -t fontSize=14 -t disableLeaveAlert=true -t rendererType=webgl bash > /dev/null 2>&1
/usr/local/bin/jd: line 546:   484 Killed                  nohup node server.js > /dev/null 2>&1
运行成功
确认看过WIKI，打开浏览器，地址为你的127.0.0.1:5678

控制面板启动成功，如未修改，则初始用户名和密码为：admin/adminadmin...

您的操作系统为：UnKnow 架构：aarch64
容器启动成功...

Welcome to Node.js v14.16.1.
Type ".help" for more information.
> crond[8]: USER root pid 653 cmd jd jd_sgmh
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directo
![Screenshot_2021-04-22-09-13-06-523_com sonelli juicessh](https://user-images.githubusercontent.com/30502871/115641489-ccdf6800-a34b-11eb-8315-eada1e132427.jpg)

**Comment by ZJUprince** [comment]
问题一样 docker 有bug吧
