### ISSUE TITLE
辛苦了，后台控制中心的“定时设定”选项中，能否在定时的脚本后面添加活动名称和运行的时间解释呢，cron看的费劲！

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#120]
### 想要增加什么样的功能或者哪里存在不足之处呢？
辛苦了，后台控制中心的“定时设定”选项中，能否在定时的脚本后面添加活动名称和运行的时间解释呢，cron看的费劲！
例如：
5 9 * * * /home/ubuntu/jd/jd.sh jd_bean_change           #某某活动，每天的几点几分运行一次 or 几次
20 10 * * * /home/ubuntu/jd/jd.sh jd_bean_change      #某某活动，每天的几点几分运行一次 or 几次

如果太麻烦，那我们自己是否可以在后面这样注释出来呢？时间上不太好写，cron表达式查的费劲，哈哈！

**Comment by lan-tianxiang** [comment]
可以，可以在后面加上注释

**Comment by LvDeShei** [comment]
大佬，我的意思是好多人不明白cron表达的意思，其实我也不明白，我的意思是能否您那里做更新的时候在后面注释上是什么活动已经几点运行运行几次等详细信息，辛苦了！就是提提建议。
