### ISSUE TITLE
通知推送Bark，出现问题，辛苦了。

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#121]
{ HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.request.once (/home/ubuntu/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  code: undefined,
  timings:
   { start: 1623555008782,
     socket: 1623555008782,
     lookup: 1623555008787,
     connect: 1623555008824,
     secureConnect: 1623555008900,
     upload: 1623555008900,
     response: 1623555008939,
     end: 1623555008946,
     error: undefined,
     abort: undefined,
     phases:
      { wait: 0,
        dns: 5,
        tcp: 37,
        tls: 76,
        request: 0,
        firstByte: 39,
        download: 7,
        total: 164 } } }

🔔京东资产变动通知, 结束! 🕛 8.613 秒

您的操作系统为：Debian 架构：x86_64

## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
我分析了一下，觉得可能是账号太多导致消息数据过多，导致无法发送。 我几天后更新分渠道推送功能

**Comment by LvDeShei** [comment]
账号确实比较多，共6个，辛苦了！凭他上有版本更新介绍吗？不好意思没注意到呢！
