### ISSUE TITLE
功能“手动执行”中的“更新文件脚本”执行n次更新后，在“定时设定”中更新后的活动会在最后多出n次，请关注！

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#124]
多次在“手动执行”菜单中执行“更新脚本文件”功能后，在“定时设定”中更新的活动会多次重复出现，比如未更新前是这样的：
... ...
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect
再次更新后是这样的（例如更新2次）：
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect
三次更新后是这样的（例如更新3次）：
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect
0 */2 * * * jd.sh jd_zoo
20,40 * * * * jd.sh jd_zooCollect

**Comment by lan-tianxiang** [comment]
好，我测试一下
