### ISSUE TITLE
怎么屏蔽部分账号不挂机joy呢

### ISSUE THREAD

**Issue by QQ1142057049** [lan-tianxiang/JS_TOOL#125]
![image](https://user-images.githubusercontent.com/67356618/121797134-f2546800-cc50-11eb-98ca-7cc12040d303.png)
我在用户设定这样添加了还是会跑那几个账号

**Comment by SKzxsk** [comment]
你好，请问你琢磨出来了吗？我好想手动执行脚本也是卡在第一个joy里无限死循环
