### ISSUE TITLE
第三方库能否改进一下。

### ISSUE THREAD

**Issue by ghost** [lan-tianxiang/JS_TOOL#126]
### 想要增加什么样的功能或者哪里存在不足之处呢？
现在第三方库都是在thirdpard任务区域下面，能否改进一下，比如
# thirdpard任务区域
第一个库
第一个库配置结束
第二个库
第二个库配置结束
raw单文件
raw配置结束
# 定时区域thirdpard结束，误删
就类似这样，因为现在比如说用了多个库的话。看起来感觉有点乱。这样是不是更好看也更好区分一些？当然一般不会用太多库，我就是说这个意思，这样会不会看起来更方便一点，不知道你那边实现起来麻烦吗？

**Comment by lan-tianxiang** [comment]
好，这个换一下位置就行了，不影响的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Jessica ***@***.***&gt;;
发送时间：2021年6月13日(星期天) 下午2:57
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 第三方库能否改进一下。 (#126)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
现在第三方库都是在thirdpard任务区域下面，能否改进一下，比如
 
thirdpard任务区域
 
第一个库
 第一个库配置结束
 第二个库
 第二个库配置结束
 raw单文件
 raw配置结束
 
定时区域thirdpard结束，误删
 
就类似这样，因为现在比如说用了多个库的话。看起来感觉有点乱。这样是不是更好看也更好区分一些？当然一般不会用太多库，我就是说这个意思，这样会不会看起来更方便一点，不知道你那边实现起来麻烦吗？

**Comment by ghost** [comment]
> 好，这个换一下位置就行了，不影响的
> […](#)
行，那你有时间改一下，我看看效果。麻烦大佬了

**Comment by LvDeShei** [comment]
大佬，thirdpard任务区域在面板的哪里呢，瞅了半天没瞅见，哈哈
