### ISSUE TITLE
能增加试用的脚本吗？docker好像没有

### ISSUE THREAD

**Issue by Curry-wei98** [lan-tianxiang/JS_TOOL#129]
### 想要增加什么样的功能或者哪里存在不足之处呢？
我用的docker跑，但是好像没有试用的脚本，还有其他好多qx上有的docker上都没有。请问是不适配还是没有添加？可以自行添加吗？

**Comment by Rosylusi** [comment]
> ### 想要增加什么样的功能或者哪里存在不足之处呢？
> 我用的docker跑，但是好像没有试用的脚本，还有其他好多qx上有的docker上都没有。请问是不适配还是没有添加？可以自行添加吗？

大佬，借一部说话

**Comment by ryan016** [comment]
> ### 想要增加什么样的功能或者哪里存在不足之处呢？
> 我用的docker跑，但是好像没有试用的脚本，还有其他好多qx上有的docker上都没有。请问是不适配还是没有添加？可以自行添加吗？

将你要跑的第三方脚本上传到sripts目录，再到配置文件里写好定时设定即可
只要是xxx.js后缀的，docker都能跑

**Comment by lan-tianxiang** [comment]
增加了

**Comment by Curry-wei98** [comment]
谢谢
