### ISSUE TITLE
/root/jd/config/cookie.sh中的COOKIE未配置，请先配置后再运行该命令

### ISSUE THREAD

**Issue by ch3nc0n9** [lan-tianxiang/JS_TOOL#13]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
QQ群967451175满了如何获取授权 
/root/jd/config/cookie.sh中的COOKIE未配置，请先配置后再运行该命令

### (2) 详细日志
A：

/root/jd/config/cookie.sh中的COOKIE未配置，请先配置后再运行该命令

**Comment by Marblog** [comment]
你把京东的cookie保存到cookie.sh中啊

**Comment by kettly1260** [comment]
@Marblog 这个应该配置哪些参数啊？我全部copy或者只放pt_pin=;pt_key=;都不行

**Comment by Marblog** [comment]
> @Marblog 这个应该配置哪些参数啊？我全部copy或者只放pt_pin=;pt_key=;都不行

只设置京东cookie，别的不需要了，微信通知也可以设置一下

**Comment by kettly1260** [comment]
> > @Marblog 这个应该配置哪些参数啊？我全部copy或者只放pt_pin=;pt_key=;都不行
> 
> 只设置京东cookie，别的不需要了，微信通知也可以设置一下

请问有实例吗？我设置之后保存是报错的，用的到底是网页版还是手机网页版的cookie

**Comment by wqwqqe** [comment]
我也遇到了这个问题，简单的复制粘贴会报错格式错误。有没有格式的例子

**Comment by Iamdog** [comment]
老哥config目录下就没有这个cookie.sh文件啊

**Comment by kettly1260** [comment]
> 老哥config目录下就没有这个cookie.sh文件啊

自建的，反正我也是不会用，放弃了

**Comment by Marblog** [comment]
> > > @Marblog 这个应该配置哪些参数啊？我全部copy或者只放pt_pin=;pt_key=;都不行
> > 
> > 
> > 只设置京东cookie，别的不需要了，微信通知也可以设置一下
> 
> 请问有实例吗？我设置之后保存是报错的，用的到底是网页版还是手机网页版的cookie

扫码获取cookie，填到cookie里面就可以了啊
Cookie2=""

**Comment by Dlian-Zero** [comment]
请问怎么配置cookie，没有看到/root/jd/config/cookie.sh目录及文件
