### ISSUE TITLE
ZOO 结束

### ISSUE THREAD

**Issue by lan-tianxiang** [lan-tianxiang/JS_TOOL#134]

**Comment by tangmuyang** [comment]
运行报错找不到zoofaker.js

**Comment by XiaokangLi** [comment]
==================脚本执行- 北京时间(UTC+8)：2021/6/14下午8:33:12=====================

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './ZooFaker.js'
Require stack:
- /root/jd/scripts/jd_zoo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/jd/scripts/jd_zoo.js:29:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/jd/scripts/jd_zoo.js' ]
}

**Comment by tangmuyang** [comment]
删除容器，重新部署解决了。但是有几个账号火爆解决不了

**Comment by Rosylusi** [comment]
==================脚本执行- 北京时间(UTC+8)：2021/6/15 上午12:00:09=====================

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/jd/scripts/ZooFaker.js:1:9677)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by CACAVOK** [comment]
好多个号在跑，为什么只有第一个号火爆
![image](https://user-images.githubusercontent.com/85742065/121926230-5588ec00-cd70-11eb-9c8d-1f523ada00bd.png)

**Comment by Rosylusi** [comment]
所以找不到zoofaker.js只能通过删除容器，重新部署解决吗？

**Comment by lan-tianxiang** [comment]
@895450603  不用的，更新一下就行了

**Comment by Rosylusi** [comment]
> 
> 
> @895450603 不用的，更新一下就行了

大佬，有个问题再问一下，我现在在学习第三方仓库，更新脚本以后在手动执行当中有脚本名了，但是定时设定里面都是空的，这是啥原因？

**Comment by aburdchen415** [comment]
jd_zoo.js 的2131行改成const fs = require('fs').promises;
就可以执行了

**Comment by baolin15** [comment]
> ==================脚本执行- 北京时间(UTC+8)：2021/6/15 上午12:00:09=====================
> 
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module 'fs/promises'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Module.require (internal/modules/cjs/loader.js:692:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> at Object. (/root/jd/scripts/ZooFaker.js:1:9677)
> at Module._compile (internal/modules/cjs/loader.js:778:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)

你解决了没 没解决的话安装一下最新的node 我是安了node就没这个错了

**Comment by Rosylusi** [comment]
> > ==================脚本执行- 北京时间(UTC+8)：2021/6/15 上午12:00:09=====================
> > internal/modules/cjs/loader.js:638
> > throw err;
> > ^
> > Error: Cannot find module 'fs/promises'
> > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> > at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> > at Module.require (internal/modules/cjs/loader.js:692:17)
> > at require (internal/modules/cjs/helpers.js:25:18)
> > at Object. (/root/jd/scripts/ZooFaker.js:1:9677)
> > at Module._compile (internal/modules/cjs/loader.js:778:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> > at Module.load (internal/modules/cjs/loader.js:653:32)
> > at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> > at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> 
> 你解决了没 没解决的话安装一下最新的node 我是安了node就没这个错了

能问下怎么安装吗，小白

**Comment by baolin15** [comment]
> > > ==================脚本执行- 北京时间(UTC+8)：2021/6/15 上午12:00:09=====================
> > > internal/modules/cjs/loader.js:638
> > > throw err;
> > > ^
> > > Error: Cannot find module 'fs/promises'
> > > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> > > at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> > > at Module.require (internal/modules/cjs/loader.js:692:17)
> > > at require (internal/modules/cjs/helpers.js:25:18)
> > > at Object. (/root/jd/scripts/ZooFaker.js:1:9677)
> > > at Module._compile (internal/modules/cjs/loader.js:778:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> > > at Module.load (internal/modules/cjs/loader.js:653:32)
> > > at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> > > at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> > 
> > 
> > 你解决了没 没解决的话安装一下最新的node 我是安了node就没这个错了
> 
> 能问下怎么安装吗，小白

我也是小白全靠拿报错信息搜索的百度照着这个做的
https://www.cnblogs.com/yjp372928571/p/12761944.html

**Comment by aburdchen415** [comment]
代码改一下就好了啊，jd_zoo.js 的2131行改成const fs = require('fs').promises;

**Comment by lan-tianxiang** [comment]
@aburdchen415  好，修改了

**Comment by Rosylusi** [comment]
> 
> 
> @aburdchen415 好，修改了

Bark APP发送通知调用API失败！！

{ HTTPError: Response code 414 (Request-URI Too Large)
    at Request.request.once (/root/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  code: undefined,
  timings:
   { start: 1623734353525,
     socket: 1623734353526,
     lookup: 1623734353727,
     connect: 1623734353764,
     secureConnect: 1623734353844,
     upload: 1623734353846,
     response: 1623734353918,
     end: 1623734353919,
     error: undefined,
     abort: undefined,
     phases:
      { wait: 1,
        dns: 201,
        tcp: 37,
        tls: 80,
        request: 2,
        firstByte: 72,
        download: 1,
        total: 394 } } }
bark 推送提示错误，是我的设置问题吗

**Comment by lan-tianxiang** [comment]
> > @aburdchen415 好，修改了
> 
> Bark APP发送通知调用API失败！！
> 
> { HTTPError: Response code 414 (Request-URI Too Large)
> at Request.request.once (/root/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> name: 'HTTPError',
> code: undefined,
> timings:
> { start: 1623734353525,
> socket: 1623734353526,
> lookup: 1623734353727,
> connect: 1623734353764,
> secureConnect: 1623734353844,
> upload: 1623734353846,
> response: 1623734353918,
> end: 1623734353919,
> error: undefined,
> abort: undefined,
> phases:
> { wait: 1,
> dns: 201,
> tcp: 37,
> tls: 80,
> request: 2,
> firstByte: 72,
> download: 1,
> total: 394 } } }
> bark 推送提示错误，是我的设置问题吗

@895450603   bark不允许太大的信息体，也就是你账号太多了，传的数据也多

**Comment by lan-tianxiang** [comment]
优化满级提示导致不助力问题 6-16 11:18

**Comment by sorker** [comment]
请问一下，我拉了第三方的仓库脚本，怎么合并部署，我每次手动添加到定时任务，过一会就显示 删除了无效脚本 jd_xxx。 (docker)

**Comment by lan-tianxiang** [comment]
@sorker 因为部分第三方脚本库不带定时文件，所以只能把脚本重命名成xxx.js，不以jd开头
