### ISSUE TITLE
/usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long

### ISSUE THREAD

**Issue by 13636308814** [lan-tianxiang/JS_TOOL#135]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：
重新布置好一切正常,可以定时任务,也可以单独跑任务;第二天醒来单独跑任务就显示一下信息
![image](https://user-images.githubusercontent.com/26049566/121897928-6ed06f00-cd55-11eb-8344-dbebb9d42eaf.png)

从任务日志里面看,定时任务还是正常跑的

### (2) 详细日志
A：
/usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long
/usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long
/usr/local/bin/thirdpard: line 1214: echo: write error: Broken pipe
/usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long
/usr/local/bin/thirdpard: line 1214: echo: write error: Broken pipe
/usr/local/bin/thirdpard: line 1547: /bin/date: Argument list too long
/usr/local/bin/thirdpard: line 211: /bin/mkdir: Argument list too long
/usr/local/bin/thirdpard: line 1551: /usr/bin/tee: Argument list too long
您的操作系统为：UnKnow 架构：x86_64
/usr/local/bin/thirdpard: line 2: /bin/base64: Argument list too long
/usr/local/bin/thirdpard: line 2: /bin/base64: Argument list too long
/usr/local/bin/thirdpard: line 2: /bin/base64: Argument list too long

**Comment by lan-tianxiang** [comment]
好的，我看一下

**Comment by lan-tianxiang** [comment]
你暂时先把账号内好友助力关了就可以了

**Comment by lan-tianxiang** [comment]
我这边修复好通知你

**Comment by lan-tianxiang** [comment]
尝试修复了一下，你更新完试试

**Comment by lan-tianxiang** [comment]
@13636308814

**Comment by 13636308814** [comment]
我jd update了  还是一样出现错误

我现在这样操作
AutoHelpOther="false"
然后将助力格式写在配置设定里面

本来50个号应该有50个ForOtherXX1~50,我手动删掉了一些


![image](https://user-images.githubusercontent.com/26049566/122225404-a0793f80-cee7-11eb-98d7-d5305fa3622b.png)

**Comment by lan-tianxiang** [comment]
今天下午更新了助力数量的设定，你设置少一点就行了

**Comment by hdstar2009** [comment]
之前用lxk的库，没用面板，auto_help.sh处理助力码也出过段时间就出argument list too long问题，导致需要自动助力的脚本（需要atuo_help.sh export引导运行）运行失败。折腾很久，搞不定这个问题，直接脚本里面awk grep这些命令的限制（谷歌有类似错误都是建议重写代码）。今天刚刚打算所有账号转到JSTool上来，难道也要遇到相同问题？那些跑上百几百号的是怎么避免这个问题的呢？我的都不到50

**Comment by hdstar2009** [comment]
刚刚crontab不执行任务，调到前台来，果然遇到了和楼上一样的问题，jd update后已经是新的config.sh和jd.sh了，config.sh的新设置参数也默认保持了，还是一样错误。这个和我用lxk的库，auto_help.sh报错很类似，我是折腾很久（不想删账号数量，47个而已）搞不定才换到本面板，可惜还是同样问题。
root@jd:/etc/init.d $ crond -f
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1341: /bin/date: Argument list too long
/usr/local/bin/jd: line 1546: /bin/date: Argument list too long
/usr/local/bin/jd: line 1550: /usr/bin/tee: Argument list too long
您的操作系统为：UnKnow 架构：aarch64
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long
/usr/local/bin/jd: line 1213: /usr/bin/perl: Argument list too long
/usr/local/bin/jd: line 1341: /bin/date: Argument list too long
/usr/local/bin/jd: line 1546: /bin/date: Argument list too long
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long
/usr/local/bin/jd: line 1550: /usr/bin/tee: Argument list too long
您的操作系统为：UnKnow 架构：aarch64
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long
/usr/local/bin/jd: line 2: /bin/base64: Argument list too long

**Comment by hdstar2009** [comment]
真是无解吗？为什么下午刚刚设置好账号的时候没问题，我终端手工运行脚本都正常，cfd fruit等脚本手工运行都正常。
而到了晚上，发现crontab任务没启动，crond调到前台就发现 Argument list too long错误，出现这错误脚本就运行不了了。

**Comment by lan-tianxiang** [comment]
你把自动助力的功能关了先

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："hdstar2009 ***@***.***&gt;;
发送时间：2021年6月18日(星期五) 晚上10:14
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] /usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long (#135)
-----------------------------------

 

 
真是无解吗？为什么下午刚刚设置好账号的时候没问题，我终端手工运行脚本都正常，cfd fruit等脚本手工运行都正常。
 而到了晚上，发现crontab任务没启动，crond调到前台就发现 Argument list too long错误，出现这错误脚本就运行不了了。

**Comment by hdstar2009** [comment]
> 你把自动助力的功能关了先
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："hdstar2009 ***@***.***&gt;; 发送时间：2021年6月18日(星期五) 晚上10:14 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] /usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long (#135) ----------------------------------- 真是无解吗？为什么下午刚刚设置好账号的时候没问题，我终端手工运行脚本都正常，cfd fruit等脚本手工运行都正常。 而到了晚上，发现crontab任务没启动，crond调到前台就发现 Argument list too long错误，出现这错误脚本就运行不了了。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

关了就不能内部多个账号助力了啊。下午去装了青龙，也一样有这种问题，他那个还更厉害，20多个账号就出现：
/usr/local/bin/task: line 21: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 122: /bin/date: Argument list too long
/usr/local/bin/task: line 128: /usr/local/bin/task: line 128: /usr/local/bin/task: line 128: /bin/sed: Argument list too long
/usr/local/bin/task: line 128: /usr/bin/xargs: Argument list too long
/usr/bin/perl: Argument list too long
/bin/grep: Argument list too long
/usr/local/bin/task: line 128: /bin/cat: Argument list too long
/ql/shell/api.sh: line 154: /bin/date: Argument list too long
/ql/shell/api.sh: line 168: /usr/bin/curl: Argument list too long
/ql/shell/api.sh: line 168: /usr/bin/jq: Argument list too long
/ql/shell/api.sh: line 169: /usr/bin/jq: Argument list too long
更新任务状态失败()
/usr/local/bin/task: line 130: /usr/bin/tee: Argument list too long
/ql/shell/api.sh: line 154: /bin/date: Argument list too long
/ql/shell/api.sh: line 168: /usr/bin/curl: Argument list too long
/ql/shell/api.sh: line 168: /usr/bin/jq: Argument list too long
/ql/shell/api.sh: line 169: /usr/bin/jq: Argument list too long
更新任务状态失败()

执行结束...

**Comment by biewenwoshishui021** [comment]
咨询一下，我termux，为何每次执行更新，都会提示如下权限拒绝的代码。。？？谢谢


/data/data/com.termux/files/home/JS_TOOL/scripts成功...

检测到有失效的定时任务：

jd_necklace
jd_xtg
jd_xtg_help
jd_zoo
jd_zooCollect

开始尝试自动删除jd_scipts脚本的定时任务...

Can't do inplace edit on /data/data/com.termux/files/home/JS_TOOL/config/crontab.list: Cannot make temp name: Permission denied.
Can't do inplace edit on /data/data/com.termux/files/home/JS_TOOL/config/crontab.list: Cannot make temp name: Permission denied.
Can't do inplace edit on /data/data/com.termux/files/home/JS_TOOL/config/crontab.list: Cannot make temp name: Permission denied.
Can't do inplace edit on /data/data/com.termux/files/home/JS_TOOL/config/crontab.list: Cannot make temp name: Permission denied.
Can't do inplace edit on /data/data/com.termux/files/home/JS_TOOL/config/crontab.list: Cannot make temp name: Permission denied.
成功删除失效的jd_scipts脚本的定时任务...

**Comment by sorker** [comment]
> > 你把自动助力的功能关了先
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："hdstar2009 _**@**_._**>; 发送时间：2021年6月18日(星期五) 晚上10:14 收件人："lan-tianxiang/JS_TOOL" _**@**_.**_>; 抄送："lan-tianxiang _**@**_._**>;"Comment _**@**_.**_>; 主题：Re: [lan-tianxiang/JS_TOOL] /usr/local/bin/thirdpard: line 1214: /usr/bin/perl: Argument list too long (#135) ----------------------------------- 真是无解吗？为什么下午刚刚设置好账号的时候没问题，我终端手工运行脚本都正常，cfd fruit等脚本手工运行都正常。 而到了晚上，发现crontab任务没启动，crond调到前台就发现 Argument list too long错误，出现这错误脚本就运行不了了。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 关了就不能内部多个账号助力了啊。下午去装了青龙，也一样有这种问题，他那个还更厉害，20多个账号就出现：
> /usr/local/bin/task: line 21: /usr/bin/perl: Argument list too long
> /usr/local/bin/task: line 122: /bin/date: Argument list too long
> /usr/local/bin/task: line 128: /usr/local/bin/task: line 128: /usr/local/bin/task: line 128: /bin/sed: Argument list too long
> /usr/local/bin/task: line 128: /usr/bin/xargs: Argument list too long
> /usr/bin/perl: Argument list too long
> /bin/grep: Argument list too long
> /usr/local/bin/task: line 128: /bin/cat: Argument list too long
> /ql/shell/api.sh: line 154: /bin/date: Argument list too long
> /ql/shell/api.sh: line 168: /usr/bin/curl: Argument list too long
> /ql/shell/api.sh: line 168: /usr/bin/jq: Argument list too long
> /ql/shell/api.sh: line 169: /usr/bin/jq: Argument list too long
> 更新任务状态失败()
> /usr/local/bin/task: line 130: /usr/bin/tee: Argument list too long
> /ql/shell/api.sh: line 154: /bin/date: Argument list too long
> /ql/shell/api.sh: line 168: /usr/bin/curl: Argument list too long
> /ql/shell/api.sh: line 168: /usr/bin/jq: Argument list too long
> /ql/shell/api.sh: line 169: /usr/bin/jq: Argument list too long
> 更新任务状态失败()
> 
> 执行结束...

我青龙 + 花语，搞了一天都不行，不知道怎么使用cookie。目前只知道青龙可以环境变量里加，如果从环境里加那花语就没什么用了。请问你用了花语的前后端吗？怎么查看和使用花语cookie配置，现在花语的删库跑路了，我猜是go写的，没有学过go！！！
