### ISSUE TITLE
设置主库之后crontab.list没有主库的定时设置

### ISSUE THREAD

**Issue by lj0307222** [lan-tianxiang/JS_TOOL#136]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

这是我设置的主库问题吗

**Comment by lan-tianxiang** [comment]
设定的主库必须得带有定时文件，不然不会自动增加定时配置

**Comment by lj0307222** [comment]
大佬求助  openwrt安装了docker  拉取镜像运行后修改config.sh 
ENABLE_TG_BOT="false"   为true 重启后还是没启用tgbot  不知道是不是我哪里弄错了

**Comment by Saoforest** [comment]
> 设定的主库必须得带有定时文件，不然不会自动增加定时配置

想问一下定时文件是哪个文件 在哪个目录下？ 想自己定义一个...

**Comment by lan-tianxiang** [comment]
@lj0307222   docker还得安装python环境

**Comment by lan-tianxiang** [comment]
@Saoforest   位于脚本目录下(scripts)的docker文件夹中，命名为
![image](https://user-images.githubusercontent.com/42911023/122141744-8c4e2780-ce80-11eb-9d0e-05010c53520b.png)

**Comment by xiaojia21190** [comment]
能给一份原来的定时任务吗
