### ISSUE TITLE
老大，请问您的镜像映射目录是什么

### ISSUE THREAD

**Issue by donggua1118** [lan-tianxiang/JS_TOOL#137]
### 想要增加什么样的功能或者哪里存在不足之处呢？

一直用v3和v4，突然发现您的镜像是两者的加强版，很是喜欢，没有按照您的一键安装，自己按照v4的方式安装发现没有映射文件，请问老大，映射目录分别是什么呀？

**Comment by lan-tianxiang** [comment]
/root/jd

**Comment by donggua1118** [comment]
感谢老大，我重新部署吧

**Comment by Soarfree** [comment]
> /root/jd

能不能把scripts脚本目录也映射到JD目录 这样同步的脚本比较方便修改
