### ISSUE TITLE
请问是否考虑添加除jd商城以外的其他平台脚本?

### ISSUE THREAD

**Issue by HarrisonQi** [lan-tianxiang/JS_TOOL#138]
### 想要增加什么样的功能或者哪里存在不足之处呢？

持续观察了作者的仓库, 仓库名由`jd_tool`转为`js_tool`. 大胆猜测将来作者将不局限于jd的脚本. 

请问是否考虑纳入其他平台的脚本?

类似于这个仓库, 包含多个平台的脚本:
[dailycheckin](https://github.com/Sitoi/dailycheckin)

**Comment by lan-tianxiang** [comment]
对的，我把外部扫码自动添加cookie写完之后，就开始添加其他平台

**Comment by HarrisonQi** [comment]
作者nb!

**Comment by snakexgc** [comment]
顶，大佬牛逼，大佬辛苦了！

**Comment by qq7984225** [comment]
搞好了吗

**Comment by happyskey** [comment]
作者nb!

**Comment by SQDFeng** [comment]
太强了！
