### ISSUE TITLE
大佬 可以参考下这个

### ISSUE THREAD

**Issue by Soarfree** [lan-tianxiang/JS_TOOL#139]
https://github.com/cmazfuture/JDC-web     JDC前端仓库
扫码登陆时一个单独的账号 推送也是单独的 
![screencapture-211977992-f3322-net-5701-1623741927924](https://user-images.githubusercontent.com/28619123/122011158-65471580-cdee-11eb-8eb7-61cc8e8d5241.png)
![screencapture-211977992-f3322-net-5701-1623741943012](https://user-images.githubusercontent.com/28619123/122011182-6aa46000-cdee-11eb-8685-b77fdd48bb82.png)
![screencapture-211977992-f3322-net-5701-1623741955025](https://user-images.githubusercontent.com/28619123/122011200-6ed07d80-cdee-11eb-9cd3-4b70b7b17fd8.png)

**Comment by lan-tianxiang** [comment]
嗯，谢谢
