### ISSUE TITLE
“日志查询”页面 - 右侧显示空白

### ISSUE THREAD

**Issue by dalant2019** [lan-tianxiang/JS_TOOL#142]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：
      此前一直使用正常，但删除旧容器并拉取最新的**docker_install_jd.sh**（更新于 06-14 23:24）一键安装后，控制面板的“**日志查询**” 页面显示异常，任意选中一个日志但右侧都是一片空白，而在log目录下面都能找到相关的日志文件
      浏览器为chrome，亦尝试更换非chrome内核的浏览器登陆控制面板但结果一样都是右侧为空白无法正常显示日志

### (2) 详细日志
A：

**Comment by dalant2019** [comment]
作者，不好意思，问题出在我自身上面

    尝试关闭科学上网功能后发现问题解决，估计是受到广告过滤功能影响导致。请忽略此问题，如果有遇到页面显示异常的朋友也可以试试停用广告过滤功能，或者加入到白名单

**Comment by lan-tianxiang** [comment]
嗯😊
