### ISSUE TITLE
Cpu爆满

### ISSUE THREAD

**Issue by xiaorizi01** [lan-tianxiang/JS_TOOL#143]
大佬，最近更新之后  cpu很容易爆满！有发现这个问题吗！然后停用容器 cpu就又慢慢恢复了！不知道就我这样。还是其他人也有这个问题

**Comment by dalant2019** [comment]
挂了13个号CPU占用率没超过10%，另外提出问题的时候也请将自己的使用场景和环境描述一下以便于作者或其他人答疑，方便他人也等于方便自己，你说是吗？

**Comment by zhangleqin** [comment]
> 大佬，最近更新之后 cpu很容易爆满！有发现这个问题吗！然后停用容器 cpu就又慢慢恢复了！不知道就我这样。还是其他人也有这个问题

这个很可能是被装了挖矿程序 就这点JS跑不满什么CPU的如果只运行这个仓库 可以重装一下 换个密码 甚至密钥登录，现在暴力破密码 再盗用挖矿的太多了
