### ISSUE TITLE
第三方的定时任务如何编写？

### ISSUE THREAD

**Issue by hubing0917** [lan-tianxiang/JS_TOOL#144]
新增任务通知

成功添加新的定时任务（thirdpard脚本）：
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_cash.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_dreamFactory.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_joy_feedPets.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_joy_reward.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_jxlhb.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_syj.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_zoo.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/https:/github.com/JDHelloWorld/jd_scripts.git/jd_zooCollect.js

仅供用于学习 https://t.me/jdfruit

定时任务中的thirdpard部分如何编写？
1.这里的jd是目录吗？
* * * * * * (jd) jd_aaaa
2.我的环境是window server hyperv虚拟的Ubuntu docker，用finshell，如何进入root文件夹？
谢谢🙏

**Comment by lan-tianxiang** [comment]
进入root文件夹`cd /root`
定时任务中的thirdpard部分，如果库自带定时的话，就不用自己设定，如果没有的话。
进入面板的定时设定，接着举第一个新增为例   `35 */4 * * * jd jd_cash.js`就可以了
第二的话就是`35 */4 * * * jd_dreamFactory.js`  前面的`35 */4 * * *`可以自己设置

**Comment by hubing0917** [comment]
进入root，jd目录还是不成功，我用的是finalshell。环境如上。

**Comment by lan-tianxiang** [comment]
直接用面板的终端就可以了

**Comment by hubing0917** [comment]
> 直接用面板的终端就可以了

好吧

**Comment by aburdchen415** [comment]
> 进入root文件夹`cd /root`
> 定时任务中的thirdpard部分，如果库自带定时的话，就不用自己设定，如果没有的话。
> 进入面板的定时设定，接着举第一个新增为例 `35 */4 * * * jd jd_cash.js`就可以了
> 第二的话就是`35 */4 * * * jd_dreamFactory.js` 前面的`35 */4 * * *`可以自己设置

5 */4 * * * jd jd_cash.js 这句在jd目录定时的是第三方的任务？不是你的主任务？
