### ISSUE TITLE
统计脚本刷得京豆功能

### ISSUE THREAD

**Issue by fan77777** [lan-tianxiang/JS_TOOL#148]
### 想要增加什么样的功能或者哪里存在不足之处呢？

我想请问下大佬，可不可以增加一个统计功能，统计单靠脚本刷得京豆的数量，而不是账户京豆单日变化。麻烦大佬了。

**Comment by lan-tianxiang** [comment]
账户京豆单日变化就是统计的各个活动所得的数量，如果单统计靠脚本刷得的，比较难区分开。不过可以列出各个活动所得的数量
