### ISSUE TITLE
种豆得豆，4个账号内部互助应该每个账号3次，但是为什么都是2次

### ISSUE THREAD

**Issue by yuezhengchao** [lan-tianxiang/JS_TOOL#149]
log/helpcode中显示设置是正确的，为什么结果了就少了1个内部互助码？
![image](https://user-images.githubusercontent.com/77090717/122232938-3a43eb00-ceee-11eb-9ebd-9a47825d3718.png)
![image](https://user-images.githubusercontent.com/77090717/122232993-4465e980-ceee-11eb-81e4-f629ec92fe3b.png)

**Comment by lan-tianxiang** [comment]
兄弟注意一下，
![image](https://user-images.githubusercontent.com/42911023/122243080-69f6f100-cef6-11eb-82bb-bfc18f24e091.png) ，
![image](https://user-images.githubusercontent.com/42911023/122243131-73805900-cef6-11eb-90b4-e50fdbeb2aa3.png)
你应该懂什么意思了吧

**Comment by lan-tianxiang** [comment]
后面三个是脚本作者助力的码，第一个账号助力三个，不就是前三个吗？

**Comment by lan-tianxiang** [comment]
`4个账号内部互助应该每个账号3次，但是为什么都是2次`  

标题所述的内容有点不懂，不就是助力三个吗，怎么会两个呢

**Comment by aburdchen415** [comment]
设置有问题吧，forotherbean1助力的是mybean1？自己助力自己？

**Comment by yuezhengchao** [comment]
感谢各位，懂了，我先试下，但是我没有设置，都是软件自动设置助力模式的
