### ISSUE TITLE
重启bug

### ISSUE THREAD

**Issue by lj0307222** [lan-tianxiang/JS_TOOL#15]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：openwrt下重启失败

### (2) 详细日志
A：crond[8]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[8]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[8]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[8]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[8]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

crond[7]: crond (busybox 1.31.1) started, log level 8

cp: cannot stat '/sample/config.sh.sample': No such file or directory

**Comment by ZJUprince** [comment]
我也是这个问题  docker用户 伤心 等待解决

**Comment by happyskey** [comment]
更新了最新的docker pull ,直接无限重启容器，直接用不了，日志里和楼主一个提示

**Comment by lan-tianxiang** [comment]
已修复，删除镜像后，重新部署

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："happyskey ***@***.***&gt;;
发送时间：2021年5月25日(星期二) 晚上10:05
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 重启bug (#15)
-----------------------------------

 

 
更新了最新的docker pull ,直接无限重启容器，直接用不了，日志里和楼主一个提示
