### ISSUE TITLE
屏蔽部分cookie不做指定活动功能失效，写了配置语句，检查了语句正确性性，但是未生效，屏蔽的cookie还是执行指定的活动

### ISSUE THREAD

**Issue by DdQhM** [lan-tianxiang/JS_TOOL#151]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
检查了语句正确性，怎么保证一定正确呢。
这边程序没问题，你可以把你的配置发出来给我们看一下

**Comment by DdQhM** [comment]
> 检查了语句正确性，怎么保证一定正确呢。
> 这边程序没问题，你可以把你的配置发出来给我们看一下

![image](https://user-images.githubusercontent.com/85662729/122313526-f16d5000-cf48-11eb-8704-41df381a890e.png)

**Comment by lan-tianxiang** [comment]
嗯，的确正确的，把最后一行删了就行了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："AnM ***@***.***&gt;;
发送时间：2021年6月17日(星期四) 上午8:49
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 屏蔽部分cookie不做指定活动功能失效，写了配置语句，检查了语句正确性性，但是未生效，屏蔽的cookie还是执行指定的活动 (#151)
-----------------------------------

 

  
检查了语句正确性，怎么保证一定正确呢。
 这边程序没问题，你可以把你的配置发出来给我们看一下

**Comment by lan-tianxiang** [comment]
Tempxxxx的那一行

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："AnM ***@***.***&gt;;
发送时间：2021年6月17日(星期四) 上午8:49
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 屏蔽部分cookie不做指定活动功能失效，写了配置语句，检查了语句正确性性，但是未生效，屏蔽的cookie还是执行指定的活动 (#151)
-----------------------------------

 

  
检查了语句正确性，怎么保证一定正确呢。
 这边程序没问题，你可以把你的配置发出来给我们看一下

**Comment by DdQhM** [comment]
> 嗯，的确正确的，把最后一行删了就行了
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："AnM ***@***.***&gt;; 发送时间：2021年6月17日(星期四) 上午8:49 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 屏蔽部分cookie不做指定活动功能失效，写了配置语句，检查了语句正确性性，但是未生效，屏蔽的cookie还是执行指定的活动 (#151) ----------------------------------- 检查了语句正确性，怎么保证一定正确呢。 这边程序没问题，你可以把你的配置发出来给我们看一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢！！！！！！！！！！！！！！！

**Comment by Rosylusi** [comment]
> 
> Tempxxxx的那一行
> [… ](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："AnM ***@***.***>; 发送时间：2021年6月17日(星期四) 上午8:49 收件人："lan-tianxiang/JS_TOOL" ***@***.***>; 抄送："lan-tianxiang ***@***.***>;"Comment ***@***.***>; 主题：Re: [lan-tianxiang/JS_TOOL] 屏蔽部分cookie不做指定活动功能失效，写了配置语句，检查了语句正确性性，但是未生效，屏蔽的cookie还是执行指定的活动 ( [#151 ](https://github.com/lan-tianxiang/JS_TOOL/issues/151)) ----------------------------------- 检查了语句正确性，怎么保证一定正确呢。 这边程序没问题，你可以把你的配置发出来给我们看一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，有没有可能做成直接屏蔽掉某个cookie，推送的时候还是按照用户配置里面的编号来

**Comment by lan-tianxiang** [comment]
@895450603  屏蔽某个cookie，那就不会运行账户的推送，你可以写一个单独屏蔽该账户全部的脚本，除了一个每个变化的脚本
