### ISSUE TITLE
自定了第三方库，更新时有报错

### ISSUE THREAD

**Issue by happyskey** [lan-tianxiang/JS_TOOL#152]
JD_SCRIPTS_URL="https://ghproxy.com/https://github.com/zero205/JD_tencent_scf.git"
开始更新仓库：/root/jd/scripts

Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Updating 5a953b7..7853b4b
error: Your local changes to the following files would be overwritten by merge:
        .github/workflows/deploy_tencent_scf.yml
        README.md
        githubAction.md
        jd_big_winner.js
        jd_chb.js
        jd_dreamFactory.js
        jd_dyj.js
        jd_jxlhb.js
        jd_speed_redpocke.js
        jd_speed_sign.js
        jd_star_shop.js
        jd_task.json
        jd_tyt.js
        jd_zoo.js
        jd_zooCollect.js
        package.json
        serverless.yml
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        jd_jxmc.js
Please move or remove them before you merge.
Aborting

更新/root/jd/scripts成功...

**Comment by Rosylusi** [comment]
这个库好像没有定时文件的

**Comment by 895450603** [comment]
而且你这个仓库地址是不是错了？

**Comment by zhangleqin** [comment]
你填错地方了 应该填在最后third那边

**Comment by lukemin** [comment]
这个库没有定时文件，不好用啊。

**Comment by happyskey** [comment]
有没有推荐的库



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 下午5:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lan-tianxiang/JS_TOOL] 自定了第三方库，更新时有报错 (#152)





 
这个库没有定时文件，不好用啊。
 
&mdash;

**Comment by zhangleqin** [comment]
ThirdpardRepoUrl1="https://github.com/zero205/JD_tencent_scf.git"
ThirdpardRepoUrl2=""

ThirdpardRepoBranch1=""
ThirdpardRepoBranch2=""

ThirdpardRepoPath1=""
ThirdpardRepoPath2=""

填在这里 自动加定时 你们把主库替代掉 自然没有定时。。。。
