### ISSUE TITLE
对于京东健康社区邀请助力没有提供手写助力码的脚本怎么实现助力？

### ISSUE THREAD

**Issue by hdstar2009** [lan-tianxiang/JS_TOOL#153]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

配置config.sh没有设置互助码的地方，那么这个jd_health.js脚本要怎么运行才能实现内部账号的邀请助力？直接jd js_health.js并不能实现。
lxk是使用：
/scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_health.js  来实现的。
同样的疑问，财富岛、东东农场如果要实现多个账号循序互助，在JS_TOOL下要怎么操作？

**Comment by ryan016** [comment]
################################## 导出互助码模板样式（选填） ###################################
## 定义 myhelp 脚本导出的互助码模板样式。
## 默认 使用“按编号顺序助力模板”，Cookie编号在前的优先助力
## 填 0 使用“全部一致助力模板”，所有账户要助力的码全部一致
## 填 1 使用“均等机会助力模板”，所有账户获得助力次数一致
## 填 2 使用“随机顺序助力模板”，本套脚本内账号间随机顺序助力，每次生成的顺序都不一致。
HelpType=""

**Comment by hdstar2009** [comment]
> ################################## 导出互助码模板样式（选填） ###################################
> 
> ## 定义 myhelp 脚本导出的互助码模板样式。
> ## 默认 使用“按编号顺序助力模板”，Cookie编号在前的优先助力
> ## 填 0 使用“全部一致助力模板”，所有账户要助力的码全部一致
> ## 填 1 使用“均等机会助力模板”，所有账户获得助力次数一致
> ## 填 2 使用“随机顺序助力模板”，本套脚本内账号间随机顺序助力，每次生成的顺序都不一致。
> HelpType=""

谢谢。我去看看，我整理下，有一点乱。
