### ISSUE TITLE
第三方库js映射到哪里了？

### ISSUE THREAD

**Issue by qaz88q11** [lan-tianxiang/JS_TOOL#154]
### 想要增加什么样的功能或者哪里存在不足之处呢？

第三方库js映射到哪里了？找不到文件夹啊！一键部署的时候也没有选项！
检测到有新的定时任务：

/root/jd/thirdpard/JDHelloWorld_jd_scripts/jd_api_test.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/jd_bean_change.js
/root/jd/thirdpard/JDHelloWorld_jd_scripts/jd_bean_home.js
没有这个目录/root/jd/thirdpard，一键部署的时候只映射了 config  log  config这三个文件夹，请问第三方js文件映射到哪里去了？

**Comment by hixuchang** [comment]
通过网页上方工具栏的“终端”进入
