### ISSUE TITLE
添加第三方库的办法

### ISSUE THREAD

**Issue by zhangleqin** [lan-tianxiang/JS_TOOL#155]
给大家使用上指条路

在设定文件中 以下位置：

ThirdpardRepoUrl1="https://github.com/zero205/JD_tencent_scf.git"
ThirdpardRepoUrl2=""

ThirdpardRepoBranch1=""
ThirdpardRepoBranch2=""

ThirdpardRepoPath1=""
ThirdpardRepoPath2=""

填在这里 自动加定时 你们把主库替代掉 自然没有定时。。。。

我现在的定时设定 自动生成的：

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

# 更新所有脚本（包括自用thirdpard脚本）
22,44 * * * * sleep 44 && jd update >> /root/jd/log/jd.log 2>&1

# 删除 RmLogDaysAgo 指定天数以前的旧日志，本行为不记录日志：
57 13 * * * jd clean

# 导出所有互助码清单，日志在log/helpcode下
48 * * * * jd myhelp

# 重启挂机程序
# 33 13 * * * jd hangup

# DIY任务区域
# 需自行将脚本放在scripts文件夹下

# thirdpard任务区域
# 定时区域thirdpard开始，误删

2 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_change.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_home.js
1 7,12,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_beauty.js
20 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_big_winner.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_blueCoin.js
1 8,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bookshop.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car_exchange.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car.js
0 0-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_carnivalcity.js
0,1,2 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash_exchange.js
2 0-23/4 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash.js
5 8,13,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cfd.js
5 0,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_club_lottery.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_bonus.js
10 1,12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_coin.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_daily_egg.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_dreamFactory.js
1 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_family.js
5 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_fruit.js
20 13 * * 6 thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_get_share_code.js
13 1,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_gold_creator.js
30 16-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_half_redrain.js
10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdfactory.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdzz.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jin_tie.js
15 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_feedPets.js
15 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy.js
0 0-16/8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_reward.js
15 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_run.js
10 0-21/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_steal.js
1 0,11,21 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jump.js
30 8,16,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxd.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxlhb.js
0 9,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxnc.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_kd.js
10-20/5 12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live.js
0,30 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live_redrain.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_market_lottery.js
4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mcxhd.js
0 0,1-23/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mohe.js
3 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_moneyTree.js
10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_ms.js
10 0,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_necklace.js
35 1,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_nzmh.js
15 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pet.js
12 0-23/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pigPet.js
1 7-21/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_plantBean.js
11 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_rankingList.js
1 1,2,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_redPacket.js
20 8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_sgmh.js
10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_shop.js
16 22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_small_home.js
20 0,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_redpocke.js
0 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_sign.js
11 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_superMarket.js
1 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_super_redrain.js
10 0,7,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_syj.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_tyt.js
55 23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_unsubscribe.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xsmh.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg_help.js
0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg.js
0 5 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zjb.js
0-59/30 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zooCollect.js
36 0,6-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zoo.js
10 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zooMap.js
# 定时区域thirdpard结束，误删

# jd任务区域，运行jd_scripts脚本，仅列出长期任务作初始化用，AutoAddCron=true时，将自动添加短期任务。
# 请保留任务名称中的前缀""jd_""，去掉后缀"".js""，如果有些任务你不想运行，注释掉就好了，不要删除。
# 非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。
20 10 * * * jd jd_bean_change
23 1,12,22 * * * jd jd_bean_home
4 0,9 * * * jd jd_bean_sign
41 7,12,19 * * * jd jd_beauty
10,40 * * * * jd jd_big_winner
0,30 0 * * * jd jd_blueCoin
38 8,12,18 * * * jd jd_bookshop
0 0 * * * jd jd_car
0 0 * * * jd jd_car_exchange
0 0,12,18,21 * * * jd jd_carnivalcity
10 */4 * * * jd jd_cash
5 7,12,18 * * * jd jd_cfd
6 0,23 * * * jd jd_club_lottery
30 7,23 * * * jd jd_crazy_joy
10 12 * * * jd jd_crazy_joy_bonus
28 * * * * jd jd_daily_egg
#13 1,22,23 * * * jd jd_daily_lottery
15 0,6,13,19,21 * * * jd jd_ddo_pk
#20 9 * * 6 jd jd_delCoupon
50 * * * * jd jd_dreamFactory
10 6,7 * * * jd jd_family
15 6-18/6 * * * jd jd_fruit
23 7 * * * jd jd_get_share_code
0 1,22 * * * jd jd_gold_creator
13 1,6,22 * * * jd jd_health
5-45/20 * * * * jd jd_health_collect
26 * * * * jd jd_jdfactory
6 0-5/1,11 * * * jd jd_jdzz
5 0 * * * jd jd_jin_tie
45 */2,23 * * * jd jd_joy
35 */1 * * * jd jd_joy_feedPets
0 0-16/8 * * * jd jd_joy_reward
10 13-20/1 * * * jd jd_joy_run
15 0,12,22 * * * jd jd_jump
30 1,6,12,21 * * * jd jd_jxlhb
15 0,12,22 * * * jd jd_jxmc
30 9,12,18 * * * jd jd_jxnc
47 1 * * * jd jd_kd
30-50/5 12,23 * * * jd jd_live
1,31 0-23/1 * * * jd jd_live_redrain
0 0,12,23 * * * jd jd_lotteryMachine
10 10,23 * * * jd jd_market_lottery
20 1,21 * * * jd jd_mcxhd
0 0-23/4 * * * jd jd_mohe
23 */2 * * * jd jd_moneyTree
10 6,21 * * * jd jd_ms
35 1,22 * * * jd jd_nzmh
35 6-18/6 * * * jd jd_pet
32 0-23/6 * * * jd jd_pigPet
10 7-22/1 * * * jd jd_plantBean
#41 0,23 * * * jd jd_price
21 9 * * * jd jd_rankingList
12 0-23/4 * * * jd jd_redPacket
47 8,22 * * * jd jd_sgmh
6 0 * * * jd jd_shop
46 6,23 * * * jd jd_small_home
45 0,23 * * * jd jd_speed_redpocke
21 1,6 * * * jd jd_speed_sign
0 1,21 * * * jd jd_star_shop
31 0,1-23/2 * * * jd jd_superMarket
12 */4 * * * jd jd_syj
45 23 * * * jd jd_unsubscribe
0 0 * * * jd jd_xtg
0 0 * * * jd jd_xtg_help
10 10,18 * * * jd jd_try

**Comment by lan-tianxiang** [comment]
嗯，帮你Pin上去给大家看看

**Comment by 895450603** [comment]
ThirdpardRepoUrl1在哪个文件当中？

**Comment by 895450603** [comment]
> 给大家使用上指条路
> 
> 在设定文件中 以下位置：
> 
> ThirdpardRepoUrl1="https://github.com/zero205/JD_tencent_scf.git"
> ThirdpardRepoUrl2=""
> 
> ThirdpardRepoBranch1=""
> ThirdpardRepoBranch2=""
> 
> ThirdpardRepoPath1=""
> ThirdpardRepoPath2=""
> 
> 填在这里 自动加定时 你们把主库替代掉 自然没有定时。。。。
> 
> 我现在的定时设定 自动生成的：
> 
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
> 
> # 更新所有脚本（包括自用thirdpard脚本）
> 22,44 * * * * sleep 44 && jd update >> /root/jd/log/jd.log 2>&1
> 
> # 删除 RmLogDaysAgo 指定天数以前的旧日志，本行为不记录日志：
> 57 13 * * * jd clean
> 
> # 导出所有互助码清单，日志在log/helpcode下
> 48 * * * * jd myhelp
> 
> # 重启挂机程序
> # 33 13 * * * jd hangup
> # DIY任务区域
> # 需自行将脚本放在scripts文件夹下
> # thirdpard任务区域
> # 定时区域thirdpard开始，误删
> 2 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_change.js
> 10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bean_home.js
> 1 7,12,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_beauty.js
> 20 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_big_winner.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_blueCoin.js
> 1 8,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_bookshop.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car_exchange.js
> 10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_car.js
> 0 0-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_carnivalcity.js
> 0,1,2 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash_exchange.js
> 2 0-23/4 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cash.js
> 5 8,13,19 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_cfd.js
> 5 0,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_club_lottery.js
> 10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_bonus.js
> 10 1,12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy_coin.js
> 10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_crazy_joy.js
> 10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_daily_egg.js
> 10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_dreamFactory.js
> 1 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_family.js
> 5 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_fruit.js
> 20 13 * * 6 thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_get_share_code.js
> 13 1,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_gold_creator.js
> 30 16-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_half_redrain.js
> 10 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdfactory.js
> 10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jdzz.js
> 10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jin_tie.js
> 15 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_feedPets.js
> 15 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy.js
> 0 0-16/8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_reward.js
> 15 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_run.js
> 10 0-21/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_joy_steal.js
> 1 0,11,21 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jump.js
> 30 8,16,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxd.js
> 4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxlhb.js
> 0 9,12,18 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_jxnc.js
> 10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_kd.js
> 10-20/5 12 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live.js
> 0,30 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_live_redrain.js
> 4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_market_lottery.js
> 4 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mcxhd.js
> 0 0,1-23/3 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_mohe.js
> 3 0-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_moneyTree.js
> 10 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_ms.js
> 10 0,20 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_necklace.js
> 35 1,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_nzmh.js
> 15 6-18/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pet.js
> 12 0-23/6 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_pigPet.js
> 1 7-21/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_plantBean.js
> 11 9 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_rankingList.js
> 1 1,2,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_redPacket.js
> 20 8 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_sgmh.js
> 10 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_shop.js
> 16 22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_small_home.js
> 20 0,22 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_redpocke.js
> 0 7 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_speed_sign.js
> 11 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_superMarket.js
> 1 0-23/1 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_super_redrain.js
> 10 0,7,23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_syj.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_tyt.js
> 55 23 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_unsubscribe.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xsmh.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg_help.js
> 0 0 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_xtg.js
> 0 5 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zjb.js
> 0-59/30 * * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zooCollect.js
> 36 0,6-23/2 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zoo.js
> 10 10 * * * thirdpard /root/jd/thirdpard/zero205_JD_tencent_scf/jd_zooMap.js
> 
> # 定时区域thirdpard结束，误删
> # jd任务区域，运行jd_scripts脚本，仅列出长期任务作初始化用，AutoAddCron=true时，将自动添加短期任务。
> # 请保留任务名称中的前缀""jd_""，去掉后缀"".js""，如果有些任务你不想运行，注释掉就好了，不要删除。
> # 非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。
> 20 10 * * * jd jd_bean_change
> 23 1,12,22 * * * jd jd_bean_home
> 4 0,9 * * * jd jd_bean_sign
> 41 7,12,19 * * * jd jd_beauty
> 10,40 * * * * jd jd_big_winner
> 0,30 0 * * * jd jd_blueCoin
> 38 8,12,18 * * * jd jd_bookshop
> 0 0 * * * jd jd_car
> 0 0 * * * jd jd_car_exchange
> 0 0,12,18,21 * * * jd jd_carnivalcity
> 10 */4 * * * jd jd_cash
> 5 7,12,18 * * * jd jd_cfd
> 6 0,23 * * * jd jd_club_lottery
> 30 7,23 * * * jd jd_crazy_joy
> 10 12 * * * jd jd_crazy_joy_bonus
> 28 * * * * jd jd_daily_egg
> #13 1,22,23 * * * jd jd_daily_lottery
> 15 0,6,13,19,21 * * * jd jd_ddo_pk
> #20 9 * * 6 jd jd_delCoupon
> 50 * * * * jd jd_dreamFactory
> 10 6,7 * * * jd jd_family
> 15 6-18/6 * * * jd jd_fruit
> 23 7 * * * jd jd_get_share_code
> 0 1,22 * * * jd jd_gold_creator
> 13 1,6,22 * * * jd jd_health
> 5-45/20 * * * * jd jd_health_collect
> 26 * * * * jd jd_jdfactory
> 6 0-5/1,11 * * * jd jd_jdzz
> 5 0 * * * jd jd_jin_tie
> 45 */2,23 * * * jd jd_joy
> 35 */1 * * * jd jd_joy_feedPets
> 0 0-16/8 * * * jd jd_joy_reward
> 10 13-20/1 * * * jd jd_joy_run
> 15 0,12,22 * * * jd jd_jump
> 30 1,6,12,21 * * * jd jd_jxlhb
> 15 0,12,22 * * * jd jd_jxmc
> 30 9,12,18 * * * jd jd_jxnc
> 47 1 * * * jd jd_kd
> 30-50/5 12,23 * * * jd jd_live
> 1,31 0-23/1 * * * jd jd_live_redrain
> 0 0,12,23 * * * jd jd_lotteryMachine
> 10 10,23 * * * jd jd_market_lottery
> 20 1,21 * * * jd jd_mcxhd
> 0 0-23/4 * * * jd jd_mohe
> 23 */2 * * * jd jd_moneyTree
> 10 6,21 * * * jd jd_ms
> 35 1,22 * * * jd jd_nzmh
> 35 6-18/6 * * * jd jd_pet
> 32 0-23/6 * * * jd jd_pigPet
> 10 7-22/1 * * * jd jd_plantBean
> #41 0,23 * * * jd jd_price
> 21 9 * * * jd jd_rankingList
> 12 0-23/4 * * * jd jd_redPacket
> 47 8,22 * * * jd jd_sgmh
> 6 0 * * * jd jd_shop
> 46 6,23 * * * jd jd_small_home
> 45 0,23 * * * jd jd_speed_redpocke
> 21 1,6 * * * jd jd_speed_sign
> 0 1,21 * * * jd jd_star_shop
> 31 0,1-23/2 * * * jd jd_superMarket
> 12 */4 * * * jd jd_syj
> 45 23 * * * jd jd_unsubscribe
> 0 0 * * * jd jd_xtg
> 0 0 * * * jd jd_xtg_help
> 10 10,18 * * * jd jd_try

老哥，方便加个企鹅指导一下吗

**Comment by Rosylusi** [comment]
> 嗯，帮你Pin上去给大家看看

按照以上方法，已从仓库拉取成功，但并未出现以上thirdpard任务区域内容，所以是要自行填写吗？

**Comment by Saoforest** [comment]
> 嗯，帮你Pin上去给大家看看

没法更换主库的时候像第三方库一样拉取定时吗?

**Comment by zhangleqin** [comment]
> > 嗯，帮你Pin上去给大家看看
> 
> 按照以上方法，已从仓库拉取成功，但并未出现以上thirdpard任务区域内容，所以是要自行填写吗？

这个牵涉到设定里面的设置 是否覆盖已有脚本 是否添加定时 去设定里面选一下 默认的不对

**Comment by zhangleqin** [comment]
> > 嗯，帮你Pin上去给大家看看
> 
> 没法更换主库的时候像第三方库一样拉取定时吗?

**Comment by zhangleqin** [comment]
> 嗯，帮你Pin上去给大家看看

害 看到一大群人理解不了你的意图 比较着急 618过了 估计人也就少了

**Comment by Rosylusi** [comment]
学习学习，摸个鱼，不然上班太无聊，嘿嘿

**Comment by zhangleqin** [comment]
> 学习学习，摸个鱼，不然上班太无聊，嘿嘿

哈 我还帮我主管挂呢 她夸我厉害 618 省了好多事

**Comment by lukemin** [comment]
> > > 嗯，帮你Pin上去给大家看看
> > 
> > 
> > 按照以上方法，已从仓库拉取成功，但并未出现以上thirdpard任务区域内容，所以是要自行填写吗？
> 
> 这个牵涉到设定里面的设置 是否覆盖已有脚本 是否添加定时 去设定里面选一下 默认的不对

默认设置需要怎么修改，方便详细说明一下吗

**Comment by 895450603** [comment]
> > 学习学习，摸个鱼，不然上班太无聊，嘿嘿
> 
> 哈 我还帮我主管挂呢 她夸我厉害 618 省了好多事

所以老哥，问个问题，ThirdpardRepo这些脚本的运行逻辑是怎样的，比如是需要手动运行还是按照定义的定时运行还是说在主仓库无法运行的时候才会运行？我看我设置以后，好像运行的还是本地的脚本，方便加企鹅请教一下吗？

**Comment by zhangleqin** [comment]
饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教

**Comment by 895450603** [comment]
> 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教

哎～这话说的，行吧，那我再好好去学习一下中文，打扰了，十分抱歉

**Comment by lukemin** [comment]
> 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
你打的每一个字我都认识，合起来我就不懂。

**Comment by zhangleqin** [comment]
> > 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
> > 你打的每一个字我都认识，合起来我就不懂。

虽然不适合说这个 但是 如果搞不明白 默认的库就很好 618过去了 Zoo不玩了 没必要用第三方库 作者的库挺好的 很方便 一键部署 适合小白
就像 你发给小孩一把AK 他还是打不过赤手空拳的大人 适合自己的才是最好的

**Comment by zhangleqin** [comment]
> > 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
> 
> 哎～这话说的，行吧，那我再好好去学习一下中文，打扰了，十分抱歉

这里是技术仓库 还是技术为先 你要是理解不了 最好还是用原版库 否则 这次学会了 还会有下个问题 没人会一直带你

**Comment by 895450603** [comment]
> > > 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
> > 
> > 
> > 哎～这话说的，行吧，那我再好好去学习一下中文，打扰了，十分抱歉
> 
> 这里是技术仓库 还是技术为先 你要是理解不了 最好还是用原版库 否则 这次学会了 还会有下个问题 没人会一直带你

就像你说的这是技术仓库，所有的技术都需要学习，并不是天生就会，我确实不懂所以提问，既然你不想做老师，也别学做教授

**Comment by 895450603** [comment]
> > > 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
> > 
> > 
> > 哎～这话说的，行吧，那我再好好去学习一下中文，打扰了，十分抱歉
> 
> 这里是技术仓库 还是技术为先 你要是理解不了 最好还是用原版库 否则 这次学会了 还会有下个问题 没人会一直带你

你也可以选择沉默不回复，我也不会一直来提问，就像我说的，我只是学习技术，作者的库也没什么不好，反而我很感谢作者提供这个渠道供我学习，我试了上方库以后，我还是在用源库，但是我只是想知道这三方库的作用和逻辑，这有错吗

**Comment by sdyby2006** [comment]
想咨询一下，配置好了以后会一直显示成功添加新的定时任务（thirdpard脚本），然后默认定时任务好像不执行了，这个是正常现象不？

**Comment by annonen** [comment]
> > > 饿 都是中文 读一下不就懂了 为啥都喜欢伸手 放在Github不就是为了过滤吗 能来这里玩 自己学一下 说明很清晰 不需要请教
> > 
> > 
> > 哎～这话说的，行吧，那我再好好去学习一下中文，打扰了，十分抱歉
> 
> 这里是技术仓库 还是技术为先 你要是理解不了 最好还是用原版库 否则 这次学会了 还会有下个问题 没人会一直带你

哈哈哈，作者是真的惨，这种伸手党就无视好了，别人给了渔具还问你要鱼的注定没法混github
