### ISSUE TITLE
多个cookies怎么同时执行同一个脚本

### ISSUE THREAD

**Issue by wossQ** [lan-tianxiang/JS_TOOL#156]
有的活动是有时效的，账号多了，导致后面的账号做任务时都没有豆子了，有没有办法可以让多个账号并发参与活动而不是顺序执行参与

**Comment by QQ1142057049** [comment]
jd xxxx  fast

**Comment by wossQ** [comment]
> jd xxxx fast

定时任务可以直接修改吗，还是只能手动执行的时候才可以。
比如星推官的定时任务那边，是不是可以改成    0 0 * * * jd jd_xtg fast

**Comment by QQ1142057049** [comment]
这个我不懂 我是小白

**Comment by zhangleqin** [comment]
> > jd xxxx fast
> 
> 定时任务可以直接修改吗，还是只能手动执行的时候才可以。
> 比如星推官的定时任务那边，是不是可以改成 0 0 * * * jd jd_xtg fast

高并发必然导致CPU上升 可能卡住 崩溃 都有可能 你有这个信心可以手动改 屏蔽自动更新就好啦

当然 0点 所有人的脚本都启动了 能不能卡到 看你的网 和 机器了

**Comment by wossQ** [comment]
> > > jd xxxx fast
> > 
> > 
> > 定时任务可以直接修改吗，还是只能手动执行的时候才可以。
> > 比如星推官的定时任务那边，是不是可以改成 0 0 * * * jd jd_xtg fast
> 
> 高并发必然导致CPU上升 可能卡住 崩溃 都有可能 你有这个信心可以手动改 屏蔽自动更新就好啦
> 
> 当然 0点 所有人的脚本都启动了 能不能卡到 看你的网 和 机器了

我只有个别脚本需要多帐号并发，5个账号，应该是可以吧
是否直接在定时任务中修改即可？
