### ISSUE TITLE
termux不能助力

### ISSUE THREAD

**Issue by wjj982** [lan-tianxiang/JS_TOOL#159]
### 想要增加什么样的功能或者哪里存在不足之处呢？

只有配置docker才行吗？
我导出了助力码，也配置了config文件，依然是所有活动无内部助力，比如，农场工厂这些

**Comment by zhangleqin** [comment]
说实话 这些脚本的目的就是用脚本换助力

你给我脚本 我给你助力 自己10个账号来回助力的毕竟少 没必要在意这些助力的东西

**Comment by wjj982** [comment]
我挂得不少呢，远远不止10个，就想多余助力能用就自己用，浪费了
