### ISSUE TITLE
群晖 docker  BUG 反馈

### ISSUE THREAD

**Issue by a2215653** [lan-tianxiang/JS_TOOL#16]
群晖 docker  添加文件夹后脚本全部消失，更新提示连不了网

群晖 docker  添加文件夹后脚本全部消失，更新提示连不了网
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
群晖 docker  添加文件夹后脚本全部消失，更新提示连不了网

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
现在应该没这个问题了吧，当初改动比较大🤔
