### ISSUE TITLE
是否可以增加店铺批量取消关注

### ISSUE THREAD

**Issue by zhongzeqing** [lan-tianxiang/JS_TOOL#161]

**Comment by qzsun02** [comment]
有取消店铺功能的

**Comment by zhangleqin** [comment]
已这套脚本的能力 跑一周你就关注满了 有个脚本管这个
设定文件也有参数管理
/*
脚本：取关京东店铺和商品
更新时间：2021-05-08
因种豆得豆和宠汪汪以及NobyDa大佬的京东签到脚本会关注店铺和商品，故此脚本用来取消已关注的店铺和商品
默认：每运行一次脚本全部已关注的店铺与商品
建议此脚本运行时间在 种豆得豆和宠汪汪脚本运行之后 再执行
现有功能: 1、取关商品。2、取关店铺。3、匹配到boxjs输入的过滤关键词后，不再进行此商品/店铺后面(包含输入的关键词商品/店铺)的取关
脚本兼容: Quantumult X, Surge, Loon, JSBox, Node.js, 小火箭
==============Quantumult X===========
[task_local]
#取关京东店铺商品
55 23 * * * https://gitee.com/lxk0301/jd_scripts/raw/master/jd_unsubscribe.js, tag=取关京东店铺商品, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/jd.png, enabled=true
===========Loon============

**Comment by zhongzeqing** [comment]
> 已这套脚本的能力 跑一周你就关注满了 有个脚本管这个
> 设定文件也有参数管理
> /*
> 脚本：取关京东店铺和商品
> 更新时间：2021-05-08
> 因种豆得豆和宠汪汪以及NobyDa大佬的京东签到脚本会关注店铺和商品，故此脚本用来取消已关注的店铺和商品
> 默认：每运行一次脚本全部已关注的店铺与商品
> 建议此脚本运行时间在 种豆得豆和宠汪汪脚本运行之后 再执行
> 现有功能: 1、取关商品。2、取关店铺。3、匹配到boxjs输入的过滤关键词后，不再进行此商品/店铺后面(包含输入的关键词商品/店铺)的取关
> 脚本兼容: Quantumult X, Surge, Loon, JSBox, Node.js, 小火箭
> ==============Quantumult X===========
> [task_local]
> #取关京东店铺商品
> 55 23 * * * https://gitee.com/lxk0301/jd_scripts/raw/master/jd_unsubscribe.js, tag=取关京东店铺商品, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/jd.png, enabled=true
> ===========Loon============

现在是不是没有放到定时脚本里面，每天执行呀
