### ISSUE TITLE
为什么docker 版本的没有面板呢，不能网页访问有一点不是太方便，可以添加吗？还是说技术实现起来比较麻烦？

### ISSUE THREAD

**Issue by lanyucomputer** [lan-tianxiang/JS_TOOL#163]
为什么docker 版本的没有面板呢，不能网页访问有一点不是太方便，可以添加吗？还是说技术实现起来比较麻烦？

**Comment by lan-tianxiang** [comment]
docker有面板的呀

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："lanyucomputer ***@***.***&gt;;
发送时间：2021年6月18日(星期五) 晚上9:13
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 为什么docker 版本的没有面板呢，不能网页访问有一点不是太方便，可以添加吗？还是说技术实现起来比较麻烦？ (#163)
-----------------------------------

 

 
为什么docker 版本的没有面板呢，不能网页访问有一点不是太方便，可以添加吗？还是说技术实现起来比较麻烦？

**Comment by lanyucomputer** [comment]
https://registry.hub.docker.com/r/lantianxiang1/js_tool/tags?page=1&ordering=last_updated用这个的没有面板，用一键wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/docker_install_jd.sh -O docker_install_jd.sh && chmod +x docker_install_jd.sh && bash docker_install_jd.sh
可以有面板
