### ISSUE TITLE
2个定时设置页面的疑问

### ISSUE THREAD

**Issue by hdstar2009** [lan-tianxiang/JS_TOOL#164]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ x] Docker

## 3. 是否用一键脚本部署的？

- [ x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x ] No

### (1) 具体问题
A：

### (2) 详细日志
A：1、非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。这句话是否有错？前后要和不要都是jd命令？
2、# 重启挂机程序
# 33 13 * * * jd hangup  请问什么是挂机程序？

**Comment by implanb** [comment]
crazy joy的自动合成挂机脚本
