### ISSUE TITLE
第三方库无法检测到cron，为了方便能否./jd.sh update 的时候设置cron

### ISSUE THREAD

**Issue by Tsukasa007** [lan-tianxiang/JS_TOOL#166]
### 想要增加什么样的功能或者哪里存在不足之处呢？
第三方库无法检测到cron，为了方便能否./jd.sh update 的时候设置cron
执行./jd.sh update 的时候能否加个参数，比如./jd.sh update xxx(未自动添加成功提示手动添加) 

如：
检测脚本jd_xxx，但无法检测到jd_xxx  的cron 请手动编辑cron用以设置cronlist：
脚本输入

**Comment by xxp2277** [comment]
建议没有检测到脚本的定时任务的话，自动给脚本增加一个定时任务（比如默认时间6 6 * * *），大家看到这么个特殊的时间，都明白是脚本内没有时间而使用的自定义时间了吧，然后就可以手动更改了。
