### ISSUE TITLE
关于第三方库问题

### ISSUE THREAD

**Issue by Saoforest** [lan-tianxiang/JS_TOOL#167]
第三方库同步完毕后会添加与主库相同的脚本 并且配置文件内配置的环境变量无法生效 如东东超市兑换脚本 会提示相关兑换未开启

**Comment by zhangleqin** [comment]
你这题一分为二 东东超市不能玩了 脚本没用了 所以你更新谁的脚本都是未开启

有设定如果相同就删除主库的脚本用第三方的

但是做着这个功能似乎有点问题 要同步个几次才会加载好 多试试 我也过了几小时才显示正常
