### ISSUE TITLE
能否考虑添加个视觉功能，辛苦了。

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#168]
例如：
序号，活动名称，脚本名称，        执行时间，          是否完成                    启用/禁用
1         口袋书店   jd_bookshop.js   38 8,12,18 * * *    待执行（已完成）      启用（点一下能启用/禁用）......
......
辛苦了！

**Comment by xuchjian** [comment]
.......呵呵
