### ISSUE TITLE
惊喜牧场更新跟京东到家添加

### ISSUE THREAD

**Issue by ly7788110** [lan-tianxiang/JS_TOOL#169]
### 想要增加什么样的功能或者哪里存在不足之处呢？

https://github.com/colakele/jd/blob/main/jd_jxmc.js

https://github.com/passerby-b/JDDJ

**Comment by CACAVOK** [comment]
加一个QQ星牧场
https://github.com/DovFork/Wenmoux/blob/master/jd/jd_qqxing.js

**Comment by wingswing** [comment]
求更新
