### ISSUE TITLE
部分bug反馈

### ISSUE THREAD

**Issue by snakexgc** [lan-tianxiang/JS_TOOL#170]
![1FIEQ%{TI)5WL@UE)CS}N(I](https://user-images.githubusercontent.com/78722169/122642623-edeeea00-d13d-11eb-8d88-9daf74a79bce.png)
这个提示是不是有什么依赖文件更新了？

**Comment by snakexgc** [comment]
另外大佬有时间的话，麻烦加一下我QQ2577266652，我是之前说写了个教程的人，麻烦了哈！

**Comment by snakexgc** [comment]
惊喜牧场, 错误!
❗️惊喜牧场, 错误!
ReferenceError: JXUserAgent is not defined
    at getGetRequest (/home/cong/jd/scripts/jd_jxmc.js:455:3)
 ️️   at takeGetRequest (/home/cong/jd/scripts/jd_jxmc.js:282:19)
    at pasture (/home/cong/jd/scripts/jd_jxmc.js:94:11)
 ️   at /home/cong/jd/scripts/jd_jxmc.js:77:11
 ️️️️️️   at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by snakexgc** [comment]
较快运行所有脚本会导致浏览器卡死，脚本会运行一会儿，就是会卡死浏览器，觉得可以取消这个按钮

**Comment by zhangleqin** [comment]
> 较快运行所有脚本会导致浏览器卡死，脚本会运行一会儿，就是会卡死浏览器，觉得可以取消这个按钮

这个是你的设备不行 并发太高CPU崩了 有人可以 有人需要 没必要删掉吧

**Comment by snakexgc** [comment]
> > 较快运行所有脚本会导致浏览器卡死，脚本会运行一会儿，就是会卡死浏览器，觉得可以取消这个按钮
> 
> 这个是你的设备不行 并发太高CPU崩了 有人可以 有人需要 没必要删掉吧

脚本挂在云服务器上，本都只是个控制台，电脑浏览器崩了，为啥和云服务器CPU有关系？你可以试试，看浏览器会不会卡死
