### ISSUE TITLE
关于“京东手机狂欢城（jd_caenivalcity) API请求失败，请检查网路重试”问题

### ISSUE THREAD

**Issue by wys206** [lan-tianxiang/JS_TOOL#171]
京东手机狂欢城（jd_caenivalcity)日志如下，是黑号了吗？还是网络问题呀? 
昨晚用甲骨文云安装Docker的方式运行过，刚刚用手机本地运行也是如此，肿么回事呢？？？

🔔京东手机狂欢城, 开始!

====================共6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/20 上午4:30:50=====================

开始获取京东手机狂欢城配置文件

共6个京东账号

您提供了6个账号的京东手机狂欢城助力码

开始【京东账号1】jd_40e3ac938071e

开始
"getaddrinfo ENOTFOUND share.turinglabs.net"
京东手机狂欢城 API请求失败，请检查网路重试
助力情况：0/100
获取邀请码失败：{"code":1006,"data":{},"msg":"任务已结束"}
开始 【浏览热销手机产品】任务,需等待6秒
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO Neo5
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO Z3
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO 7
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO U3x
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO Neo5
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 1-F 单品区 任务 iQOO Z3
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 2-F 专柜区 任务 iQOO京东自营店，需等待10秒
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 3-F 综合区 任务 iQOO新品上市，需等待10秒
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 3-F 综合区 任务 预售榜，需等待10秒
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始浏览 3-F 综合区 任务 618手机会场，需等待10秒
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【iQOO】 任务
开始做答题任务 iQOO 7的芯片是？
doQuestion 领取答题任务奖励 结果:{"code":1006,"data":{},"msg":"任务已结束"}

开始做 品牌手机 【OPPO】 任务
开始浏览 1-F 单品区 任务 OPPO Reno6 系列6400万人像镜头5G轻薄手机
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

开始做 品牌手机 【OPPO】 任务
开始浏览 1-F 单品区 任务 OPPO Reno5
doBrowse 做brand任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
....
“省略”
....
开始做 品牌手机 【造浪计划】 任务
开始做答题任务 京东手机造浪计划是与那个极限运动IP合作的？
doQuestion 领取答题任务奖励 结果:{"code":1006,"data":{},"msg":"任务已结束"}

开始 【逛好货街，做任务】，需等待10秒
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做browseShop任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
20210619日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210618日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210617日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210616日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210615日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210614日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210613日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210612日 【京豆20个】往期京豆奖励已领取~
20210611日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210610日 【京豆20个】往期京豆奖励已领取~
20210609日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210608日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210607日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210606日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210605日 【京豆20个】往期京豆奖励已领取~
20210604日 【京豆20个】往期京豆奖励已领取~
20210603日 【京豆20个】往期京豆奖励已领取~
20210602日 【京豆20个】往期京豆奖励已领取~
20210601日 【京豆20个】往期京豆奖励已领取~
20210531日 【京豆20个】往期京豆奖励已领取~
20210530日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210529日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210528日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210527日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210526日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210525日 【无】往期京豆奖励，今日争取进入前30000名哦~
20210524日 【无】往期京豆奖励，今日争取进入前30000名哦~
开始抽奖，当前积分可抽奖0次

==============📣系统通知📣==============
京东手机狂欢城
京东账号1 jd_40e3ac938071e
邀请好友助力：0/100
当前获得积分：-
当前获得排名：-
累计获得积分：38
累计获得京豆：511🐶
具体详情点击弹窗跳转后即可查看

开始【京东账号2】还不赶快去学习

开始
"getaddrinfo ENOTFOUND share.turinglabs.net"
京东手机狂欢城 API请求失败，请检查网路重试
助力情况：0/100
获取邀请码失败：{"code":1006,"data":{},"msg":"任务已结束"}
开始 【浏览热销手机产品】任务,需等待6秒
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常
doBrowse 做hot任务:{"code":1006,"data":{},"msg":"任务已结束"}
doBrowse异常

**Comment by CACAVOK** [comment]
活动结束了

**Comment by wys206** [comment]
> 活动结束了

原来如此
