### ISSUE TITLE
主仓库能不能像第三方仓库一样增加一下分支清单？

### ISSUE THREAD

**Issue by lukemin** [lan-tianxiang/JS_TOOL#173]
JD_SCRIPTS_URL:github.com/xx.git
JD_SCRIPTS_BRANCH:main ...

**Comment by zhangleqin** [comment]
主库也没分支啊 你要什么清单 你要把主库换了？ 似乎不太行

**Comment by lukemin** [comment]
gitee的主库 https://gitee.com/highdimen/clone_scripts.git 有点老了，最新更新时间是11月前的，而https://github.com/lan-tianxiang/clone_scripts 有两个branchs，一个是sync，一个是master。默认是sync，但是真正的应该是master。

**Comment by zhangleqin** [comment]
你可以加到第三方库里啊 可以代替 可以自动定时

**Comment by zhangleqin** [comment]
@lan-tianxiang 今天看了一下主库 https://gitee.com/highdimen/clone_scripts.git 确实有点老 默认是用这个库吗 还是 只是为了导入的时候快一点， 更新的时候使用别的库 提升体验

**Comment by wys206** [comment]
我一直没看明白添加第三方库怎么弄，分支有什么作用呢？我添加了两个第三方库，都是默认，
ThirdpardRepoUrl1="https://github.com/zero205/JD_tencent_scf.git"
ThirdpardRepoUrl2="https://github.com/panghu999/jd_scripts.git"

ThirdpardRepoBranch1=""
ThirdpardRepoBranch2=""

ThirdpardRepoPath1=""
ThirdpardRepoPath2=""
这样可以吧？
看模板还是没搞懂这三个变量的意思😂。
第一个是拉去库的地址是吧，第二个分支是指拉去的库放在哪个文件夹里的意思嘛？第三个是什么意思啊，不改没事吧？还有第三方库手动运行其中一个怎么弄呀？

**Comment by Defeatable1** [comment]
> 我一直没看明白添加第三方库怎么弄，分支有什么作用呢？我添加了两个第三方库，都是默认，
> ThirdpardRepoUrl1="https://github.com/zero205/JD_tencent_scf.git"
> ThirdpardRepoUrl2="https://github.com/panghu999/jd_scripts.git"
> 
> ThirdpardRepoBranch1=""
> ThirdpardRepoBranch2=""
> 
> ThirdpardRepoPath1=""
> ThirdpardRepoPath2=""
> 这样可以吧？
> 看模板还是没搞懂这三个变量的意思😂。
> 第一个是拉去库的地址是吧，第二个分支是指拉去的库放在哪个文件夹里的意思嘛？第三个是什么意思啊，不改没事吧？还有第三方库手动运行其中一个怎么弄呀？

有什么比较好用的第三方库推荐或者交流群什么的吗，感觉好多都找不到
