### ISSUE TITLE
内部自动互助

### ISSUE THREAD

**Issue by CACAVOK** [lan-tianxiang/JS_TOOL#174]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：开启内部自动互助选项后，查看日志发现，ForOther这里助力有点问题，首先1是给自己助力，然后2，我有11个号为啥竟然Cookie1还是没助力满，发现我有两个号是空的助力码。
当我调整TempBlockCookie后，jd_fruit执行日志里可以看到只有9个账号做了任务，但是手动拉取互助码后发现还是下面这样没有把号4和号11屏蔽掉。而且不是账号靠前的优先助力吗，为啥这个不把MyFruit1优先放在ForOtherFruit2/3/4/5/6里进行助力呢。

感觉这个ForOtherFruit自动生成的有点混乱。

### (2) 详细日志
A：
# 你选择的互助码模板为：按账号编号优先。

## 东东农场：
MyFruit1='*********'
MyFruit2='*********'
MyFruit3='*********'
MyFruit4=''
MyFruit5='*********'
MyFruit6='*********'
MyFruit7='*********'
MyFruit8='*********'
MyFruit9='*********'
MyFruit10='*********'
MyFruit11=''
ForOtherFruit1="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}"
ForOtherFruit2="${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}"
ForOtherFruit3="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit4="${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}"
ForOtherFruit5="${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}"
ForOtherFruit6="${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}"
ForOtherFruit7="${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}"
ForOtherFruit8="${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit9="${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}"
ForOtherFruit10="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}"
ForOtherFruit11="${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}"

**Comment by wingswing** [comment]
应该选择模板模式为1，所有账户一致助力，优先助力cookie1

**Comment by CACAVOK** [comment]
> 应该选择模板模式为1，所有账户一致助力，优先助力cookie1

谢谢，我试了下发现并不是，而是每个账户会从下一个Cookie开始排，所以从结果来看，并没有起到作用。还是只有三个助力。
```
ForOtherFruit1="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}"
ForOtherFruit2="${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}"
ForOtherFruit3="${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}"
ForOtherFruit4="${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}"
ForOtherFruit5="${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}"
ForOtherFruit6="${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
ForOtherFruit7="${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}"
ForOtherFruit8="${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit9="${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}"
ForOtherFruit10="${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}"
ForOtherFruit11="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}"

 东东农场

【京东账号1】光阴不下
【水果名称】1.5斤大连樱桃
【已兑换水果】1次
【今日剩余助力👬】0次
【额外奖励】领取失败,原因：给您助力的人未达5个
【助力您的好友】jd_183518ndg,嗨啊哈呦嗨嗨,jd_182229ffc
【今日共浇水】12次
【剩余 水滴】100g💧
【水果进度】70.27%，已浇水1054次,还需446次
【预测】37天之后(2021-07-29日)可兑换水果

```

**Comment by wingswing** [comment]
> > 应该选择模板模式为1，所有账户一致助力，优先助力cookie1
> 
> 谢谢，我试了下发现并不是，而是每个账户会从下一个Cookie开始排，所以从结果来看，并没有起到作用。还是只有三个助力。
> 
> ```
> ForOtherFruit1="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}"
> ForOtherFruit2="${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}"
> ForOtherFruit3="${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}"
> ForOtherFruit4="${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}"
> ForOtherFruit5="${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}"
> ForOtherFruit6="${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
> ForOtherFruit7="${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}"
> ForOtherFruit8="${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
> ForOtherFruit9="${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}"
> ForOtherFruit10="${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}"
> ForOtherFruit11="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}"
> 
>  东东农场
> 
> 【京东账号1】光阴不下
> 【水果名称】1.5斤大连樱桃
> 【已兑换水果】1次
> 【今日剩余助力👬】0次
> 【额外奖励】领取失败,原因：给您助力的人未达5个
> 【助力您的好友】jd_183518ndg,嗨啊哈呦嗨嗨,jd_182229ffc
> 【今日共浇水】12次
> 【剩余 水滴】100g💧
> 【水果进度】70.27%，已浇水1054次,还需446次
> 【预测】37天之后(2021-07-29日)可兑换水果
> ```

你要优先助力cookis1用这个配置
HelpType="0"

**Comment by CACAVOK** [comment]
> > > 应该选择模板模式为1，所有账户一致助力，优先助力cookie1
> > 
> > 
> > 谢谢，我试了下发现并不是，而是每个账户会从下一个Cookie开始排，所以从结果来看，并没有起到作用。还是只有三个助力。
> > ```
> > ForOtherFruit1="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}"
> > ForOtherFruit2="${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}"
> > ForOtherFruit3="${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}"
> > ForOtherFruit4="${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}"
> > ForOtherFruit5="${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}"
> > ForOtherFruit6="${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}"
> > ForOtherFruit7="${MyFruit8}@${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}"
> > ForOtherFruit8="${MyFruit9}@${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
> > ForOtherFruit9="${MyFruit10}@${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}"
> > ForOtherFruit10="${MyFruit11}@${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}"
> > ForOtherFruit11="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}@${MyFruit8}@${MyFruit9}@${MyFruit10}"
> > 
> >  东东农场
> > 
> > 【京东账号1】光阴不下
> > 【水果名称】1.5斤大连樱桃
> > 【已兑换水果】1次
> > 【今日剩余助力👬】0次
> > 【额外奖励】领取失败,原因：给您助力的人未达5个
> > 【助力您的好友】jd_183518ndg,嗨啊哈呦嗨嗨,jd_182229ffc
> > 【今日共浇水】12次
> > 【剩余 水滴】100g💧
> > 【水果进度】70.27%，已浇水1054次,还需446次
> > 【预测】37天之后(2021-07-29日)可兑换水果
> > ```
> 
> 你要优先助力cookis1用这个配置
> HelpType="0"

还不是我理想的情况，我关了内部互助，自定义了，谢谢你的回复
