### ISSUE TITLE
京东试用显示申请商品数为0

### ISSUE THREAD

**Issue by hixuchang** [lan-tianxiang/JS_TOOL#178]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：京东试用，显示申请数为0，无法正常申请。

### (2) 详细日志
A：
开始【京东账号1】XXX

⏰ 获取 家用电器 普通试用 商品列表
⏰ 获取 家用电器 闪电试用 商品列表
⏰ 获取 手机数码 普通试用 商品列表
⏰ 获取 手机数码 闪电试用 商品列表
⏰ 获取 电脑办公 普通试用 商品列表
⏰ 获取 电脑办公 闪电试用 商品列表
⏰ 获取 家居家装 普通试用 商品列表
⏰ 获取 家居家装 闪电试用 商品列表
⏰ 过滤商品列表，当前共有2084个商品
⏰ 即将申请 0 个商品
💩 获得成功列表失败: null

==============📣系统通知📣==============
京东试用
京东账号1 XXX
🎉 本次申请：0/0个商品🛒
🎉 0个商品待领取🤩
🎉 结束原因：申请完毕

**Comment by rayho932** [comment]
关键词过滤列表最后多了一个@，手动更新以后每次都会变自动更新覆盖。。

**Comment by wingswing** [comment]
> 关键词过滤列表最后多了一个@，手动更新以后每次都会变自动更新覆盖。。

感谢 修改后能用了

**Comment by lideli2566128** [comment]
> 关键词过滤列表最后多了一个@，手动更新以后每次都会变自动更新覆盖。。

如何手动更新？我用的是手机端termux。
