### ISSUE TITLE
脚本执行工具显示错误

### ISSUE THREAD

**Issue by zdmisif** [lan-tianxiang/JS_TOOL#179]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：
Error: Command failed: cd /home/pi/jd;jd
/bin/sh: jd：未找到命令

![image](https://user-images.githubusercontent.com/8085248/122887758-caad8000-d373-11eb-9104-049ab97492ed.png)

**Comment by zhangleqin** [comment]
你要玩这个 去终端啊 

脚本执行工具 你不输入脚本名 输入命令干吗 后面温馨提示看见了吗

**Comment by zdmisif** [comment]
> 你要玩这个 去终端啊
> 
> 脚本执行工具 你不输入脚本名 输入命令干吗 后面温馨提示看见了吗

这个原本是会列出所有脚本的名称的，之前是可以的，突然就报错了，而且这个命令又不是我输入的，不懂别装懂好吗
