### ISSUE TITLE
使用docker一键安装命令后重启容器，出现启动死循环

### ISSUE THREAD

**Issue by ZJUprince** [lan-tianxiang/JS_TOOL#18]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：使用docker一键安装命令后重启VPS，jd容器出现启动死循环

### (2) 详细日志
A：确认看过WIKI，打开浏览器，地址为你的127.0.0.1:5678

控制面板启动成功，如未修改，则初始用户名和密码为：admin/adminadmin...

您的操作系统为：UnKnow 架构：x86_64
容器启动成功...

Welcome to Node.js v14.16.1.
Type ".help" for more information.
> crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory

**Comment by cq535454518** [comment]
一样的问题 ，重启就gg
![image](https://user-images.githubusercontent.com/47836815/116871715-48dc8880-ac47-11eb-94d1-1eeb9aa177ee.png)

**Comment by ZJUprince** [comment]
这有点恶性bug了

**Comment by lukemin** [comment]
最新版的还是没有修复。

**Comment by 1120247833** [comment]
今天还是有这个问题

**Comment by lan-tianxiang** [comment]
好

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："1120247833 ***@***.***&gt;;
发送时间：2021年5月25日(星期二) 中午1:49
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18)
-----------------------------------

 

 
今天还是有这个问题

**Comment by lan-tianxiang** [comment]
已修复，删除镜像后，重新部署

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："1120247833 ***@***.***&gt;;
发送时间：2021年5月25日(星期二) 中午1:49
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18)
-----------------------------------

 

 
今天还是有这个问题

**Comment by lan-tianxiang** [comment]
已修复，删除镜像后，重新部署

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："lukemin ***@***.***&gt;;
发送时间：2021年5月25日(星期二) 中午12:15
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18)
-----------------------------------

 

 
最新版的还是没有修复。

**Comment by happyskey** [comment]
> 已修复，删除镜像后，重新部署
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："lukemin ***@***.***&gt;; 发送时间：2021年5月25日(星期二) 中午12:15 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18) ----------------------------------- 最新版的还是没有修复。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

### 

> [`_****_`](

- 

- [ ] @1. url

)

> 已修复，删除镜像后，重新部署
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："1120247833 ***@***.***&gt;; 发送时间：2021年5月25日(星期二) 中午1:49 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18) ----------------------------------- 今天还是有这个问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

之前的镜像全删除了，还是不行
创建容器并运行 
2c4cf8a749f47ecf3ecb6ee99b1ada45175f5c29b38386cc2f08b8a8ef2f4f0e

下面列出所有容器 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                  PORTS                    NAMES
2c4cf8a749f4        lantianxiang1/js_tool:A1   "/bin/sh -c 'bash $J…"   1 second ago        Up Less than a second   0.0.0.0:5678->5678/tcp   jd

安装已经完成。
请访问 http://<ip>:5678 进行配置
初始用户名：admin，初始密码：adminadmin 
进入容器命令为########docker exec -it jd /bin/bash
root@ubuntu:~# docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                                  PORTS               NAMES
2c4cf8a749f4        lantianxiang1/js_tool:A1   "/bin/sh -c 'bash $J…"   8 seconds ago       Restarting (1) Less than a second ago                       jd
root@ubuntu:~# docker logs 2c4cf8a749f4
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[8]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory
crond[7]: crond (busybox 1.31.1) started, log level 8
cp: cannot stat '/sample/config.sh.sample': No such file or directory

**Comment by lan-tianxiang** [comment]
> > 已修复，删除镜像后，重新部署
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："lukemin _**@**_._**>; 发送时间：2021年5月25日(星期二) 中午12:15 收件人："lan-tianxiang/JS_TOOL" _**@**_.**_>; 抄送："Subscribed _**@**_.***>; 主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18) ----------------------------------- 最新版的还是没有修复。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > [`_****_`](
> 
> * [ ]  @1. url
> 
> )
> 
> > 已修复，删除镜像后，重新部署
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："1120247833 _**@**_._**>; 发送时间：2021年5月25日(星期二) 中午1:49 收件人："lan-tianxiang/JS_TOOL" _**@**_.**_>; 抄送："Subscribed _**@**_.***>; 主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18) ----------------------------------- 今天还是有这个问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 之前的镜像全删除了，还是不行
> 创建容器并运行
> 2c4cf8a749f47ecf3ecb6ee99b1ada45175f5c29b38386cc2f08b8a8ef2f4f0e
> 
> 下面列出所有容器
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 2c4cf8a749f4 lantianxiang1/js_tool:A1 "/bin/sh -c 'bash $J…" 1 second ago Up Less than a second 0.0.0.0:5678->5678/tcp jd
> 
> 安装已经完成。
> 请访问 http://:5678 进行配置
> 初始用户名：admin，初始密码：adminadmin
> 进入容器命令为########docker exec -it jd /bin/bash
> root@ubuntu:~# docker ps -a CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 2c4cf8a749f4 lantianxiang1/js_tool:A1 "/bin/sh -c 'bash $J…" 8 seconds ago Restarting (1) Less than a second ago jd root@ubuntu:~# docker logs 2c4cf8a749f4
> crond[8]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[8]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory
> crond[7]: crond (busybox 1.31.1) started, log level 8
> cp: cannot stat '/sample/config.sh.sample': No such file or directory


可能是docker镜像站更新的慢，真的修复了呢😣

**Comment by happyskey** [comment]
可以了，感谢开发者

**Comment by lan-tianxiang** [comment]
哈哈

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："happyskey ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨0:14
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 使用docker一键安装命令后重启容器，出现启动死循环 (#18)
-----------------------------------

 

 
可以了，感谢开发者

**Comment by 1120247833** [comment]
非常感谢！已经可以正常运行

**Comment by ZJUprince** [comment]
感谢作者
