### ISSUE TITLE
可以添加卸载项目的教程嘛

### ISSUE THREAD

**Issue by Hiddenl** [lan-tianxiang/JS_TOOL#182]
### 想要增加什么样的功能或者哪里存在不足之处呢？
可以添加卸载项目的教程嘛
我看安装教程很详细了
但没有卸载的！！！

**Comment by zhangleqin** [comment]
linux有啥卸不卸载 文件夹删了就好啦 定时的也删了 你还想要一键卸载？？？

**Comment by 13636308814** [comment]
docker stop 容器名称
docker rm 容器名称
rm -rf 目录
