### ISSUE TITLE
惊喜牧场报错问题

### ISSUE THREAD

**Issue by zdmisif** [lan-tianxiang/JS_TOOL#187]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

❗️惊喜牧场, 错误!
TypeError: Cannot read property 'push' of undefined
    at pasture (/home/pi/jd/scripts/jd_jxmc.js:104:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/pi/jd/scripts/jd_jxmc.js:77:5

**Comment by yyx2684264** [comment]
我的也有报错，不过报错的内容和你不一样
运行环境是群晖的Docker
错误是这样的：
ReferenceError: JXUserAgent is not defined
    at getGetRequest (/root/jd/scripts/jd_jxmc.js:455:3)
    at takeGetRequest (/root/jd/scripts/jd_jxmc.js:282:19)
    at pasture (/root/jd/scripts/jd_jxmc.js:94:11)
    at /root/jd/scripts/jd_jxmc.js:77:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by zdmisif** [comment]
> 我的也有报错，不过报错的内容和你不一样
> 运行环境是群晖的Docker
> 错误是这样的：
> ReferenceError: JXUserAgent is not defined
> at getGetRequest (/root/jd/scripts/jd_jxmc.js:455:3)
> at takeGetRequest (/root/jd/scripts/jd_jxmc.js:282:19)
> at pasture (/root/jd/scripts/jd_jxmc.js:94:11)
> at /root/jd/scripts/jd_jxmc.js:77:11
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
这个有两个地方会报错的，注释掉就可以运行了
![image](https://user-images.githubusercontent.com/8085248/123216904-9a451d80-d4fc-11eb-88e8-6baff58bb1a5.png)
![image](https://user-images.githubusercontent.com/8085248/123216960-a7faa300-d4fc-11eb-8b98-6e2b2e3c6dd1.png)

**Comment by yyx2684264** [comment]
> > 我的也有报错，不过报错的内容和你不一样
> > 运行环境是群晖的Docker
> > 错误是这样的：
> > ReferenceError: JXUserAgent is not defined
> > at getGetRequest (/root/jd/scripts/jd_jxmc.js:455:3)
> > at takeGetRequest (/root/jd/scripts/jd_jxmc.js:282:19)
> > at pasture (/root/jd/scripts/jd_jxmc.js:94:11)
> > at /root/jd/scripts/jd_jxmc.js:77:11
> > at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > 这个有两个地方会报错的，注释掉就可以运行了
> > ![image](https://user-images.githubusercontent.com/8085248/123216904-9a451d80-d4fc-11eb-88e8-6baff58bb1a5.png)
> > ![image](https://user-images.githubusercontent.com/8085248/123216960-a7faa300-d4fc-11eb-8b98-6e2b2e3c6dd1.png)

好的，谢谢，修改后问题解决了

**Comment by wys206** [comment]
@lan-tianxiang  大佬，抽空把库里的这个也修改一下呗，【比心】

**Comment by benkyocn** [comment]
> > 我的也有报错，不过报错的内容和你不一样
> > 运行环境是群晖的Docker
> > 错误是这样的：
> > ReferenceError: JXUserAgent is not defined
> > at getGetRequest (/root/jd/scripts/jd_jxmc.js:455:3)
> > at takeGetRequest (/root/jd/scripts/jd_jxmc.js:282:19)
> > at pasture (/root/jd/scripts/jd_jxmc.js:94:11)
> > at /root/jd/scripts/jd_jxmc.js:77:11
> > at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > 这个有两个地方会报错的，注释掉就可以运行了
> > ![image](https://user-images.githubusercontent.com/8085248/123216904-9a451d80-d4fc-11eb-88e8-6baff58bb1a5.png)
> > ![image](https://user-images.githubusercontent.com/8085248/123216960-a7faa300-d4fc-11eb-8b98-6e2b2e3c6dd1.png)

大佬，割草显示401 Authorization Required 怎么办

**Comment by lan-tianxiang** [comment]
好的，感谢指出

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："benkyo ***@***.***&gt;;
发送时间：2021年6月24日(星期四) 晚上8:01
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 惊喜牧场报错问题 (#187)
-----------------------------------

 

   
我的也有报错，不过报错的内容和你不一样
 运行环境是群晖的Docker
 错误是这样的：
 ReferenceError: JXUserAgent is not defined
 at getGetRequest (/root/jd/scripts/jd_jxmc.js:455:3)
 at takeGetRequest (/root/jd/scripts/jd_jxmc.js:282:19)
 at pasture (/root/jd/scripts/jd_jxmc.js:94:11)
 at /root/jd/scripts/jd_jxmc.js:77:11
 at processTicksAndRejections (internal/process/task_queues.js:95:5)
 这个有两个地方会报错的，注释掉就可以运行了
 
 
   
大佬，割草显示401 Authorization Required 怎么办
