### ISSUE TITLE
关于jd_ddo_pk失效问题

### ISSUE THREAD

**Issue by wys206** [lan-tianxiang/JS_TOOL#189]
大佬，能不能更新一下库里“jd_ddo_pk.js”的脚本，现在的已经失效了，我看这个链接里的能用，大佬抽空更新下！
https://github.com/zero205/JD_tencent_scf/blob/main/jd_ddo_pk.js

**Comment by lan-tianxiang** [comment]
好的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："wys206 ***@***.***&gt;;
发送时间：2021年6月24日(星期四) 晚上7:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 关于jd_ddo_pk失效问题 (#189)
-----------------------------------

 

 
大佬，能不能更新一下库里“jd_ddo_pk.js”的脚本，现在的已经失效了，我看这个链接里的能用，大佬抽空更新下！
 https://github.com/zero205/JD_tencent_scf/blob/main/jd_ddo_pk.js

**Comment by lan-tianxiang** [comment]
更新了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："wys206 ***@***.***&gt;;
发送时间：2021年6月24日(星期四) 晚上7:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 关于jd_ddo_pk失效问题 (#189)
-----------------------------------

 

 
大佬，能不能更新一下库里“jd_ddo_pk.js”的脚本，现在的已经失效了，我看这个链接里的能用，大佬抽空更新下！
 https://github.com/zero205/JD_tencent_scf/blob/main/jd_ddo_pk.js

**Comment by wys206** [comment]
> 更新了
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："wys206 ***@***.***&gt;; 发送时间：2021年6月24日(星期四) 晚上7:56 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] 关于jd_ddo_pk失效问题 (#189) ----------------------------------- 大佬，能不能更新一下库里“jd_ddo_pk.js”的脚本，现在的已经失效了，我看这个链接里的能用，大佬抽空更新下！ https://github.com/zero205/JD_tencent_scf/blob/main/jd_ddo_pk.js — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

辛苦辛苦！！

**Comment by linyali888** [comment]
又坏了，原作者好像不更新了
