### ISSUE TITLE
扫码获取 cookie 显示失效

### ISSUE THREAD

**Issue by ZhoucpSAMA** [lan-tianxiang/JS_TOOL#191]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lideli2566128** [comment]
同样的情况

**Comment by EvanZhou666** [comment]
我今天早上也遇到了这种情况

**Comment by iamadao** [comment]
一样的问题

**Comment by lhjhbufo** [comment]
同样的问题。测试了下iphone扫码无法获取cookie,报请升级到最新版本。安卓测试没有问题，可以获取cookie。

**Comment by lukemin** [comment]
扫码获取ck目前仅仅支持扫码设备与获取二维码设备同ip下才能成功获取否则提示失效

**Comment by lan-tianxiang** [comment]
@lukemin  好，我试试看

**Comment by lukemin** [comment]
> @lukemin 好，我试试看

大佬，能顺带看一下 https://github.com/lan-tianxiang/JS_TOOL/issues/181 问题吗？

**Comment by happyskey** [comment]
我也遇到了

**Comment by lhjhbufo** [comment]
确实要同一局域网内才行，手机用4G扫不出来，尴尬了。

**Comment by aburdchen415** [comment]
生成码机器和扫码的手机必须同一个ip

**Comment by timessage** [comment]
我用的内网穿透开的热点，两部设备是同一个ip，但是还是不行

**Comment by Rosylusi** [comment]
同样遇到该问题，不知道现是否有解决方案

**Comment by Rosylusi** [comment]
> 扫码获取ck目前仅仅支持扫码设备与获取二维码设备同ip下才能成功获取否则提示失效

这是bug还是修改过了

**Comment by coppea** [comment]
能否有那种本地运行的cooie获取二维码

**Comment by FKDXD** [comment]
我现在也获取不了了

**Comment by ywxc** [comment]
抓取了一些可以扫码的 他们是用口令获取cookie

抓的包就是这个 生成口令 



 "err": 0,
 "qrcode": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
 "jdCode": "26.0复制整段话 http://JDmOcT1Ep3ScjH【口令登录】点击->立即查看去登录%q0JUjBmqZb!咑開猄倲",
 "user": {
  "s_token": "gavmjihi",
  "cookies": "okl_token=vnzhiqla;guid=ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650; lang=chs; lsid=68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re; lstoken=gavmjihi;",
  "qrCodeUrl": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
  "lstoken": "gavmjihi",
  "lsid": "68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re",
  "guid": "ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650",
  "okl_token": "vnzhiqla",
  "token": "m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh"
 }

**Comment by Rosylusi** [comment]
> 抓取了一些可以扫码的 他们是用口令获取cookie
> 
> 抓的包就是这个 生成口令
> 
> "err": 0,
> "qrcode": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
> "jdCode": "26.0复制整段话 [http://JDmOcT1Ep3ScjH【口令登录】点击->立即查看去登录%q0JUjBmqZb!咑開猄倲](http://JDmOcT1Ep3ScjH%E3%80%90%E5%8F%A3%E4%BB%A4%E7%99%BB%E5%BD%95%E3%80%91%E7%82%B9%E5%87%BB-%3E%E7%AB%8B%E5%8D%B3%E6%9F%A5%E7%9C%8B%E5%8E%BB%E7%99%BB%E5%BD%95%q0JUjBmqZb!%E5%92%91%E9%96%8B%E7%8C%84%E5%80%B2)",
> "user": {
> "s_token": "gavmjihi",
> "cookies": "okl_token=vnzhiqla;guid=ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650; lang=chs; lsid=68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re; lstoken=gavmjihi;",
> "qrCodeUrl": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
> "lstoken": "gavmjihi",
> "lsid": "68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re",
> "guid": "ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650",
> "okl_token": "vnzhiqla",
> "token": "m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh"
> }

所以如果我们要利用的话应该怎么使用？

**Comment by coppea** [comment]
> > 抓取了一些可以扫码的 他们是用口令获取cookie
> > 抓的包就是这个 生成口令
> > "err": 0,
> > "qrcode": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
> > "jdCode": "26.0复制整段话 [http://JDmOcT1Ep3ScjH【口令登录】点击->立即查看去登录%q0JUjBmqZb!咑開猄倲](http://JDmOcT1Ep3ScjH%E3%80%90%E5%8F%A3%E4%BB%A4%E7%99%BB%E5%BD%95%E3%80%91%E7%82%B9%E5%87%BB-%3E%E7%AB%8B%E5%8D%B3%E6%9F%A5%E7%9C%8B%E5%8E%BB%E7%99%BB%E5%BD%95%q0JUjBmqZb!%E5%92%91%E9%96%8B%E7%8C%84%E5%80%B2)",
> > "user": {
> > "s_token": "gavmjihi",
> > "cookies": "okl_token=vnzhiqla;guid=ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650; lang=chs; lsid=68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re; lstoken=gavmjihi;",
> > "qrCodeUrl": "https://plogin.m.jd.com/cgi-bin/m/tmauth?appid=300&client_type=m&token=m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh",
> > "lstoken": "gavmjihi",
> > "lsid": "68oopbnwp0au4br4xb0w9538417wz0x69muyxiumi4gng8re",
> > "guid": "ba0ce0f1ec46dacf9de1c34b728430d05baf16eceabdd8ba5ca4f85b10bcb650",
> > "okl_token": "vnzhiqla",
> > "token": "m_tokenAAEAIEgnW4JzYDgcuCPe9siMRg0T-VhKZn6lZ4lLByyDacwh"
> > }
> 
> 所以如果我们要利用的话应该怎么使用？

同局域网的才可以扫码，怎样才能让他本地运行？

**Comment by timessage** [comment]
自己抓ck就可以了，问题结束

**Comment by happy-peter** [comment]
> 自己抓ck就可以了，问题结束

请问你是怎么抓的
我chrome用好几个插件也抓不到ck啊，条件是：异地IP情况下iPhone扫码登录成功，但是获取不到pt_key

**Comment by timessage** [comment]
> > 自己抓ck就可以了，问题结束
> 
> 请问你是怎么抓的
> 我chrome用好几个插件也抓不到ck啊，条件是：异地IP情况下iPhone扫码登录成功，但是获取不到pt_key

手机端用alook浏览器工具箱里的开发者工具，直接提取cookie

**Comment by qiangwushuang** [comment]
> > 自己抓ck就可以了，问题结束
> 
> 请问你是怎么抓的
> 我chrome用好几个插件也抓不到ck啊，条件是：异地IP情况下iPhone扫码登录成功，但是获取不到pt_key

chrome 触屏版设备仿真登录，网络->搜索->输入pt_key，就可以搜索到了。

**Comment by 895450603** [comment]
> > 自己抓ck就可以了，问题结束
> 
> 请问你是怎么抓的
> 我chrome用好几个插件也抓不到ck啊，条件是：异地IP情况下iPhone扫码登录成功，但是获取不到pt_key

登陆成功了干嘛还要获取
