### ISSUE TITLE
安装完成后，在“手动执行”中的“列出活动脚本”出现的问题

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#197]
Ubuntu 20.04 LTS的版本，安装过程顺利，启用了控制面板，但出现了点问题。在“手动执行”中的“列出活动脚本”中出现错误提示
Error: Command failed: cd /home/ubuntu/jd;jd update
/bin/sh: 1: jd: not found
重启了服务器和控制面板以及 hangup，也不行，还是这个错误！

**Comment by zdmisif** [comment]
你可以看一下是否没有用root权限进行启动，用root权限启动试试
我之前也是这个问题，用root权限启动之后就没问题了
