### ISSUE TITLE
您的第1个账号：jd_xxxxxxxxxxxx 未经授权

### ISSUE THREAD

**Issue by lywly** [lan-tianxiang/JS_TOOL#2]
没问题了

**Comment by lywly** [comment]
额  直接往下找教程了。。。没看到新机制

**Comment by lan-tianxiang** [comment]
加群授权

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："李宜文 ***@***.***&gt;;
发送时间：2021年4月12日(星期一) 上午9:58
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 您的第1个账号：jd_xxxxxxxxxxxx 未经授权 (#2)
-----------------------------------

 

 
额  直接往下找教程了。。。没看到新机制
