### ISSUE TITLE
老哥求救 在配置时出现问题

### ISSUE THREAD

**Issue by tesengiii** [lan-tianxiang/JS_TOOL#20]
![image](https://user-images.githubusercontent.com/58262656/117761968-d8db8d00-b25a-11eb-8cb7-aebd2fcefc7d.png)
![image](https://user-images.githubusercontent.com/58262656/117761990-e264f500-b25a-11eb-8e6d-a6d23d6edbd0.png)

请问这个怎么解决 重装系统很多次 换了网络也是这个样子 在管理员窗口执行也会这样

**Comment by lan-tianxiang** [comment]
可能是之前怕出现某个bug，注释了一段代码，不过已经修复啦😘

**Comment by biewenwoshishui021** [comment]
很高兴群主大人再次更新，我挺喜欢用A1的，但有个问题困扰着我。我添加了几个第三方链接，然后每次jd update，都下方信息

更新/data/data/com.termux/files/home/JS_TOOL/scripts成功...

--------------------------------------------------------------

开始下载：https://gitee.com/lxrcbw/my_scripts/raw/master/jd_try.js

保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try.js

下载 jd_try.js 成功...

开始下载：https://gitee.com/lxrcbw/my_scripts/raw/master/jd_try-v2.js

保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try-v2.js

下载 jd_try-v2.js 成功...

开始下载：https://gitee.com/lxrcbw/longzhuzhu/raw/master/qx/jd_half_redrain.js

保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_half_redrain.js

下载 jd_half_redrain.js 成功...

开始下载：https://gitee.com/lxrcbw/longzhuzhu/raw/master/qx/jd_super_redrain.js

保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_super_redrain.js

下载 jd_super_redrain.js 成功...

检测到有新的定时任务：

/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_half_redrain.js
/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_super_redrain.js
/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try.js

开始尝试自动添加 thirdpard 脚本的定时任务...

成功添加新的定时任务...


但为何进crontab.list，还是原来自带的那些定时任务，第三方新的定时任务哪里能看到写入成功了呢？？


谢谢！！

**Comment by biewenwoshishui021** [comment]
另外，在crontab.list文件里，这么描述的

# jd任务区域，运行jd_scripts脚本，仅列出长期任务作初始化用，AutoAddCron=true时，将自动添加短期任务。
# 请保留任务名称中的前缀"jd_"，去掉后缀".js"，如果有些任务你不想运行，注释掉就好了，不要删除。
# 非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。

非lxk的，到底是使用jd命令，还是不要使用京东命令？没看懂。因为主要想运行longzhuzhu的红包雨和try两个第三方脚本，不知道到底怎么才能定时运行成功，所以占了人家的楼，回复咨询一下，谢谢

**Comment by tesengiii** [comment]
> 可能是之前怕出现某个bug，注释了一段代码，不过已经修复啦😘

![image](https://user-images.githubusercontent.com/58262656/119717379-cedf9e00-be98-11eb-94d1-c254b664adf4.png)
老哥还是不行哦

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/119717561-08180e00-be99-11eb-81bc-5bc45dbdcfda.png)
文件ye也没有获取完全吧

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/119718046-adcb7d00-be99-11eb-947e-4c15eb28818a.png)

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/119718590-54178280-be9a-11eb-9e2b-85875497edf0.png)
老哥解决下看下什么问题哈

**Comment by lan-tianxiang** [comment]
这样啊。我帮你标注一下，应该是定时数据没采集到，我看看今天能不能解决

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："biewenwoshishui021 ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨0:48
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

 
很高兴群主大人再次更新，我挺喜欢用A1的，但有个问题困扰着我。我添加了几个第三方链接，然后每次jd update，都下方信息
 
更新/data/data/com.termux/files/home/JS_TOOL/scripts成功...
 
 
开始下载：https://gitee.com/lxrcbw/my_scripts/raw/master/jd_try.js
 
保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try.js
 
下载 jd_try.js 成功...
 
开始下载：https://gitee.com/lxrcbw/my_scripts/raw/master/jd_try-v2.js
 
保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try-v2.js
 
下载 jd_try-v2.js 成功...
 
开始下载：https://gitee.com/lxrcbw/longzhuzhu/raw/master/qx/jd_half_redrain.js
 
保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_half_redrain.js
 
下载 jd_half_redrain.js 成功...
 
开始下载：https://gitee.com/lxrcbw/longzhuzhu/raw/master/qx/jd_super_redrain.js
 
保存路径：/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_super_redrain.js
 
下载 jd_super_redrain.js 成功...
 
检测到有新的定时任务：
 
/data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_half_redrain.js
 /data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_super_redrain.js
 /data/data/com.termux/files/home/JS_TOOL/thirdpard/raw/jd_try.js
 
开始尝试自动添加 thirdpard 脚本的定时任务...
 
成功添加新的定时任务...
 
但为何进crontab.list，还是原来自带的那些定时任务，第三方新的定时任务哪里能看到写入成功了呢？？
 
谢谢！！

**Comment by lan-tianxiang** [comment]
我的天，好像是我表述有问题。应该是，非lxk的脚本，不要命名为jd_开头

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："biewenwoshishui021 ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨0:51
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

 
另外，在crontab.list文件里，这么描述的
 
jd任务区域，运行jd_scripts脚本，仅列出长期任务作初始化用，AutoAddCron=true时，将自动添加短期任务。
 
请保留任务名称中的前缀"jd_"，去掉后缀".js"，如果有些任务你不想运行，注释掉就好了，不要删除。
 
非lxk0301/jd_scripts仓库中的脚本请使用jd命令，不要使用jd命令。请在最后保留一个空行。
 
非lxk的，到底是使用jd命令，还是不要使用京东命令？没看懂。因为主要想运行longzhuzhu的红包雨和try两个第三方脚本，不知道到底怎么才能定时运行成功，所以占了人家的楼，回复咨询一下，谢谢

**Comment by lan-tianxiang** [comment]
好，看到了，安装方式用的什么呢

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tesengiii ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨3:08
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

  
可能是之前怕出现某个bug，注释了一段代码，不过已经修复啦
  

 老哥还是不行哦

**Comment by lan-tianxiang** [comment]
是完整的呢，小兄弟，你在那个文件夹下输入命令，bash jd.sh就会有帮助的哦

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tesengiii ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨3:10
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

 

 文件ye也没有获取完全吧

**Comment by lan-tianxiang** [comment]
我再看看

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tesengiii ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨3:15
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

**Comment by tesengiii** [comment]
> 好，看到了，安装方式用的什么呢
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tesengiii ***@***.***&gt;; 发送时间：2021年5月27日(星期四) 凌晨3:08 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20) ----------------------------------- 可能是之前怕出现某个bug，注释了一段代码，不过已经修复啦 老哥还是不行哦 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我没懂 什么安装当时啊   我用的是虚拟机

**Comment by tesengiii** [comment]
> 是完整的呢，小兄弟，你在那个文件夹下输入命令，bash jd.sh就会有帮助的哦
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tesengiii ***@***.***&gt;; 发送时间：2021年5月27日(星期四) 凌晨3:10 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20) ----------------------------------- 文件ye也没有获取完全吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

之前不是有 一键运行的命令的吗

**Comment by lan-tianxiang** [comment]
运行命令换了，那个是v3版的命令。bash js.sh有提示。前面看到图片了，那尝试一下把这个文件夹删了，在home底下再运行一次一键安装脚本吧。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tesengiii ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 凌晨3:19
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

 

 老哥解决下看下什么问题哈

**Comment by tesengiii** [comment]
> 运行命令换了，那个是v3版的命令。bash js.sh有提示。前面看到图片了，那尝试一下把这个文件夹删了，在home底下再运行一次一键安装脚本吧。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tesengiii ***@***.***&gt;; 发送时间：2021年5月27日(星期四) 凌晨3:19 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20) ----------------------------------- 老哥解决下看下什么问题哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 等我回去试试

**Comment by tesengiii** [comment]
> 运行命令换了，那个是v3版的命令。bash js.sh有提示。前面看到图片了，那尝试一下把这个文件夹删了，在home底下再运行一次一键安装脚本吧。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："tesengiii ***@***.***&gt;; 发送时间：2021年5月27日(星期四) 凌晨3:19 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20) ----------------------------------- 老哥解决下看下什么问题哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么进去home底层  开命令行不是就在 HOME\用户名的吗

**Comment by tesengiii** [comment]
解决了 感谢老哥~！

**Comment by lan-tianxiang** [comment]
没事儿的，不用谢

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tesengiii ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 下午2:05
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 老哥求救 在配置时出现问题 (#20)
-----------------------------------

 

 
解决了 感谢老哥~！
