### ISSUE TITLE
扫码解决方案

### ISSUE THREAD

**Issue by dreamfly32** [lan-tianxiang/JS_TOOL#202]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

把代码中的ua换成jdapp开头的ua即可。麻烦作者修复下，我改了，定时更新给覆盖掉了

**Comment by coderykw** [comment]
求具体代码

**Comment by zdmisif** [comment]
求具体代码+1

**Comment by sallyciel** [comment]
jdapp的ua也不行吧？我这边测试了，异地就GG

**Comment by Sherlockouo** [comment]
换哪部分的那个ua?

**Comment by bj-wangxiaoxiao** [comment]
不会的推荐直接上m.jd.com拿。会的可以自己修改docker里面getJDCookie.js文件中ua，然后手动执行一下，不过比较麻烦的就是老是会被覆盖，等待大佬合并requests

**Comment by Sherlockouo** [comment]
> 不会的推荐直接上m.jd.com拿。会的可以自己修改docker里面getJDCookie.js文件中ua，然后手动执行一下，不过比较麻烦的就是老是会被覆盖，等待大佬合并requests

你好修改user-agent? 改成什么?

**Comment by dalant2019** [comment]
同等大佬修复~~

**Comment by Sherlockouo** [comment]
talk is cheap show me the code

**Comment by lan-tianxiang** [comment]
已经修复，感谢！
