### ISSUE TITLE
紧急严重BUG。

### ISSUE THREAD

**Issue by ly7788110** [lan-tianxiang/JS_TOOL#205]
服务器IP:端口/shell 可以直接打开终端。例：http://127.0.0.1:8080/shell  可以直接曝光所有CK

**Comment by ly7788110** [comment]
大家最好是，赶紧去停止外网访问

**Comment by missorforget** [comment]
修改 IsWebShell="false" ,重启

**Comment by MrH723** [comment]
是的。我刚才测试了一下。关闭webshell功能。不登录的情况下 依旧可以直接 root登陆shell。。吓得我赶紧关闭端口映射。
再次提醒关闭免密支付。

**Comment by missorforget** [comment]
记得重启

**Comment by Mr-Liu1996** [comment]
如何关闭

**Comment by missorforget** [comment]
> 如何关闭
修改配置 IsWebShell="false" ,重启

**Comment by MrH723** [comment]
重启很重要。重启了shell就不能进了。端口映射和免密关了更保险。

**Comment by ycvk** [comment]
关闭shell然后重启即可

**Comment by ymcoming** [comment]
网上流传黑客有10万条京东cookie

京东cookie泄漏危害：

轻者：拿cookie助力。
重者：用你的账户下单，花你的红包，小额支付(300以内，下单后可删除订单和收货地址）。
再不济拿收货地址和订单记录打包成压缩包一条0.3-3元不等拿去卖也是可以的。
其他危害：自己想

**Comment by rayho932** [comment]
访问ip:9999。直接可以取到shell，建议把ttyd屏蔽掉。

**Comment by wingswing** [comment]
docker是不是不受影响？

**Comment by lan-tianxiang** [comment]
@ly7788110 @missorforget  @Mr-Liu1996 @MrH723  @ycvk  @ymcoming  @rayho932  @wingswing   127.0.0.1和localhost是回送地址，可以先了解一下什么是内网。想通过外部网络访问需满足：①服务器供应商防火墙端口打开  ② 系统防火墙配置中，对应端口打开 ③ 对应端口开放且直接暴露 

对应的，第一，开放了阿里云或者腾讯云的对应端口吗？  9999根本不需要开放（云服务器从根本上已经杜绝了）。  第二，同理（系统层面）。  第三，如果是docker用户，端口都没有映射，无法访问（软件层面）。直接部署的用户的确可以本机访问ip:9999

以上条件必须同时满足，不然外部访问，感谢提问。

**Comment by lukemin** [comment]
> @ly7788110 @missorforget @Mr-Liu1996 @MrH723 @ycvk @ymcoming @rayho932 @wingswing 127.0.0.1和localhost是回送地址，可以先了解一下什么是内网。想通过外部网络访问需满足：①服务器供应商防火墙端口打开 ② 系统防火墙配置中，对应端口打开 ③ 对应端口开放且直接暴露
> 
> 对应的，第一，开放了阿里云或者腾讯云的对应端口吗？ 9999根本不需要开放（云服务器从根本上已经杜绝了）。 第二，同理（系统层面）。 第三，如果是docker用户，端口都没有映射，无法访问（软件层面）。直接部署的用户的确可以本机访问ip:9999
> 
> 以上条件必须同时满足，不然外部访问，感谢提问。

如果把脚本布置到vps上，http://服务器ip:5678/shell，可以直接在webshell运行，相关命令，而不需要登录。

**Comment by ymcoming** [comment]
对啊，问题就在于如果VPS部署了它，可以 http://公网IP：port/shell就能登录。按理说应该是先认证用户名和密码才行。这个BUG今天还是存在。

**Comment by MrH723** [comment]
> > @ly7788110 @missorforget @Mr-Liu1996 @MrH723 @ycvk @ymcoming @rayho932 @wingswing 127.0.0.1和localhost是回送地址，可以先了解一下什么是内网。想通过外部网络访问需满足：①服务器供应商防火墙端口打开 ② 系统防火墙配置中，对应端口打开 ③ 对应端口开放且直接暴露
> > 对应的，第一，开放了阿里云或者腾讯云的对应端口吗？ 9999根本不需要开放（云服务器从根本上已经杜绝了）。 第二，同理（系统层面）。 第三，如果是docker用户，端口都没有映射，无法访问（软件层面）。直接部署的用户的确可以本机访问ip:9999
> > 以上条件必须同时满足，不然外部访问，感谢提问。
> 
> 如果把脚本布置到vps上，[http://服务器ip:5678/shell，可以直接在webshell运行，相关命令，而不需要登录。](http://%E6%9C%8D%E5%8A%A1%E5%99%A8ip:5678/shell%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E5%9C%A8webshell%E8%BF%90%E8%A1%8C%EF%BC%8C%E7%9B%B8%E5%85%B3%E5%91%BD%E4%BB%A4%EF%BC%8C%E8%80%8C%E4%B8%8D%E9%9C%80%E8%A6%81%E7%99%BB%E5%BD%95%E3%80%82)

正是如此。webshell还是root用户登录。拿CK。然后rm走人。

**Comment by azhuge233** [comment]
几个月前就有这个问题了，QQ群反映过，后来只是默认关闭了 Web Shell，再后来因为不太爱在群里说话被踢了

**Comment by lan-tianxiang** [comment]
@ymcoming @MrH723 已做修复，感谢各位宝贵的建议。谢谢❤

**Comment by lan-tianxiang** [comment]
@azhuge233 近期比较忙，没时间管理群，带来不便说一声抱歉

**Comment by ly7788110** [comment]
@lan-tianxiang  正好把，扫码登录修复一下，解决办法，更换手机UI，如：（jdapp;android;10.0.5;11;0393465333165363-5333430323261366;network/wifi;model/M2102K1C;osVer/30;appBuild/88681;partner/lc001;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; M2102K1C Build/RKQ1.201112.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045534 Mobile Safari/537.36'）

**Comment by lan-tianxiang** [comment]
扫码问题，今早已修复

--------------原始邮件--------------
发件人："ly7788110 ***@***.***&gt;;
发送时间：2021年7月1日(星期四) 下午4:25
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 紧急严重BUG。 (#205)
-----------------------------------

 

 
@lan-tianxiang  正好把，扫码登录修复一下，解决办法，更换手机UI，如：（jdapp;android;10.0.5;11;0393465333165363-5333430323261366;network/wifi;model/M2102K1C;osVer/30;appBuild/88681;partner/lc001;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 11; M2102K1C Build/RKQ1.201112.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045534 Mobile Safari/537.36'）

**Comment by dalant2019** [comment]
感谢大佬的维护工作，祝你和家人身体健康
