### ISSUE TITLE
删除jd文件，但crontab中的定时任务仍会保留

### ISSUE THREAD

**Issue by ChellyL** [lan-tianxiang/JS_TOOL#206]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：
我之前使用debian的脚本安装，后来改用docker版，发现删除jd文件夹后，定时任务里的内容仍然保留

### (2) 详细日志
A：
无

**Comment by lan-tianxiang** [comment]
定时任务的确还会存在（不过不会运行，因为文件已经被删除了），我做一下改进，感谢提出！
