### ISSUE TITLE
严重问题！！！！

### ISSUE THREAD

**Issue by lrz0212** [lan-tianxiang/JS_TOOL#208]
大家有没有遇见过自己的ck被泄露了。
【京东金融】用户您好，您的支付密码连续多次输入错误，支付密码已被锁定，两小时后解锁。如非本人操作，请立即致电95118[白条]

**Comment by lrz0212** [comment]
还有一个充值Q币的订单取消通知

**Comment by shanhai2333** [comment]
我在本地环境，还好，青龙昨天修复了，大佬这边还没修

**Comment by lan-tianxiang** [comment]
暂时没有碰到，刚刚已经修复了潜在的安全漏洞了

**Comment by lrz0212** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lan-tianxiang/JS_TOOL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lan-tianxiang/JS_TOOL] 严重问题！！！！ (#208)





 
暂时没有碰到，刚刚已经修复了潜在的安全漏洞了
