### ISSUE TITLE
怎么添加 js 文件脚本

### ISSUE THREAD

**Issue by QQ1142057049** [lan-tianxiang/JS_TOOL#209]
![image](https://user-images.githubusercontent.com/67356618/124093298-4e5d2000-da8a-11eb-8bdf-5b54dff5402f.png)
如题 像这样的 怎么添加到脚本里面  求教。。

**Comment by lan-tianxiang** [comment]
增加raw脚本，然后添加定时就可以了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："QQ1142057049 ***@***.***&gt;;
发送时间：2021年7月1日(星期四) 下午4:35
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 怎么添加 js 文件脚本 (#209)
-----------------------------------

 

 

 如题 像这样的 怎么添加到脚本里面  求教。。

**Comment by QQ1142057049** [comment]
> 增加raw脚本，然后添加定时就可以了
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："QQ1142057049 ***@***.***&gt;; 发送时间：2021年7月1日(星期四) 下午4:35 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] 怎么添加 js 文件脚本 (#209) ----------------------------------- 如题 像这样的 怎么添加到脚本里面 求教。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没明白  不懂  能说的具体一点吗
