### ISSUE TITLE
最近js_tool面板老出现问题

### ISSUE THREAD

**Issue by qingcheng123** [lan-tianxiang/JS_TOOL#210]
v3的面板直接打不开，A1的终端打不开：
Cannot GET /RandomShellEntry

**Comment by tslace** [comment]
刚才终端更新脚本，更新完后提示连接中断，尝试更新三四次后面板无法访问，重启面板才好。。

**Comment by tslace** [comment]
刚才执行runall1，跑着跑着就连接中断了。。
