### ISSUE TITLE
更新脚本面板就挂了，修复脚本也不好用了，和这次更新有关吗？

### ISSUE THREAD

**Issue by wingswing** [lan-tianxiang/JS_TOOL#213]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ x] Docker

## 3. 是否用一键脚本部署的？

- [ x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by wingswing** [comment]
另外定时文件能增加三方库和主库的同名脚本去重功能吗？

**Comment by sorker** [comment]
我也是，都不运行了，重启docker也不行

**Comment by Rosylusi** [comment]
卸载，重装

**Comment by ZhoucpSAMA** [comment]
为什么进不去面板了

**Comment by wingswing** [comment]
> 卸载，重装

重装也不行呀

**Comment by Rosylusi** [comment]
> > 卸载，重装
> 
> 重装也不行呀

重装完之后有没有输入手动开启命令

**Comment by wingswing** [comment]
> > > 卸载，重装
> > 
> > 
> > 重装也不行呀
> 
> 重装完之后有没有输入手动开启命令

什么开启命令？docker？
现在是脚本应该还在挂机，面板打不开

**Comment by wingswing** [comment]
更新了下脚本 能看到面板页面 无法登陆呀

**Comment by Rosylusi** [comment]
> > > > 卸载，重装
> > > 
> > > 
> > > 重装也不行呀
> > 
> > 
> > 重装完之后有没有输入手动开启命令
> 
> 什么开启命令？docker？
> 现在是脚本应该还在挂机，面板打不开

你不是重装了吗？重装以后脚本还能挂机吗？我也是小白，也不是很懂，反正我重装以后手动开启面板就一切都好

**Comment by wingswing** [comment]
> > > > > 卸载，重装
> > > > 
> > > > 
> > > > 重装也不行呀
> > > 
> > > 
> > > 重装完之后有没有输入手动开启命令
> > 
> > 
> > 什么开启命令？docker？
> > 现在是脚本应该还在挂机，面板打不开
> 
> 你不是重装了吗？重装以后脚本还能挂机吗？我也是小白，也不是很懂，反正我重装以后手动开启面板就一切都好

可以挂机 我备份了配置和cookie 应该是缺文件了

**Comment by wintsa123** [comment]
就用恢复命令就好了，然后重启下，等等。恢复命令挺不错的
