### ISSUE TITLE
请问如何添加其他脚本比如京东到家？

### ISSUE THREAD

**Issue by JeremyMin666** [lan-tianxiang/JS_TOOL#215]
### 想要增加什么样的功能或者哪里存在不足之处呢？

请问如何添加其他脚本比如京东到家？
https://github.com/passerby-b/JDDJ

**Comment by MrH723** [comment]
ThirdpardRepoUrl1="https://github.com/passerby-b/JDDJ.git"

**Comment by JeremyMin666** [comment]
> ThirdpardRepoUrl1="https://github.com/passerby-b/JDDJ.git"

那定时那些需要设置吗？
