### ISSUE TITLE
windows安装docker没反应

### ISSUE THREAD

**Issue by zhongzeqing** [lan-tianxiang/JS_TOOL#216]
![image](https://user-images.githubusercontent.com/43203407/124213033-80ba5c00-db22-11eb-8234-5fcc28202c57.png)
da'lao大佬们帮忙看看，我windows安装了docker后，运行脚本没有反应

**Comment by QQ1142057049** [comment]
bash

**Comment by SQDFeng** [comment]
![}R(@G)763W4%A@A5 @2M5LY](https://user-images.githubusercontent.com/11267586/124297201-679ac500-db8d-11eb-93e9-6fdf3bc9d997.png)包括ubuntu在内一起重装重新配置环境，面板能打开了，但是这个情况依然没有好，所有脚本都提示获取不到cookie，然而实际上有填写，现在回退到之前的版本可以正常使用
