### ISSUE TITLE
今天自动更新了定时脚本，但和以前不同呢。

### ISSUE THREAD

**Issue by LvDeShei** [lan-tianxiang/JS_TOOL#217]
表达式前增加了cron，之前都是直接表达式的
12 */4 * * * jd jd_syj
10 10,18 * * * jd jd_try
45 23 * * * jd jd_unsubscribe
5 0 * * * jd jx_sign
cron 0 10 * * * jd jd_europeancup
55 7,15,23 * * * jd jd_joy_validate
cron 1 0-23/2 * * * jd jd_qqxing
cron 30 11 * * * jd jd_superBrand
cron 5 0-23/6 * * * jd jd_wsdlb
cron 10 * * * * jd jx_mc_coin
cron 10 * * * * jd jx_mc_emptycabbage
cron 5 0-23/6 * * * jd jd_lsj

**Comment by LvDeShei** [comment]
这样有问题吗，谢谢。

**Comment by xiaojia21190** [comment]
会报错

**Comment by wingswing** [comment]
把前面删了吧 应该和以前一致
