### ISSUE TITLE
今天更新了 怎么控制面板进不去了？

### ISSUE THREAD

**Issue by Aomsqian** [lan-tianxiang/JS_TOOL#218]

**Comment by qingcong** [comment]
从昨天6点开始脚本停止运行，然后今天重启docker以后面板同样进不去了。

然后查看之前的cookie都变少了

**Comment by SQDFeng** [comment]
一样的情况，填了有效cookie，运行各种脚本提示获取cookie为0，尝试重装修复后控制面板已无法进入

**Comment by PalmerCharles** [comment]
我这定时任务也不跑了，进入容器执行jd xxx命令也没有反应，重装也一样

**Comment by SQDFeng** [comment]
![}R(@G)763W4%A@A5 @2M5LY](https://user-images.githubusercontent.com/11267586/124297469-adf02400-db8d-11eb-934e-9658eceeedb7.png)包括ubuntu在内一起重装重新配置环境，面板能打开了，但是这个情况依然没有好，所有脚本都提示获取不到cookie，然而实际上有填写，现在回退到之前的版本可以正常使用

**Comment by gzshasha** [comment]
1号早上6点之后脚本就GG了，面板能进，但不能签到，手动签到也不行。

**Comment by GPK0801** [comment]
me too，删除原来的容器跟镜像，重新部署就正常了，不过发现点点券好像又不行了，希望能修复一下

**Comment by shanhai2333** [comment]
更新就进不去+1

**Comment by SKzxsk** [comment]
这个事故告诉我们要养成常备份的好习惯
