### ISSUE TITLE
用一键脚本命令安装的，怎么卸载呢？

### ISSUE THREAD

**Issue by lanyucomputer** [lan-tianxiang/JS_TOOL#22]
wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/linux_install_jd.sh -O linux_install_jd.sh && chmod +x linux_install_jd.sh && bash linux_install_jd.sh
用这个脚 本安装的怎么样才可以完全删掉，DOCKER的可以很容易，这个不知道怎么删除

**Comment by lan-tianxiang** [comment]
这个删除更简单的，只需要删除`jd`这个文件夹即可

**Comment by lan-tianxiang** [comment]
不会有其他残留的

**Comment by opojin** [comment]
> 这个删除更简单的，只需要删除`jd`这个文件夹即可

怎么我的vps root 目录下没有jd文件夹呢？
