### ISSUE TITLE
jd_wsdlb这个脚本是个啥情况？？？

### ISSUE THREAD

**Issue by fuyu-site** [lan-tianxiang/JS_TOOL#221]
![image](https://user-images.githubusercontent.com/58680078/124345669-e7b43f80-dc0c-11eb-8eb8-b0e7493c0145.png)

![image](https://user-images.githubusercontent.com/58680078/124345673-ebe05d00-dc0c-11eb-9e9b-14d667fc495e.png)

**Comment by SQDFeng** [comment]
原来新版使用异常无法获取cookie是这个脚本的锅？

**Comment by fuyu-site** [comment]
> 原来新版使用异常无法获取cookie是这个脚本的锅？

应该不是
这个是我今天在pushplus的推送里面看见这个脚本发的广告了
瞟了一眼js文，不知道这个脚本到底啥情况

**Comment by SQDFeng** [comment]
> > 原来新版使用异常无法获取cookie是这个脚本的锅？
> 
> 应该不是
> 这个我今天在pushplus的演示里面看到脚本这个发的广告了
> 瞟了眼js文，不知道这个脚本到底啥情况

![}R(@G)763W4%A@A5 @2M5LY](https://user-images.githubusercontent.com/11267586/124354981-7347c380-dc41-11eb-865b-f4ad80f98c81.png)
不过我的每个脚本提示都有这句话，也有怀疑的可能性

**Comment by fuyu-site** [comment]
> > > 原来新版使用异常无法获取cookie是这个脚本的锅？
> > 
> > 
> > 应该不是
> > 这个我今天在pushplus的演示里面看到脚本这个发的广告了
> > 瞟了眼js文，不知道这个脚本到底啥情况
> 
> ![}R(@G)763W4%A@A5 @2M5LY](https://user-images.githubusercontent.com/11267586/124354981-7347c380-dc41-11eb-865b-f4ad80f98c81.png)
> 不过我的每个脚本提示都有这句话，也有怀疑的可能性

你那个是jd的
我说的是这种广告
这网站是我图中的脚本加的
![IMG_20210703_214942](https://user-images.githubusercontent.com/58680078/124356466-b0fc1a80-dc48-11eb-880b-7962ee523a13.jpg)

**Comment by awardat** [comment]
http://a8pck.cn/VbjDm
这个地址我昨天访问是个广告，刚才试又是对的

**Comment by Glernen** [comment]
那个main.xxx.js是个什么文件运行产生的

**Comment by xintq** [comment]
这个脚本应该没啥用了吧，看代码是执行 https://thebigboss.jd.com/ 的任务，这个活动已经停止了

**Comment by ghost** [comment]
m.jd.com获取的cookie，怎么一天不到就过期了呢？有大佬知道吗
