### ISSUE TITLE
京东健康社区是不是不能运行？

### ISSUE THREAD

**Issue by lideli2566128** [lan-tianxiang/JS_TOOL#222]
~/jd $ jd jd_health.js 1
您的操作系统为：Android 架构：aarch64
~/jd $ jd jd_health_collect.js 1
您的操作系统为：Android 架构：aarch64
请问大佬收到这样的提示的话，是不是就是健康社区脚本不能运行？这样的话应该怎么样才能解决呢？

**Comment by wintsa123** [comment]
用不了就别用。。。。。把脚本除去定时就好了，实在不行，你自己打开京东健康社区抓包吧

**Comment by lideli2566128** [comment]
> 用不了就别用。。。。。把脚本除去定时就好了，实在不行，你自己打开京东健康社区抓包吧

好的，谢谢，那就不用了
