### ISSUE TITLE
安卓跑A1的又一困惑

### ISSUE THREAD

**Issue by biewenwoshishui021** [lan-tianxiang/JS_TOOL#224]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否阅读了常见问题
- [ x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [x ] Linux，实际上是安卓termux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：
添加了几个第三方js拷到scripts文件夹里，但运行bash jd update，总是提示权限方面的出错。

### (2) 详细日志
A：

更新/data/data/com.termux/files/home/JS_TOOL/scripts成功... 
chmod: changing permissions of '/data/data/com.termux/files/home/JS_TOOL/scripts/Andy_sendBeans.js': Operation not permitted                                                        chmod: changing permissions of '/data/data/com.termux/files/home/JS_TOOL/scripts/DIY_shopsign.js': Operation not permitted
chmod: changing permissions of '/data/data/com.termux/files/home/JS_TOOL/scripts/dust_z_health_energy.js': Operation not permitted

**Comment by biewenwoshishui021** [comment]
能否告知，应该设置权限是怎样的，上面这些警告才不会有？？谢谢！！

**Comment by biewenwoshishui021** [comment]
老大为何关闭帖子？？？伤心？。。。。

**Comment by lan-tianxiang** [comment]
> 老大为何关闭帖子？？？伤心？。。。。

问题太多了，都没看到了，在讨论区发起吧，哈哈啊哈
