### ISSUE TITLE
所有京东账号的京豆消失了，问了客服说是给一个132开头的手机号投注去了

### ISSUE THREAD

**Issue by yyx2684264** [lan-tianxiang/JS_TOOL#229]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：
没啥详细日志，就是今天（2021年7月5日）突然所有账号的京豆全部消失了，咨询了客服说被弄到了一个132开头的手机账号下买了彩票，通过微信小程序“赚京豆”
请问其他人有这个情况吗

**Comment by xlbgxlbg** [comment]
我也有

**Comment by xlbgxlbg** [comment]
通过赚京豆小程序-彩票兑换-购买，并把彩票信息绑定到盗用者手机号。拿不回来了

**Comment by lan-tianxiang** [comment]
暂时先关闭，可以重新提出，我看一下是什么原因
