### ISSUE TITLE
所有cookie，豆子超过1500的被盗刷，用于赚京豆小程序兑换了彩票。

### ISSUE THREAD

**Issue by xlbgxlbg** [lan-tianxiang/JS_TOOL#235]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
所有用这个程序的人，cookie应该都被恶意攻击者获取了，这几天助力全部没有，今天2021 07 05，豆子超过1500的被盗刷，用于赚京豆小程序给攻击者兑换了彩票。

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
有没有用其他的第三方脚本呢

**Comment by lan-tianxiang** [comment]
1500单位是个，还是元

**Comment by xlbgxlbg** [comment]
1、没有用过第三方库，docker安装后没动过。
2、发现问题就这两三天，所有的领现金的助力次数，在没有本地日志的情况下连续两天没有了，本来以为是黑号了，找了半天问题，中午突然发现所有京豆全都被盗刷。
3、1500是京豆数量。我自己号只有600个豆子，没被刷，所有超过1500以上的号全都被刷完了。
4、豆子用于买彩票，300豆子一注，问京东客服，说是用于绑定一个手机号了

**Comment by xlbgxlbg** [comment]
我挂了周围共20个人的号，一次性被盗刷了300多块钱的京豆

**Comment by Soarfree** [comment]
前几天漏洞出来时候 把cookie全部失效一遍 重新获取下就没事了  再说这东西最好还是在本地挂 不开外网端口 就比较安全了

**Comment by xlbgxlbg** [comment]
确实没想到会发生这个，以后就本地用用了

**Comment by lan-tianxiang** [comment]
@xlbgxlbg  面板暂时没有做暴力破解等相关的安全措施，有被攻破的可能。对于你的情况感到非常抱歉。

**Comment by Soarfree** [comment]
再狠一点 防火墙设置下 除了拉库的域名 还有京东旗下的域名 其他都禁止通过

**Comment by xlbgxlbg** [comment]
如果有相同问题的人，找京东客服，客服会把你盗刷的全部返还。

**Comment by xlbgxlbg** [comment]
我的几个号已经找回损失了

**Comment by lan-tianxiang** [comment]
建议先将现有的Cookie失效处理，然后修改密码。
失效脚本命令 jd jd_exit
@xlbgxlbg

**Comment by lan-tianxiang** [comment]
> 我的几个号已经找回损失了

好
