### ISSUE TITLE
大佬最新的面板运行了，打不开啊A1 的

### ISSUE THREAD

**Issue by timessage** [lan-tianxiang/JS_TOOL#236]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
先更新一下，然后输入jd panelon

**Comment by timessage** [comment]
> 先更新一下，然后输入jd panelon

改默认端口的文件在哪

**Comment by lan-tianxiang** [comment]
server.js

**Comment by lan-tianxiang** [comment]
不过每次更新会自动覆盖成5678

**Comment by timessage** [comment]
OK，多谢大佬

**Comment by lan-tianxiang** [comment]
推荐你使用docker，只需要更改映射端口就可以了
