### ISSUE TITLE
在每次推送的时候最底下这段字就一半，稍微有点不舒服，有没有大佬知道这段字在哪里文件当中？《本脚本免费使用 ByXXXXXXXXXXXX》

### ISSUE THREAD

**Issue by Rosylusi** [lan-tianxiang/JS_TOOL#24]
在每次推送的时候最底下这段字就一半，稍微有点不舒服，有没有大佬知道这段字在哪里文件当中？《本脚本免费使用 ByXXXXXXXXXXXX》

**Comment by lan-tianxiang** [comment]
已经为你单独优化了，更新完可以再看一下

**Comment by zuikundeyuan** [comment]
人心险恶啊,知道在哪个文件中,替换掉,然后拿去卖钱?

**Comment by lan-tianxiang** [comment]
> 人心险恶啊,知道在哪个文件中,替换掉,然后拿去卖钱?

希望他不是。 `本脚本免费使用 ByXXXXXXXXXXXX`对我个人觉得并不会引起不适，的确不排除售卖软件怕别人看到信息的可能😣

**Comment by Rosylusi** [comment]
各位老师，请不要这样说，我连环境都是别人帮我搭的，后来自己想学习就把环境删掉了，现在还卡着呢，老师应该有在那个教获取cookie的帖子里看到我的

**Comment by Rosylusi** [comment]
说实话，因为那个环境是别人帮我搭的，只是想知道那个网址好学习一下，后来我也问了我朋友，也确定了问题所在，是那个推送的什么酱显示字数不全而已
![Uploading AB9B293A-861D-4428-BD7D-3F87C0AAD964.png…]()

**Comment by lan-tianxiang** [comment]
> 说实话，因为那个环境是别人帮我搭的，只是想知道那个网址好学习一下，后来我也问了我朋友，也确定了问题所在，是那个推送的什么酱显示字数不全而已

哈哈，别担心。那个朋友也是为了我们整体使用者提出的合理质疑，只要不是，那就没有必要担心。😘

**Comment by 895450603** [comment]
嗯嗯，这也是我所希望的，只是我一个小白，连环境都还没搭起来🐶

**Comment by Rosylusi** [comment]
> > 说实话，因为那个环境是别人帮我搭的，只是想知道那个网址好学习一下，后来我也问了我朋友，也确定了问题所在，是那个推送的什么酱显示字数不全而已
> 
> 哈哈，别担心。那个朋友也是为了我们整体使用者提出的合理质疑，只要不是，那就没有必要担心。😘


嗯嗯，这也是我所希望的，只是我一个小白，连环境都还没搭起来🐶

**Comment by zuikundeyuan** [comment]
> > > 说实话，因为那个环境是别人帮我搭的，只是想知道那个网址好学习一下，后来我也问了我朋友，也确定了问题所在，是那个推送的什么酱显示字数不全而已
> > 
> > 
> > 哈哈，别担心。那个朋友也是为了我们整体使用者提出的合理质疑，只要不是，那就没有必要担心。😘
> 
> 嗯嗯，这也是我所希望的，只是我一个小白，连环境都还没搭起来🐶

如果误伤我向你道歉.因为我看到你主页全都是一些带有你私人邀请码的拿人头项目,所以有这个猜测.最后再次向你为我的恶意猜测道歉

**Comment by Rosylusi** [comment]
> 
> 
> > > > 说实话，因为那个环境是别人帮我搭的，只是想知道那个网址好学习一下，后来我也问了我朋友，也确定了问题所在，是那个推送的什么酱显示字数不全而已
> > > 
> > > 
> > > 哈哈，别担心。那个朋友也是为了我们整体使用者提出的合理质疑，只要不是，那就没有必要担心。😘
> > 
> > 
> > 嗯嗯，这也是我所希望的，只是我一个小白，连环境都还没搭起来🐶
> 
> 如果误伤我向你道歉.因为我看到你主页全都是一些带有你私人邀请码的拿人头项目,所以有这个猜测.最后再次向你为我的恶意猜测道歉

没事没事，也没那么严重，我只是说明一下情况，毕竟作者大佬开发也辛苦，不能让他寒心~本人小白，就主页那个你不说我都快忘了还有这个，不过那个是要靠拉人头才赚钱，这个是自己就能赚钱，所以也不能相提并论，只是都希望薅点羊毛，对于这个js_tool的，我还是在学习阶段
