### ISSUE TITLE
centos 7 安装后想删除怎么删

### ISSUE THREAD

**Issue by lanyucomputer** [lan-tianxiang/JS_TOOL#25]
wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/linux_install_jd.sh -O linux_install_jd.sh && chmod +x linux_install_jd.sh && bash linux_install_jd.sh
用这个命令安装的，装多了一个，有冲突想删除一个，怎么删？

**Comment by Sherlockouo** [comment]
同问怎么删除或者关闭脚本

**Comment by lan-tianxiang** [comment]
可以搜索一下关于docker删除的知识。
提出的问题不错，已经为你和后续的伙伴优化了，新的脚本安装前会自动删除先前的docker

**Comment by lanyucomputer** [comment]
docker 方式的好删，，用docker stop jd,然后docker rm jd,就可以了，我要问的是直接安装到系统后的删除，不是DOCKER方式的，谢谢你了

**Comment by lan-tianxiang** [comment]
直接安装到系统里面的只会生成一个目录，所有文件都在目录下，直接删除目录即可。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："lanyucomputer ***@***.***&gt;;
发送时间：2021年5月26日(星期三) 晚上11:04
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] centos 7 安装后想删除怎么删 (#25)
-----------------------------------

 

 
docker 方式的好删，，用docker stop jd,然后docker rm jd,就可以了，我要问的是直接安装到系统后的删除，不是DOCKER方式的，谢谢你了

**Comment by lanyucomputer** [comment]
rm -rf jd，谢谢

**Comment by lan-tianxiang** [comment]
是的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："lanyucomputer ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 上午9:15
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] centos 7 安装后想删除怎么删 (#25)
-----------------------------------

 

 
rm -rf jd，谢谢
