### ISSUE TITLE
cookie 手动失效问题

### ISSUE THREAD

**Issue by xlbgxlbg** [lan-tianxiang/JS_TOOL#257]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：背景：继京豆被盗刷问题之后，在2021/7/6下午，我又一次手动失效了京东cookie。并删除了docker
          然后重新安装docker，修改了默认登陆面板密码，用7个号做测试，四个号重新登陆了JS_TOOL，三个号没登陆。
结果是无论登录与否，助力次数还是被用完了。用京东财富岛为案例，七个号全都在jd_**72d 、田田9**2 、201**DAN下面打工。
     
 问题：cookie失效是否有用，因为我的cookie还是在被人盗用，失效后不登录也在用

### (2) 详细日志
A：

**Comment by xlbgxlbg** [comment]
是否说，账号跑一边任务，日志里面的互助码在cookie失效后，互助码还是会继续生效？

**Comment by ryan016** [comment]
有些活动的助力码是不变的，不论你的cookie如何改变，助力码永远不变。
这种情况下，脚本的定时你只能往前调整，不要使用默认的时间。

**Comment by lan-tianxiang** [comment]
@xlbgxlbg   `jd_72d 、田田92 、201**DAN`这应该是原作者的账号，我稍后删除

**Comment by lan-tianxiang** [comment]
好了，去除了
