### ISSUE TITLE
windows Ubuntu 定时任务占用内存过高，第一次启动的时候内存占用正常，长时间启动内存使用会增加很多

### ISSUE THREAD

**Issue by lkswritecode** [lan-tianxiang/JS_TOOL#258]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lkswritecode** [comment]
查看内存占用情况，出现了很多node应用，比定时任务的数量还多

**Comment by sm1lewc** [comment]
这个是wsl机制的问题
C:\Users\当前用户    目录下创建.wslconfig文件
文件里写入

[wsl2]
memory=500MB
swap=2GB
localhostForwarding=true

限制最大内存500MB

**Comment by lkswritecode** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lan-tianxiang/JS_TOOL] windows Ubuntu 定时任务占用内存过高，第一次启动的时候内存占用正常，长时间启动内存使用会增加很多 (#258)





 
这个是wsl机制的问题
 C:\Users\当前用户    目录下创建.wslconfig文件
 文件里写入
 
[wsl2]
 memory=500MB
 swap=2GB
 localhostForwarding=true
 
限制最大内存500MB
