### ISSUE TITLE
关于管理界面的终端显示错误的问题

### ISSUE THREAD

**Issue by wys206** [lan-tianxiang/JS_TOOL#265]
管理界面进去后点终端显示"Error occured while trying to proxy: 127.0.0.1:5678/"，大佬能修复一下嘛
![Screenshot_2021-07-07-23-58-59-964_com android browser](https://user-images.githubusercontent.com/45279055/124792576-b1b1eb00-df7f-11eb-9f48-006665fc061d.jpg)

**Comment by wys206** [comment]
还是说我个人设置哪里出了问题？

**Comment by lan-tianxiang** [comment]
这个错误一般是终端程序没正常运行

**Comment by lan-tianxiang** [comment]
你看一下panel目录下有没有ttyd这个文件

**Comment by wys206** [comment]
> 你看一下panel目录下有没有ttyd这个文件

嗯嗯，有，不过用mt管理器进去后乱码

**Comment by lan-tianxiang** [comment]
有的话就再次运行jd panel试试

**Comment by wys206** [comment]
> 有的话就再次运行jd panel试试

手机的termux还是不大行，不用它了，别的能用就足够了！docker的能用！
大佬，电报的bot设置怎么弄，能整个教程吗？研究到今天早上都没整明白，就是终端运行python3 bot.py ，提示
root@jd:~/jd/bot $  python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 24, in <module>
    with open('/jd/config/bot.json') as f:
NotADirectoryError: [Errno 20] Not a directory: '/jd/config/bot.json'
可是文件夹里有这个文件呀，是哪里出问题了呢？

**Comment by lan-tianxiang** [comment]
修复了一下，更新完重新拷贝bot.py就可以了
