### ISSUE TITLE
支持py脚本吗？

### ISSUE THREAD

**Issue by wingswing** [lan-tianxiang/JS_TOOL#268]
### 想要增加什么样的功能或者哪里存在不足之处呢？

这个大佬的能支持吗？
https://github.com/curtinlv/JD-Script

**Comment by lan-tianxiang** [comment]
已支持，更新即可

**Comment by wingswing** [comment]
> 已支持，更新即可

感谢大佬 么么哒
 话说更新了怎么用呀？

**Comment by lan-tianxiang** [comment]
添加raw地址，然后通过jd +xxx.py来执行

**Comment by wingswing** [comment]
> 添加raw地址，然后通过jd +xxx.py来执行

总是提示脚本不存在

**Comment by lan-tianxiang** [comment]
输入完整文件名  xxx.py

**Comment by wingswing** [comment]
> 输入完整文件名 xxx.py

之前文件名输错了
提 运行示
/usr/local/bin/jd: line 1623: python3: command not found

我是用这个脚本测试的，不知道是哪里有问题，感谢大佬

**Comment by lan-tianxiang** [comment]
如果是docker的话输入`apk add python3`，安装python环境

**Comment by wingswing** [comment]
> 如果是docker的话输入`apk add python3`，安装python环境

感谢，可以运行了，好像脚本有问题，太感谢了

**Comment by lan-tianxiang** [comment]
没事

**Comment by Haon1348326083** [comment]
大佬我能加进群嘛，正在装着，感觉很多问题不懂
