### ISSUE TITLE
更新提示errors in crontab file, can't install.

### ISSUE THREAD

**Issue by Rosylusi** [lan-tianxiang/JS_TOOL#270]
系统时间：2021-07-08 16:45:25

脚本根目录：/root/jd

jd_scripts目录：/root/jd/scripts

thirdpard脚本目录：/root/jd/thirdpard

--------------------------------------------------------------

开始更新仓库：/root/jd

正在获取 origin
HEAD 现在位于 8aa87b8 更新于 07-08 01:40
已经是最新的。

更新成功...

开始更新仓库：/root/jd/scripts

正在获取 origin
HEAD 现在位于 cf8e6a33 更新于 07-08 03:01
已经是最新的。

更新/root/jd/scripts成功...

"/root/jd/config/crontab.list":54: bad day-of-month
errors in crontab file, can't install.
"/root/jd/config/crontab.list":54: bad day-of-month
errors in crontab file, can't install.
您的操作系统为：Debian 架构：x86_64

errors in crontab file, can't install.这个错误是什么原因？

**Comment by lan-tianxiang** [comment]
这个的话，你把定时文件中的jd_joy_reward这行删了更新一下就行了

**Comment by Rosylusi** [comment]
> 这个的话，你把定时文件中的jd_joy_reward这行删了更新一下就行了

OK，谢谢大佬
