### ISSUE TITLE
A1版本，添加第三方库，显示添加成功，实际上没有成功。

### ISSUE THREAD

**Issue by xxp2277** [lan-tianxiang/JS_TOOL#28]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：添加和尚脚本，每次bash jd.sh update，都提示更新成功且添加了定时任务，但实际未成功。

### (2) 详细日志
A：日志显示完全正常的样子。

**Comment by lan-tianxiang** [comment]
好的，近期马上修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xxp2277 ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 晚上9:11
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] A1版本，添加第三方库，显示添加成功，实际上没有成功。 (#28)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：添加和尚脚本，每次bash jd.sh update，都提示更新成功且添加了定时任务，但实际未成功。
 
(2) 详细日志
 
A：日志显示完全正常的样子。

**Comment by biewenwoshishui021** [comment]
又来占楼了。两个事:
1、作者你上面说的近期修复，好了吗？

2、最新的config.sh，第34和36项重复，都是jxnc的控制。

哈哈😄加油💪

**Comment by lan-tianxiang** [comment]
好，知道了。我修复了会发通知的，耐心等待🥰&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："biewenwoshishui021 ***@***.***&gt;;
发送时间：2021年5月29日(星期六) 凌晨5:09
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] A1版本，添加第三方库，显示添加成功，实际上没有成功。 (#28)
-----------------------------------

 

 
又来占楼了。两个事:
 1、作者你上面说的近期修复，好了吗？
 
2、最新的config.sh，第34和36项重复，都是jxnc的控制。
 
哈哈加油

**Comment by lan-tianxiang** [comment]
修复了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："biewenwoshishui021 ***@***.***&gt;;
发送时间：2021年5月29日(星期六) 凌晨5:09
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] A1版本，添加第三方库，显示添加成功，实际上没有成功。 (#28)
-----------------------------------

 

 
又来占楼了。两个事:
 1、作者你上面说的近期修复，好了吗？
 
2、最新的config.sh，第34和36项重复，都是jxnc的控制。
 
哈哈加油

**Comment by lan-tianxiang** [comment]
> 又来占楼了。两个事:
> 1、作者你上面说的近期修复，好了吗？
> 
> 2、最新的config.sh，第34和36项重复，都是jxnc的控制。
> 
> 哈哈😄加油💪

@biewenwoshishui021 修复了，删除config下的crontab.list，然后输入`crontab -r`

**Comment by biewenwoshishui021** [comment]
谢谢大佬！

**Comment by lan-tianxiang** [comment]
> 谢谢大佬！

没事，感谢反馈

**Comment by xxp2277** [comment]
> 
> 
> > 谢谢大佬！
> 
> 没事，感谢反馈

感谢大佬更新解决问题，有空回来群里聊聊天呀。（关闭issues了）
