### ISSUE TITLE
用户设定里的某些账号不玩小游戏设定后手动执行无效？

### ISSUE THREAD

**Issue by wingswing** [lan-tianxiang/JS_TOOL#293]
### 想要增加什么样的功能或者哪里存在不足之处呢？

不知道写的对不对
case $1 in
   jd_price)
   TempBlockCookie="8 9"      # 账号8 9不玩保价
   ;;
   jd_qqxing)
   TempBlockCookie="5 6 7 8 9"
   ;;
   esac
保存后手动运行jd_qqxing一样执行cookie5-9，是我写的不对还是有问题呢？请教一下！

**Comment by lan-tianxiang** [comment]
貌似没错的，你把屏蔽的这部分截一个完整的图给我看一下

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："wingswing ***@***.***&gt;;
发送时间：2021年7月9日(星期五) 晚上7:08
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 用户设定里的某些账号不玩小游戏设定后手动执行无效？ (#293)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
不知道写的对不对
 case $1 in
 jd_price)
 TempBlockCookie="8 9"      # 账号8 9不玩保价
 ;;
 jd_qqxing)
 TempBlockCookie="5 6 7 8 9"
 ;;
 esac
 保存后手动运行jd_qqxing一样执行cookie5-9，是我写的不对还是有问题呢？请教一下！

**Comment by wingswing** [comment]
![Uploading IMG_20210709_195231.jpg…]()

**Comment by wingswing** [comment]
![IMG_20210709_195231](https://user-images.githubusercontent.com/11457669/125074202-8d751c00-e0ef-11eb-82e7-7ba9aae54045.jpg)
手机党 能上传吗

**Comment by lan-tianxiang** [comment]
把最后一行去掉就好了
![image](https://user-images.githubusercontent.com/42911023/125075646-79cab500-e0f1-11eb-815a-b29708bf7df0.png)

**Comment by wingswing** [comment]
感谢大佬。
那从逻辑上来说，这两个功能不能共存？
即满足某些账号不玩部分游戏的情况下，在其它有的账号失效的时候，不能临时屏蔽失效账号？

**Comment by lan-tianxiang** [comment]
好提议，准备更新自动屏蔽失效账号功能，等几天吧

**Comment by wingswing** [comment]
感谢大佬
