### ISSUE TITLE
jd_daydlt，黑号无限执行。不自动跳过

### ISSUE THREAD

**Issue by ly7788110** [lan-tianxiang/JS_TOOL#296]
jd_daydlt，黑号无限执行。跳转不过。
![image](https://user-images.githubusercontent.com/77609647/125097355-9faf8400-e108-11eb-8067-91295730436f.png)
怎么才能让他先停下来
@lan-tianxiang

_Originally posted by @ly7788110 in https://github.com/lan-tianxiang/JS_TOOL/discussions/295_

**Comment by wjj982** [comment]
我注释掉了

**Comment by lan-tianxiang** [comment]
好，已经争对修复了一下

**Comment by lan-tianxiang** [comment]
更新即可
