### ISSUE TITLE
定时任务crontab.list问题

### ISSUE THREAD

**Issue by Asimpl0** [lan-tianxiang/JS_TOOL#3]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：
crontab.list无法定时运行
将jd替换为bash ~/jd/jd.sh可以运行

### (2) 详细日志
A：

**Comment by Jackfinal** [comment]
`-rwxr-xr-x. 1 root root     0 Apr 17 18:39 crontab.list`
这个是什么问题，crontab.list 为空

**Comment by xiaomexiaoerlang** [comment]
同问+1，定时任务不运行。crontab.list 文件正常。

**Comment by xiaomexiaoerlang** [comment]
```
crond -ipP
```
**请注意：每次重启手机或重启`Termux`后需要重新输入上述命令。**

如果输入上述命令后显示类似以下内容的错误，那么表示cronie已经启动好了，无需再次启动：
```
crond: can't lock /data/data/com.termux/files/usr/var/run/crond.pid, otherpid may be 3087: Try again
```
