### ISSUE TITLE
大佬，这个能开bot机器人么，能的话告知下方法

### ISSUE THREAD

**Issue by xxp2277** [lan-tianxiang/JS_TOOL#30]
以下参数已设置为true
ENABLE_TG_BOT="true"
还需要什么设置呢，手动安装python？

**Comment by huzichai** [comment]
机器人有什么作用吗？

**Comment by xxp2277** [comment]
适合于电报远程管理

**Comment by PoetryU** [comment]
```shell
## 相关配置，请进入config/bot.json进行设置
## 开启则填true,默认关闭
ENABLE_TG_BOT="true"
```
遇到同样的问题，这里设置为`true`，没找到`config/bot.json`，该如何设置呢？

**Comment by qq7984225** [comment]
不能 没有机器人

**Comment by sorker** [comment]
> ```shell
> ## 相关配置，请进入config/bot.json进行设置
> ## 开启则填true,默认关闭
> ENABLE_TG_BOT="true"
> ```
> 
> 遇到同样的问题，这里设置为`true`，没找到`config/bot.json`，该如何设置呢？

sample文件夾下有bot.json文件，複製到config文件夹下
