### ISSUE TITLE
现在不用授权了吗

### ISSUE THREAD

**Issue by xiaorizi01** [lan-tianxiang/JS_TOOL#32]
老哥，现在这个不用授权了吗，可以多号使用了吗

**Comment by lan-tianxiang** [comment]
嗯，是的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xiaorizi01 ***@***.***&gt;;
发送时间：2021年6月1日(星期二) 下午3:21
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 现在不用授权了吗 (#32)
-----------------------------------

 

 
老哥，现在这个不用授权了吗，可以多号使用了吗

**Comment by xiaorizi01** [comment]
好的，感谢老哥！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lan-tianxiang ***@***.***&gt;
发送时间: 2021年6月1日 16:11
收件人: lan-tianxiang/JS_TOOL ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lan-tianxiang/JS_TOOL] 现在不用授权了吗 (#32)





 嗯，是的 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 
 --------------原始邮件-------------- 
 发件人："xiaorizi01 ***@***.***&amp;gt;; 
 发送时间：2021年6月1日(星期二) 下午3:21 
 收件人："lan-tianxiang/JS_TOOL" ***@***.***&amp;gt;; 
 抄送："Subscribed ***@***.***&amp;gt;; 
 主题：[lan-tianxiang/JS_TOOL] 现在不用授权了吗 (#32) 
 ----------------------------------- 
 
   
 
   
 老哥，现在这个不用授权了吗，可以多号使用了吗
