### ISSUE TITLE
限制请求域名，提升安全性，尽量避免后门出现

### ISSUE THREAD

**Issue by Huansheng1** [lan-tianxiang/JS_TOOL#325]
### 想要增加什么样的功能或者哪里存在不足之处呢？

第三方脚本参差不齐，无法保证作者良心，故 对请求的 url 进行安全校验，防止运行了非法的脚本发送请求，从而避免被偷掉 ck。
1. 限制请求域名列表
2. 可通过环境变量配置增加域名，保证灵活性

参考案例：[https://github.com/atzcl/as/commit/84ccb598e167149d20bf1dff887c500e17d2ab2e](https://github.com/atzcl/as/commit/84ccb598e167149d20bf1dff887c500e17d2ab2e)

**Comment by lan-tianxiang** [comment]
好，感谢！！

**Comment by lan-tianxiang** [comment]
已增加
