### ISSUE TITLE
增加过期后cookie自动移除或者通知次数限制

### ISSUE THREAD

**Issue by zhanggaolei001** [lan-tianxiang/JS_TOOL#33]
### 想要增加什么样的功能或者哪里存在不足之处呢？

前两天遇到个问题,号cookie过期了,睡了一晚上,然后早上发了一亿条掉线通知.......

**Comment by lan-tianxiang** [comment]
哈哈哈哈，好der

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："zhanggaolei001 ***@***.***&gt;;
发送时间：2021年6月2日(星期三) 下午5:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 增加过期后cookie自动移除或者通知次数限制 (#33)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
前两天遇到个问题,号cookie过期了,睡了一晚上,然后早上发了一亿条掉线通知.......
