### ISSUE TITLE
关于替换第三方库作为主库出现的问题

### ISSUE THREAD

**Issue by wys206** [lan-tianxiang/JS_TOOL#330]
大佬，我用“JD_SCRIPTS_URL="https://github.com/yuannian1112/jd_scripts.git"”作为主库，可是运行jd update时显示如下内容，是哪里没设置好吗？还望告！
Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Updating fac72e8..64b5d70
error: Your local changes to the following files would be overwritten by merge:
        README.md
        docker/crontab_list.sh
        jd_cfd.js
        jd_cfd_lottery.js
        jd_cfdtx.js
        jd_cfdtx1.js
        jd_joy.js
        jd_opencard1.js
        jd_sendbean.js
        jd_sendbean1.js
        jd_sendbean2.js
        jd_sendbean3.js
        jd_summer_movement_help.js
        jd_zooCaptain01.js
        jd_zooOpencard12.js
        package.json
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        jd_cfd_loop.js
        jd_joy_steal.js
Please move or remove them before you merge.
Aborting

**Comment by lan-tianxiang** [comment]
我测试了一下，正常的。

你把主库链接换成这个
```
https://ghproxy.com/https://github.com/yuannian1112/jd_scripts.git
```
应该是你的网络问题

**Comment by lan-tianxiang** [comment]
你先看一下，不行的话我再看一下是什么问题

**Comment by wys206** [comment]
> 你先看一下，不行的话我再看一下是什么问题

我还是先用默认库吧，其他的加第三方库了！！

**Comment by laoshuaibip** [comment]
> 你先看一下，不行的话我再看一下是什么问题

fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
我这更新拉主库也会这样

**Comment by wys206** [comment]
> 你先看一下，不行的话我再看一下是什么问题
今天又试了一下，还是这样。
_开始更新仓库：/root/jd

Fetching origin
HEAD is now at 7b203d4 更新于 07-15 02:07

更新成功...

开始更新仓库：/root/jd/scripts

Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

更新/root/jd/scripts成功..._

**Comment by wys206** [comment]
> 你先看一下，不行的话我再看一下是什么问题

今天又试了一下，还是这样。

_开始更新仓库：/root/jd

Fetching origin
HEAD is now at 7b203d4 更新于 07-15 02:07

更新成功...

开始更新仓库：/root/jd/scripts

Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

更新/root/jd/scripts成功..._

**Comment by wys206** [comment]
> 你先看一下，不行的话我再看一下是什么问题


今天又试了一下，还是这样。
_开始更新仓库：/root/jd

Fetching origin
HEAD is now at 7b203d4 更新于 07-15 02:07

更新成功...

开始更新仓库：/root/jd/scripts

Fetching origin
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

更新/root/jd/scripts成功..._

**Comment by lan-tianxiang** [comment]
已修复，这回应该ok了

**Comment by lan-tianxiang** [comment]
确定没问题了  @wys206 
JD_SCRIPTS_URL="https://ghproxy.com/https://github.com/yuannian1112/jd_scripts.git"
JD_SCRIPTS_BRANCH="main"

**Comment by wys206** [comment]
> 确定没问题了 @wys206
> JD_SCRIPTS_URL="https://ghproxy.com/https://github.com/yuannian1112/jd_scripts.git"
> JD_SCRIPTS_BRANCH="main"

嗯哪，辛苦大佬
