### ISSUE TITLE
脚本更新以后jd.sh为空文本，用autofix以后，提示未经授权

### ISSUE THREAD

**Issue by oopuuu** [lan-tianxiang/JS_TOOL#332]
如题，什么原因啊

**Comment by lan-tianxiang** [comment]
回退错了，请再次使用Autofix.sh

**Comment by wys206** [comment]
> 回退错了，请再次使用Autofix.sh

怎么用呢？直接输入Autofix.sh和Autofix都提示command not found

**Comment by Rosylusi** [comment]
> 
> 
> 回退错了，请再次使用Autofix.sh

运行后提示“请告诉我你是谁”这是什么情况？

**Comment by wintsa123** [comment]
上次也遇到了，还是用repair.sh修复的，不过配置文件要重新填
