### ISSUE TITLE
运行无反应，在目录下输入bash AutoFix.sh

### ISSUE THREAD

**Issue by lan-tianxiang** [lan-tianxiang/JS_TOOL#333]

**Comment by ly7788110** [comment]
TS脚本这么手动运行?

**Comment by lan-tianxiang** [comment]
> TS脚本这么手动运行?

jd xxx.ts

**Comment by ly7788110** [comment]
@lan-tianxiang 
![image](https://user-images.githubusercontent.com/77609647/125462234-d1e27ba1-7344-4c7b-a859-a32c2d1d29a7.png)
没反应，是什么问题，是我输入错误 还是？

**Comment by lan-tianxiang** [comment]
> @lan-tianxiang
> ![image](https://user-images.githubusercontent.com/77609647/125462234-d1e27ba1-7344-4c7b-a859-a32c2d1d29a7.png)
> 没反应，是什么问题，是我输入错误 还是？

第一次运行会安装ts环境，比较慢。

**Comment by ly7788110** [comment]
感谢大佬、。https://hub.fastgit.org/smiek2221/scripts/blob/master/gua_wealth_island.js  刚刚更新了 财富岛，JS版本的。

**Comment by lan-tianxiang** [comment]
好的
