### ISSUE TITLE
昨晚出现jd.sh为0，早上重新部署后控制面板无法打开

### ISSUE THREAD

**Issue by hackgsl** [lan-tianxiang/JS_TOOL#341]
运行提示这个，看了下备份文件跟库，都没有这个文件
Error: ENOENT: no such file or directory, stat '/root/jd/panel/public/auth.html'

**Comment by mailwudong** [comment]
控制面板web 打不开了

**Comment by hackgsl** [comment]
> 
> 
> 控制面板web 打不开了

我重新部署了2次都不行，后面手工复制了个老的auth.html后可以打开，但是控制面板是旧的，然后我执行了下repair.sh修复后OK了。

**Comment by knight-666** [comment]
我的也打不开

**Comment by iso-lib** [comment]
同样的问题,,,昨晚20:00后就不运行了,,今天删了镜像从新安装也进不去web面板,,

**Comment by StoneForests** [comment]
> 同样的问题,,,昨晚20:00后就不运行了,,今天删了镜像从新安装也进不去web面板,,

我也是昨天晚上8点后就不运行了，今天重新安装后一开始进不了web面板，过个大概十几分钟就可以进去了。

**Comment by knight-666** [comment]
我重装面板了，docker容器内5678 端口都没启动

**Comment by dreamfly32** [comment]
进入docker，手动启动面板，pm2 start server.js

**Comment by lan-tianxiang** [comment]
已修复
