### ISSUE TITLE
关于终端运行第三方脚本出现的问题

### ISSUE THREAD

**Issue by wys206** [lan-tianxiang/JS_TOOL#344]
大佬，昨天由于jd.sh无效，在你更新后从新拉的JS_TOOL库，但是终端运行第三方库的脚本提示如下内容，上次搭建的记得是能够直接运行的，这次是缺少什么配置吗？
**root@jd:~/jd/panel $ thirdpard /root/jd/thirdpard/smiek2221_scripts/jd_summer_movement_help.js now

复制或覆盖 /root/jd/thirdpard/smiek2221_scripts/jd_summer_movement_help.js 到 /root/jd/scripts 下.....开始运行...

执行node
Welcome to Node.js v14.17.1.
Type ".help" for more information.
>**

**Comment by knight-666** [comment]
我的也打不开了

**Comment by sorker** [comment]
我也是

**Comment by wqdwang** [comment]
同样

**Comment by knight-666** [comment]
目前docker启动，端口没有映射，定时任务也不执行了

**Comment by knight-666** [comment]
目前docker启动，端口没有映射，定时任务也不执行了

**Comment by lan-tianxiang** [comment]
已修复

**Comment by lan-tianxiang** [comment]
@knight-666  单独发起issues我看看
