### ISSUE TITLE
面板ip更改功能

### ISSUE THREAD

**Issue by c410185** [lan-tianxiang/JS_TOOL#35]
面板ip 默认是 127.0.0.1，一般不会出错，但是在华为云中，每个服务器都有子网ip，所以公网ip:5678的方式无法访问，而之前部署flask程序的时候也出现过这种状况，把127改为华为内的子网ip就能正常访问。

自己尝试在 server.js 中加入了app.set('host','192.168.0.41'); 或者 app.listen(5678, '192.168.0.41'); 的方式，没有效果。
希望能指导一下如何修改，因为是自学，并且 js 服务端没接触过。

**Comment by lan-tianxiang** [comment]
的确，server.js默认用的是127.0.0.1

**Comment by lan-tianxiang** [comment]
你可以考虑一下 服务器安装docker之后，走docker的安装路线，这样映射出来的就是子网ip:5678了

**Comment by lan-tianxiang** [comment]
> 面板ip 默认是 127.0.0.1，一般不会出错，但是在华为云中，每个服务器都有子网ip，所以公网ip:5678的方式无法访问，而之前部署flask程序的时候也出现过这种状况，把127改为华为内的子网ip就能正常访问。
> 
> 自己尝试在 server.js 中加入了app.set('host','192.168.0.41'); 或者 app.listen(5678, '192.168.0.41'); 的方式，没有效果。
> 希望能指导一下如何修改，因为是自学，并且 js 服务端没接触过。

不过你可以先尝试一下app.listen(5678, '0.0.0.0')

**Comment by c410185** [comment]
试了一下还是不行,我试试其他办法
