### ISSUE TITLE
openwrt 无法运行

### ISSUE THREAD

**Issue by happy-peter** [lan-tianxiang/JS_TOOL#352]
![image](https://user-images.githubusercontent.com/68748434/125610851-07cc33d3-f824-4c62-b4be-a6366c7f867a.png)

已经autofix.sh repair.sh过了，都木有用，希望大神修复一下，谢谢

**Comment by lan-tianxiang** [comment]
好的，今天前修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："happy-peter ***@***.***&gt;;
发送时间：2021年7月14日(星期三) 晚上6:57
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] openwrt 无法运行 (#352)
-----------------------------------

 

 

 
已经autofix.sh repair.sh过了，都木有用，希望大神修复一下，谢谢

**Comment by lan-tianxiang** [comment]
已修复，再次使用autofix.sh

**Comment by happy-peter** [comment]
> 已修复，再次使用autofix.sh
好了，谢谢大神~
