### ISSUE TITLE
使用了容器内自动助力可是还是助力的容器外账号

### ISSUE THREAD

**Issue by qq7984225** [lan-tianxiang/JS_TOOL#36]
![image](https://user-images.githubusercontent.com/85238021/120579500-329a3600-c45a-11eb-8c00-552b2174a1d4.jpeg)docker搭建的jd。释放cookie配置好文件使用内部自动助力 可是运行脚本时显示助力的账号不是我容器内的（已经运行过脚本创建助力码![image](https://user-images.githubusercontent.com/85238021/120579510-36c65380-c45a-11eb-8c19-fbbf33213848.jpeg)

**Comment by lan-tianxiang** [comment]
前面还在看你的
![image](https://user-images.githubusercontent.com/42911023/120589945-477fc500-c46c-11eb-92ed-a5296167ca42.png)

可以把完整一点的日记发给我看一下吗

**Comment by qq7984225** [comment]
搞好了看错日志了sy😂
