### ISSUE TITLE
找不到目录下jd/.AutoConfig/Env.js的canRequest（三个文件都映射了）

### ISSUE THREAD

**Issue by bds9527** [lan-tianxiang/JS_TOOL#367]
想要增加限制的域名，请编辑目录下jd/.AutoConfig/Env.js的canRequest

**Comment by lan-tianxiang** [comment]
![image](https://user-images.githubusercontent.com/42911023/125736059-b0d7a091-b2ea-4b77-a5d9-f104d61eb7ae.png)

**Comment by lan-tianxiang** [comment]
已改变Env.js的位置到config底下了
