### ISSUE TITLE
每次更新后拉取跟新，都要手动重启一次docker

### ISSUE THREAD

**Issue by wintsa123** [lan-tianxiang/JS_TOOL#381]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [x ] Linux
- [x ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：日记查不到，每次发现不推送打开5678也打不开，然后手动重启才可以打开5678.发现是已经更新了。不知道是docker自动挂了，还是更新的缘故。

### (2) 详细日志
A：

**Comment by xx668888** [comment]
我也是 突然不能访问面板，然后重启了一下，可以访问了，不知道怎么回事

**Comment by wintsa123** [comment]
> 我也是突然不能访问面板，然后重启了一下，可以访问了，不知道怎么回事

设置内存模式为pm2会改善很多
