### ISSUE TITLE
重启之后报错Argument list too long

### ISSUE THREAD

**Issue by qq7984225** [lan-tianxiang/JS_TOOL#39]
重启打开面板时报错![image](https://user-images.githubusercontent.com/85238021/120682344-f228cf80-c4ce-11eb-8c09-554fb9084892.jpeg)

**Comment by lan-tianxiang** [comment]
收到图了，不过应该不影响面板运行吧

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："qq7984225 ***@***.***&gt;;
发送时间：2021年6月4日(星期五) 凌晨0:51
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 重启之后报错Argument list too long (#39)
-----------------------------------

 

 
重启打开面板时报错

**Comment by lan-tianxiang** [comment]
正常脚本能够运行吗

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："qq7984225 ***@***.***&gt;;
发送时间：2021年6月4日(星期五) 凌晨0:51
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 重启之后报错Argument list too long (#39)
-----------------------------------

 

 
重启打开面板时报错

**Comment by qq7984225** [comment]
z> 收到图了，不过应该不影响面板运行吧

**Comment by qq7984225** [comment]
很难受脚本不运行 但是更新任务啥的是正常的

**Comment by qq7984225** [comment]
是我cookie太多了吗？ 有56个

**Comment by lan-tianxiang** [comment]
@qq7984225   暂时没有限制cookie的数量

**Comment by lan-tianxiang** [comment]
你更新一下，我刚刚稍微改善了一下
如果还是不行的话，可以用https://github.com/lan-tianxiang/jd_shell/wiki
功能上几乎一样，同步更新

**Comment by qq7984225** [comment]
![image](https://user-images.githubusercontent.com/85238021/120741291-62633f80-c527-11eb-8437-edbf043a2be5.png)
要用哪个呢？

**Comment by lan-tianxiang** [comment]
更新是用命令 `jd update`

前面说的 还不行的话
可以把Cookie拷贝出来
然后删除这个镜像，安装
`wget -q https://gitee.com/highdimen/jd_shell/raw/v3/install_scripts/docker_install_jd.sh -O docker_install_jd.sh && chmod +x docker_install_jd.sh && bash docker_install_jd.sh`

不懂的话，你留Q，我帮你试一下

**Comment by qq7984225** [comment]
我重置了一遍然后更新好了现在还没重启过 等晚上重启一遍看看 谢谢大佬

**Comment by lan-tianxiang** [comment]
嗯，没事的ヾ(≧▽≦*)o&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "qq7984225"; 
Date: 2021年6月4日(星期五) 下午2:32
To: "lan-tianxiang/JS_TOOL"; 
Cc: "lan-tianxiang"; "Comment"; 
Subject: Re: [lan-tianxiang/JS_TOOL] 重启之后报错Argument list too long (#39)

&nbsp;


 
我重置了一遍然后更新好了现在还没重启过 等晚上重启一遍看看 谢谢大佬

**Comment by qq7984225** [comment]
哦对了我的QQ7984225

**Comment by qq7984225** [comment]
还有些小问题要和你反馈下

**Comment by qq7984225** [comment]
![阿萨大大](https://user-images.githubusercontent.com/85238021/120786076-65c6ed00-c560-11eb-887c-2acb045d9069.png)
docker restart jd 后又启动不了了大佬

**Comment by qq7984225** [comment]
![image](https://user-images.githubusercontent.com/85238021/120788026-93149a80-c562-11eb-8a7a-2f1ca31ee7a0.png)
这个行数上限应该可以增加的把

**Comment by lan-tianxiang** [comment]
几天前修复了，忘了通知
