### ISSUE TITLE
脚本定时运行配置文件crontab.list不定时重置（重置）

### ISSUE THREAD

**Issue by zdanlan** [lan-tianxiang/JS_TOOL#4]
crontab.list文件不定时复原成初始状态（下图这样只有22行）
![@_1TWHDI(2~N$DV~H@149_E](https://user-images.githubusercontent.com/50987143/114584857-a0757d00-9cb5-11eb-8e87-f874ffefe276.png)

重新用bash jd.sh update  更新脚本后会恢复（下图这样）
![@TASCBX{J9H1GZN4TE}AZMJ](https://user-images.githubusercontent.com/50987143/114585003-cac73a80-9cb5-11eb-8b76-30392993e2da.png)

但是过一段时间又会恢复成初始状态，导致后续的定时任务全部停止执行。

**Comment by zdanlan** [comment]
版本
## Version: v0.0.4
## Date: 2021-04-12

**Comment by lan-tianxiang** [comment]
收到

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："zdanlan ***@***.***&gt;;
发送时间：2021年4月14日(星期三) 凌晨0:12
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 脚本定时运行配置文件crontab.list不定时重置（重置） (#4)
-----------------------------------

 

 
crontab.list文件不定时复原成初始状态（下图这样只有22行）
 
 
重新用bash jd.sh update  更新脚本后会恢复（下图这样）
 
 
但是过一段时间又会恢复成初始状态，导致后续的定时任务全部停止执行。

**Comment by ryan016** [comment]
一样的问题，我是所有的配置信息都没了，面板上的信息全都空白了。

**Comment by Jackfinal** [comment]
我的全部为空，更新了，也为空

**Comment by Jackfinal** [comment]
[https://user-images.githubusercontent.com/50987143/114585003-cac73a80-9cb5-11eb-8b76-30392993e2da.png](url)

这个清单，怎么没有了。。。找不到了

**Comment by lan-tianxiang** [comment]
新版有点问题，先暂时回退旧版吧，不好意思

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Jackfinal ***@***.***&gt;;
发送时间：2021年4月18日(星期天) 上午7:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 脚本定时运行配置文件crontab.list不定时重置（重置） (#4)
-----------------------------------

 

 
https://user-images.githubusercontent.com/50987143/114585003-cac73a80-9cb5-11eb-8b76-30392993e2da.png
 
这个清单，怎么没有了。。。找不到了

**Comment by Jackfinal** [comment]
@lan-tianxiang  大概什么时候能解决crontab的问题，我现在晚上就会没有了

**Comment by Jackfinal** [comment]
@lan-tianxiang  这个问题 咋回事呢，crontab 就会为空，啥也没有，需要自己手动加上才会执行。。。。。那个文件控制这个。。。。

**Comment by Luolin0826** [comment]
还是会发生这个问题，请问是如何解决的呢？

**Comment by lan-tianxiang** [comment]
@Luolin0826   提供一下截图，谢谢

**Comment by Luolin0826** [comment]
> @Luolin0826 提供一下截图，谢谢
就是程序的定时页面，每天都会自动重置清空1-2次，每次都需要手动添加定时配置文件上去。
![image](https://user-images.githubusercontent.com/58615864/120328440-63c11c00-c31d-11eb-9b93-356875da82ed.png)
更新脚本会提示新增任务成功，但实际上定时的配置文件还是空的。
![image](https://user-images.githubusercontent.com/58615864/120328797-c3b7c280-c31d-11eb-9e9d-1324fe4b520f.png)
只有一键修复脚本可以恢复，但是过段时间又被清空了，大概半天左右。

**Comment by lan-tianxiang** [comment]
> > @Luolin0826 提供一下截图，谢谢
> > 就是程序的定时页面，每天都会自动重置清空1-2次，每次都需要手动添加定时配置文件上去。
> > ![image](https://user-images.githubusercontent.com/58615864/120328440-63c11c00-c31d-11eb-9b93-356875da82ed.png)
> > 更新脚本会提示新增任务成功，但实际上定时的配置文件还是空的。
> > ![image](https://user-images.githubusercontent.com/58615864/120328797-c3b7c280-c31d-11eb-9e9d-1324fe4b520f.png)
> > 只有一键修复脚本可以恢复，但是过段时间又被清空了，大概半天左右。

@Luolin0826  不应该呀，安装方式是docker还是

**Comment by lan-tianxiang** [comment]
使用docker安装试一下
```
wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/Qunhui_docker_install_jd.sh -O docker_install_jd.sh && chmod +x docker_install_jd.sh && bash docker_install_jd.sh
```

**Comment by lan-tianxiang** [comment]
关键这个问题上个版本已经修复了

**Comment by Luolin0826** [comment]
> 关键这个问题上个版本已经
好的 我去试试

**Comment by lan-tianxiang** [comment]
怎么样了😢

**Comment by Luolin0826** [comment]
> 怎么样了😢

docker可以啦，没有自动复原。我想了一下可能是因为最初的时候我安装的是低版本的，然后由低版本升级上来的，会不会是因为这个原因导致的。问题已经解决了，谢谢啦！

**Comment by lan-tianxiang** [comment]
好勒，那就好😋 😋&nbsp;

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："洛林 ***@***.***&gt;;
发送时间：2021年6月2日(星期三) 上午10:06
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 脚本定时运行配置文件crontab.list不定时重置（重置） (#4)
-----------------------------------

 

  
怎么样了
  
docker可以啦，没有自动复原。我想了一下可能是因为最初的时候我安装的是低版本的，然后由低版本升级上来的，会不会是因为这个原因导致的。问题已经解决了，谢谢啦！
