### ISSUE TITLE
大佬看下，更新有文件未找到，定时任务也无法执行，手动执行没问题

### ISSUE THREAD

**Issue by leeailee77** [lan-tianxiang/JS_TOOL#40]
![Screenshot_2021-06-04-09-24-05-956_com.termux.jpg](https://user-images.githubusercontent.com/80807232/120731729-cf37f480-c4a9-11eb-9bd0-e0540a796f95.jpg)

**Comment by lan-tianxiang** [comment]
你使用的是v3版本的，要用v3命令的噢


看一下wiki里面有说明的，termux要输入一条额外的命令才能自动运行定时任务的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："leeailee77 ***@***.***&gt;;
发送时间：2021年6月4日(星期五) 上午9:27
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 大佬看下，更新有文件未找到，定时任务也无法执行，手动执行没问题 (#40)
-----------------------------------

**Comment by leeailee77** [comment]
![Screenshot_2021-06-04-13-17-16-269_com.termux.jpg](https://user-images.githubusercontent.com/80807232/120749472-4bdacb00-c4ca-11eb-9d4a-d70c60b7af03.jpg)
感谢大佬回复，前图是utermux安装的ubuntu系统下执行的，这图是安卓端执行的，刚安装的，还是无法更新.

**Comment by lan-tianxiang** [comment]
你看一下这里
![image](https://user-images.githubusercontent.com/42911023/120750887-ac552100-c539-11eb-8ffe-46b544836d22.png)

https://github.com/lan-tianxiang/jd_shell/wiki/Instruction

更新命令 `bash git_pull.sh`

**Comment by lan-tianxiang** [comment]
utermux安装的ubuntu系统的话，自动执行定时还要加一句 `service cron start`
