### ISSUE TITLE
127.0.0.1:5678无法访问

### ISSUE THREAD

**Issue by Gong-Zhang** [lan-tianxiang/JS_TOOL#41]
环境是腾讯云centos7 面板启动成功，但是输入默认地址访问不到，如下图所示，请大佬帮忙看下啥问题
![image](https://user-images.githubusercontent.com/38037570/120737232-44461100-c520-11eb-8278-e71b934db8fb.png)

**Comment by lan-tianxiang** [comment]
你先看一下
```
cd panel
node server.js
```

**Comment by lan-tianxiang** [comment]
我知道原因了，一般是nodejs的版本问题

**Comment by Gong-Zhang** [comment]
![image](https://user-images.githubusercontent.com/38037570/120738022-b703bc00-c521-11eb-9b75-6c72c15a6b7c.png)

**Comment by lan-tianxiang** [comment]
是的

**Comment by Gong-Zhang** [comment]
我现在是6.17.1，需要什么版本呀

**Comment by lan-tianxiang** [comment]
方法一：升级到最新版本https://blog.csdn.net/guzhao593/article/details/81712016

方法二：
安装docker
```
curl -fsSL https://get.docker.com | bash -s docker --mirror aliyun
```
部署脚本
```
wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/Qunhui_docker_install_jd.sh -O docker_install_jd.sh && chmod +x docker_install_jd.sh && bash docker_install_jd.sh
```

**Comment by Gong-Zhang** [comment]
好的我去试试，多谢

**Comment by lan-tianxiang** [comment]
没事

**Comment by i-bugmaker** [comment]
![image](https://user-images.githubusercontent.com/26687639/121362933-153cfe80-c969-11eb-9356-ebc90244f71b.png)
不行呀
