### ISSUE TITLE
之前v3，定时任务正常运行，今天改a1，所有定时不能运行，改pm2也一样，大神，求解

### ISSUE THREAD

**Issue by wjj982** [lan-tianxiang/JS_TOOL#42]

**Comment by lan-tianxiang** [comment]
说一下安装方式

**Comment by wjj982** [comment]
wget -q https://gitee.com/highdimen/js_tool/raw/A1/resource/install_scripts/linux_install_jd.sh -O linux_install_jd.sh && chmod +x linux_install_jd.sh && bash linux_install_jd.sh

**Comment by wjj982** [comment]
安装utermux后执行如上命令，更新脚本后执行挂机，不能执行定时任务，
安卓10，之前v3时安装后挂机，能正常执行定时任务，
我在/storage/emulated/0/xinhao下操作的

**Comment by wjj982** [comment]
v3能马上看到运行日志，a1无反应

**Comment by wjj982** [comment]
v3不能并发，所以想换'a1

**Comment by lan-tianxiang** [comment]
好的，懂了，你加上一句

**Comment by lan-tianxiang** [comment]
utermux安装的ubuntu系统的话，自动执行定时还要加一句 `service cron start`

**Comment by lan-tianxiang** [comment]
termux的话，就加上 `crond -ipP`
希望能帮到你

**Comment by lan-tianxiang** [comment]
#40

**Comment by wjj982** [comment]
都加了，v3无任何问题，a1不行，但有时有如下提示，
cp: cannot stat '/data/data/com.termux/files/home/sample/config.sh.sample': No such file or directory
cp: cannot stat '/data/data/com.termux/files/home/sample/cookie.sh.sample': No such file or directory
cp: cannot stat '/data/data/com.termux/files/home/sample/crontab.list.sample': No such file or directory
Can't open /data/data/com.termux/files/home/config/crontab.list: No such file or directory.

命令输入错误...

/data/data/com.termux/files/usr/bin/jd: line 1332: cd: /data/data/com.termux/files/home/scripts: No such file or directory

**Comment by lan-tianxiang** [comment]
> 都加了，v3无任何问题，a1不行，但有时有如下提示，
> cp: cannot stat '/data/data/com.termux/files/home/sample/config.sh.sample': No such file or directory
> cp: cannot stat '/data/data/com.termux/files/home/sample/cookie.sh.sample': No such file or directory
> cp: cannot stat '/data/data/com.termux/files/home/sample/crontab.list.sample': No such file or directory
> Can't open /data/data/com.termux/files/home/config/crontab.list: No such file or directory.
> 
> 命令输入错误...
> 
> /data/data/com.termux/files/usr/bin/jd: line 1332: cd: /data/data/com.termux/files/home/scripts: No such file or directory



这个提示是脚本目录判断错了，怎么会出现这个错误呢，奇怪了。
一般脚本都安装在 ~jd里面，也就是/data/data/com.termux/files/home/jd里面

**Comment by lan-tianxiang** [comment]
有试过清除termux的软件数据和缓存，然后换源、再运行一键安装脚本吗

**Comment by wjj982** [comment]
是的，我马上换v3，一切正常，a1就不行了，重装utermux这些也试了，一样的问题，
'a1只有手动正常

**Comment by wjj982** [comment]
源也北外，三个源都试了

**Comment by lan-tianxiang** [comment]
你试试这样

**Comment by lan-tianxiang** [comment]
把jd目录里面的内容全部复制到jd的同级目录中

**Comment by lan-tianxiang** [comment]
打开软件，输入
```
cd jd
mv -f * ../
mv -f .* ../
cd ../
bash jd.sh update
```

**Comment by wjj982** [comment]
我q178716982，就方便加下 运行如下，
您的操作系统为：Android 架构：aarch64
.../0/xinhaoa1 $ cd jd
.../xinhaoa1/jd $ mv -rf * ../
mv: invalid option -- 'r'
Try 'mv --help' for more information.
.../xinhaoa1/jd $ cd ..
.../0/xinhaoa1 $ cd jd
.../xinhaoa1/jd $ mv -rf * ../
mv: invalid option -- 'r'
Try 'mv --help' for more information.
.../xinhaoa1/jd $ mv -rf .* ../
mv: invalid option -- 'r'
Try 'mv --help' for more information.
.../xinhaoa1/jd $ cd ../
.../0/xinhaoa1 $ bash jd.sh update

--------------------------------------------------------------

系统时间：2021-06-05 14:55:45

脚本根目录：/storage/emulated/0/xinhaoA1

jd_scripts目录：/storage/emulated/0/xinhaoA1/scripts

thirdpard脚本目录：/storage/emulated/0/xinhaoA1/thirdpard

--------------------------------------------------------------

fatal: not in a git directory
开始更新仓库：/storage/emulated/0/xinhaoA1

fatal: not a git repository (or any parent up to mount point /storage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /storage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /storage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

更新/storage/emulated/0/xinhaoA1失败，请检查原因...

开始更新仓库：/storage/emulated/0/xinhaoA1/scripts

Fetching origin
HEAD is now at bae208f8 update
Already up to date.

更新/storage/emulated/0/xinhaoA1/scripts成功...

检测到有失效的定时任务：

jd_618redpacket
jd_mcxhd_brandcity

您的操作系统为：Android 架构：aarch64

**Comment by lan-tianxiang** [comment]
好，我稍后加你

**Comment by lan-tianxiang** [comment]
你按照上面命令再输运行一次试试

**Comment by lan-tianxiang** [comment]
```
cd jd
mv -f * ../
mv -f .* ../
cd ../
bash jd.sh update
```

**Comment by wjj982** [comment]
还是不行，
