### ISSUE TITLE
API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by Kirbyouo** [lan-tianxiang/JS_TOOL#43]
"getaddrinfo ENOTFOUND share.turinglabs.net share.turinglabs.net:80"
闪购盲盒 API请求失败，请检查网路重试

在手动执行某些任务时会出现以上错误。

**Comment by lan-tianxiang** [comment]
这个脚本文件的作者内置的助力码库的连接问题

**Comment by lan-tianxiang** [comment]
可能和网络有关，我这边市场也会出现，不过不会影响整体脚本的运行

**Comment by IfItWereU** [comment]
明白了，我这个是在华为云服务器上运行的，谢谢作者。

**Comment by Kirbyouo** [comment]
> 可能和网络有关，我这边市场也会出现，不过不会影响整体脚本的运行

明白了，我这个是在华为云服务器上运行的，谢谢作者。

**Comment by lan-tianxiang** [comment]
没事的，不用谢
