### ISSUE TITLE
宠汪汪任务怎么不执行

### ISSUE THREAD

**Issue by yuezhengchao** [lan-tianxiang/JS_TOOL#46]
![image](https://user-images.githubusercontent.com/77090717/120892012-8e251900-c63e-11eb-9eb6-03de69518f36.png)

**Comment by lan-tianxiang** [comment]
更新一下脚本就行了，昨晚修复了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yuezhengchao ***@***.***&gt;;
发送时间：2021年6月5日(星期六) 晚上8:43
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 宠汪汪任务怎么不执行 (#46)
-----------------------------------

**Comment by yuezhengchao** [comment]
还是不行，提示以下错误：
TypeError: $.getPetTaskConfigRes.datas is not iterable
    at petTask (/root/jd/scripts/jd_joy.js:230:42)
    at jdJoy (/root/jd/scripts/jd_joy.js:111:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by lan-tianxiang** [comment]
再更新一下，修复了bug

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yuezhengchao ***@***.***&gt;;
发送时间：2021年6月5日(星期六) 晚上10:23
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 宠汪汪任务怎么不执行 (#46)
-----------------------------------

 

 
还是不行，提示以下错误：
 TypeError: $.getPetTaskConfigRes.datas is not iterable
 at petTask (/root/jd/scripts/jd_joy.js:230:42)
 at jdJoy (/root/jd/scripts/jd_joy.js:111:9)
 at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by yuezhengchao** [comment]
已解决，谢谢您

**Comment by lan-tianxiang** [comment]
没事的，不用谢

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yuezhengchao ***@***.***&gt;;
发送时间：2021年6月6日(星期天) 中午12:06
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 宠汪汪任务怎么不执行 (#46)
-----------------------------------

 

 
已解决，谢谢您
