### ISSUE TITLE
添加其他JS库无法自动添加定时任务

### ISSUE THREAD

**Issue by zkhaoo** [lan-tianxiang/JS_TOOL#48]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
好的，方便给一下仓库地址测试一下吗

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："zkhaoo ***@***.***&gt;;
发送时间：2021年6月6日(星期天) 凌晨4:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 添加其他JS库无法自动添加定时任务 (#48)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 
(2) 详细日志
 
A：

**Comment by xxp2277** [comment]
我添加的几个第三方库还好，自从https://github.com/lan-tianxiang/JS_TOOL/issues/28#issue-903726001 问题修复后就没出现问题了。

**Comment by zkhaoo** [comment]
> 好的，方便给一下仓库地址测试一下吗
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："zkhaoo ***@***.***&gt;; 发送时间：2021年6月6日(星期天) 凌晨4:56 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] 添加其他JS库无法自动添加定时任务 (#48) ----------------------------------- 1.关于你要提交的问题 Q：是否搜索了issue（包括已关闭的issue） 没有类似的issue Q：是否阅读了常见问题 已阅读常见问题，未找到相关说明 Q：是否仔细阅读了教程 已仔细阅读教程 2. 使用什么平台？ Linux Docker 3. 是否用一键脚本部署的？ Yes No 4. 有没有试过用修复脚本来修复过？ Yes No 5. 详细叙述 (1) 具体问题 A： (2) 详细日志 A： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
拉取都成功，就是没有定时任务



https://github.com/hyzaw/scripts.git "ddo_"
https://github.com/Ariszy/Private-Script.git "JD"	
https://github.com/zooPanda/zoo.git "zoo"
https://github.com/panghu999/panghu.git "jd_"
https://github.com/Wenmoux/scripts.git "jd"
https://github.com/passerby-b/JDDJ.git "jddj_" "scf_test_event" "jddj_cookie"
https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"
https://github.com/longzhuzhu/nianyu.git "qx" “main”
https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

**Comment by zkhaoo** [comment]
> 好的，方便给一下仓库地址测试一下吗
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："zkhaoo ***@***.***&gt;; 发送时间：2021年6月6日(星期天) 凌晨4:56 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] 添加其他JS库无法自动添加定时任务 (#48) ----------------------------------- 1.关于你要提交的问题 Q：是否搜索了issue（包括已关闭的issue） 没有类似的issue Q：是否阅读了常见问题 已阅读常见问题，未找到相关说明 Q：是否仔细阅读了教程 已仔细阅读教程 2. 使用什么平台？ Linux Docker 3. 是否用一键脚本部署的？ Yes No 4. 有没有试过用修复脚本来修复过？ Yes No 5. 详细叙述 (1) 具体问题 A： (2) 详细日志 A： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/60925389/121238558-ce98c700-c8ca-11eb-84bd-08f1dac936ad.png)
![image](https://user-images.githubusercontent.com/60925389/121238592-d9535c00-c8ca-11eb-8ccb-44cb98319a59.png)

**Comment by lan-tianxiang** [comment]
已修复，请打开
![image](https://user-images.githubusercontent.com/42911023/121654207-0f156200-cad0-11eb-8cbc-ec6ecdb7d276.png)
