### ISSUE TITLE
关于挂机程序自启动

### ISSUE THREAD

**Issue by dada-liang** [lan-tianxiang/JS_TOOL#49]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：A1一键部署无法设置 挂机程序是否自启动，建议增加按钮设置

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
好的，没问题

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："dada-liang ***@***.***&gt;;
发送时间：2021年6月6日(星期天) 中午12:14
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 关于挂机程序自启动 (#49)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：A1一键部署无法设置 挂机程序是否自启动，建议增加按钮设置
 
(2) 详细日志
 
A：
