### ISSUE TITLE
（作者更新了，好耶）无法扫码获取cookie的来看看（修改UA）

### ISSUE THREAD

**Issue by doublekill02** [lan-tianxiang/JS_TOOL#490]
### Discussed in https://github.com/lan-tianxiang/JS_TOOL/discussions/489

<div type='discussions-op-text'>

<sup>Originally posted by **doublekill02** August 10, 2021</sup>
🎁配置设定→130行 export JD_USER_AGENT=  将UA换一下即可远程扫码

😚如何获取UA？
😊抓包

😎软件：Android小黄鸟👍链接：https://pan.baidu.com/s/1zYcGfMfcjF38oh0_nzK5Kg  提取码：ck03
                IOS : thor

😉抓包的时候不要看200的数据，看302、304的

✔UA例子：（UA很长，你忍一下）jdapp;andro*****0.6;****************35*********del/P*******ddressid/83******61;aid/1*0d**9a5*********0-0***********000*0000;os*Bu*il5;*pa**r*r/**********ufv/1;M*********illa/**0 ( M*******/*6.2* 5710 M*********ari/5*********

😭CONTRAST: 抓到 okhttp/3.12.1;jdmall;android;version/10.6;build/852;screen/1080x222;os/;network/wifi;
                                 Dalvik/2.1.0 (Linux; ; Android 10;0 Build/HUAWEI)这种就不是那种UA，你懂我意思的。
     
❣希望作者能维护一下❣</div>

**Comment by dreamfly32** [comment]
测试过不行，跟ip有关系，需要在同一个局域网

**Comment by dreamfly32** [comment]
可能跟vps有关，估计jd检测了ip，本地搭建，流量扫码没问题

**Comment by doublekill02** [comment]
> 测试过不行，跟ip有关系，需要在同一个局域网

我刚和朋友测试过，可以的。。。相隔几个市。。。我这个之前试过不行就改用了外带一个远程扫码（无db文件的），现在听闻有人改了UA可以，所以试了下，顺便简单写写给小白白们看。

**Comment by shanhai2333** [comment]
更新了，可以了获取cookie了
