### ISSUE TITLE
配置了多个Cookie后运行脚本提示 用户未授权

### ISSUE THREAD

**Issue by yu1chaofan** [lan-tianxiang/JS_TOOL#5]
提示:您的第1个账号：jd_7179cc8****** 未经授权

**Comment by xian1632006** [comment]
更新就好了

**Comment by jdyuxu** [comment]
是不是没进那个Q群以后的版本就不能用了？

**Comment by lan-tianxiang** [comment]
不会的，放心，永久免费

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："jdyuxu ***@***.***&gt;;
发送时间：2021年4月17日(星期六) 中午11:11
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 配置了多个Cookie后运行脚本提示 用户未授权 (#5)
-----------------------------------

 

 
是不是没进那个Q群以后的版本就不能用了？

**Comment by jdyuxu** [comment]
大佬，加了几次Q群，无奈没有通过，担心没有授权，一直没敢更新到这个版本，今天再加看到已经满员，我怎么样才能得到这个新版的授权而用上新版本？谢谢！

**Comment by bigmax706** [comment]
> 不会的，放心，永久免费
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："jdyuxu ***@***.***&gt;; 发送时间：2021年4月17日(星期六) 中午11:11 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 配置了多个Cookie后运行脚本提示 用户未授权 (#5) ----------------------------------- 是不是没进那个Q群以后的版本就不能用了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，群满了，进不去
