### ISSUE TITLE
jd update或者面板中手动执行更新脚本文件导致面板对话失效，必须重新登录

### ISSUE THREAD

**Issue by xxp2277** [lan-tianxiang/JS_TOOL#50]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

-[x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：jd update或者面板中手动执行更新脚本文件导致面板对话失效，必须重新登录。如果是在面板中的手动执行那里点击更新脚本文件，因为面板对话过期，导致无法显示出更新脚本的日志。我记得以前不是这样的，望修复。

### (2) 详细日志
A：
无

**Comment by lan-tianxiang** [comment]
好
