### ISSUE TITLE
开始克隆仓库 https://gitee.com/highdimen/clone_scripts.git 到 /root/jd/scripts   更新/root/jd/scripts失败，请检查原因...,另外最重要的并发执行别取消了，这个功能我认为很好。

### ISSUE THREAD

**Issue by wzal2008** [lan-tianxiang/JS_TOOL#51]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
好，知道了。
开始克隆仓库失败，可能是因为gitee对同一秒钟连接仓库的数量做了限制，再更新一下就行了

**Comment by xxp2277** [comment]
面板手动运行，默认有说明：
jd jd_xxx fast     # 急速运行jd_xxx脚本
加fast参数就是并发。。。

**Comment by wzal2008** [comment]
我说的是jd runall_fast这条命令，这个跑下来，一般20分钟不到，全部跑完。

**Comment by lan-tianxiang** [comment]
> 我说的是jd runall_fast这条命令，这个跑下来，一般20分钟不到，全部跑完。

@wzal2008   去掉是因为总是有小白运行了卡机，老是跑过来问我，哈哈哈

**Comment by lan-tianxiang** [comment]
都写了谨慎运行的😣

**Comment by wzal2008** [comment]
大佬还是加上这功能吧？我的机子跑完没问题。

**Comment by lan-tianxiang** [comment]
@wzal2008  加上了

**Comment by wzal2008** [comment]
刚刚运行jd runall3 和jd runall2还是脚本依次运行，大佬麻烦再看看。

**Comment by lan-tianxiang** [comment]
好

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："wzal2008 ***@***.***&gt;;
发送时间：2021年6月8日(星期二) 上午8:49
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 开始克隆仓库 https://gitee.com/highdimen/clone_scripts.git 到 /root/jd/scripts   更新/root/jd/scripts失败，请检查原因...,另外最重要的并发执行别取消了，这个功能我认为很好。 (#51)
-----------------------------------

 

 
刚刚运行jd runall3 和jd runall2还是脚本依次运行，大佬麻烦再看看。
