### ISSUE TITLE
关于第三方库的同名脚本是否覆盖运行的问题

### ISSUE THREAD

**Issue by xxp2277** [lan-tianxiang/JS_TOOL#52]
增加第三方库后，如果第三方库里和默认的jd scripts库存在相同的脚本，默认不会复制到scripts下去执行，而是直接执行scripts下的文件（手动运行的日志附后）。
建议：能否增加个开关，实现自定义是否覆盖运行（1，保持现状，不覆盖；2，强制覆盖运行；3，智能判断是否覆盖，读取脚本文件的最后更新日期，优先运行最近更新的，判断条件是，a、优先读取脚本文件的Last Modified time字段日期，b、若脚本内没有上述字段，则读取文件最后修改日期）。
ps：上述文件最后修改时间好像会因为从第三方库拉取的原因导致时间为最后一次jd update的时间，不知道有没有办法解决这个问题。

手动运行日志：
root@jd:~/jd/scripts $ thirdpard /root/jd/thirdpard/inoyna11_jd28/jd_joy_reward.js now

jd_scripts项目存在同名文件jd_joy_reward.js，不复制/root/jd/thirdpard/inoyna11_jd28/jd_joy_reward.js，直接执行/root/jd/scripts/jd_joy_reward.js ...

**Comment by lan-tianxiang** [comment]
行的，确实应该增加一个选项。
不过说个题外话，jd_joy系列的文件都已经修复了，可以正常运行，不需要从第三方库拉取☺

**Comment by xxp2277** [comment]
谢谢告知。

**Comment by lan-tianxiang** [comment]
已修复，请打开
![image](https://user-images.githubusercontent.com/42911023/121654207-0f156200-cad0-11eb-8cbc-ec6ecdb7d276.png)
@xxp2277 
已经增加覆盖功能

**Comment by xxp2277** [comment]
给大佬点赞！！！
