### ISSUE TITLE
仓库检查不到更新了

### ISSUE THREAD

**Issue by happyskey** [lan-tianxiang/JS_TOOL#53]
开始更新仓库：/root/jd

Fetching origin
HEAD is now at 410c5c0 更新于 06-04 22:54
Already up to date.

更新成功...

开始更新仓库：/root/jd/scripts

Fetching origin
HEAD is now at f168bfb7 update
Already up to date.

更新/root/jd/scripts成功...

**Comment by lan-tianxiang** [comment]
小兄弟，这个是运行正常的意思

**Comment by lanny520** [comment]
> 小兄弟，这个是运行正常的意思

大佬，我也是这个问题，我是N1里docker装的，安装的时候把路径改到了opt/docker/jd 里面，使用都正常，就是更新不行，更新默认的是root/jd ，这要怎么办呀？
