### ISSUE TITLE
A1版本，添加第三方库，不能没有成功。

### ISSUE THREAD

**Issue by q345665092** [lan-tianxiang/JS_TOOL#55]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：A1版本，添加第三方库，没有成功。最开始安装容器时更改过配置文件的绝对路径，改成了/mnt/mmcblk2p4/jd-docker

### (2) 详细日志
开始更新仓库：/root/jd

Fetching origin
HEAD is now at 02503a0 更新于 06-06 05:49
Already up to date.

更新成功...

开始更新仓库：/root/jd/scripts

Fetching origin
HEAD is now at ff59f8c7 修复宠汪汪赛跑
Already up to date.

更新/root/jd/scripts成功...

--------------------------------------------------------------

开始更新仓库：/root/jd/thirdpard/zooPanda_zoo

Fetching origin
HEAD is now at bd7f5e6 Update zooJointeam01.js
Already up to date.

更新/root/jd/thirdpard/zooPanda_zoo成功...

jd.sh: line 752: cd: /root/jd/thirdpard/zooPanda_zoo/blob/dev: No such file or directory
检测到有新的定时任务：

/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_big_winner.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_cash.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_dreamFactory.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_feedPets.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_reward.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_xtg_help.js
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_zoo.js

您的操作系统为：UnKnow 架构：aarch64

**Comment by lan-tianxiang** [comment]
好的，我测试一下

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："q345665092 ***@***.***&gt;;
发送时间：2021年6月7日(星期一) 凌晨3:31
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] A1版本，添加第三方库，不能没有成功。 (#55)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
[x ] 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
[x ] 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
[x ] Docker
  
3. 是否用一键脚本部署的？
  
[x ] Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
[x ] Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：A1版本，添加第三方库，没有成功。最开始安装容器时更改过配置文件的绝对路径，改成了/mnt/mmcblk2p4/jd-docker
 
(2) 详细日志
 
开始更新仓库：/root/jd
 
Fetching origin
 HEAD is now at 02503a0 更新于 06-06 05:49
 Already up to date.
 
更新成功...
 
开始更新仓库：/root/jd/scripts
 
Fetching origin
 HEAD is now at ff59f8c7 修复宠汪汪赛跑
 Already up to date.
 
更新/root/jd/scripts成功...
 
 
开始更新仓库：/root/jd/thirdpard/zooPanda_zoo
 
Fetching origin
 HEAD is now at bd7f5e6 Update zooJointeam01.js
 Already up to date.
 
更新/root/jd/thirdpard/zooPanda_zoo成功...
 
jd.sh: line 752: cd: /root/jd/thirdpard/zooPanda_zoo/blob/dev: No such file or directory
 检测到有新的定时任务：
 
/root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_big_winner.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_cash.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_dreamFactory.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_feedPets.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_reward.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_xtg_help.js
 /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_zoo.js
 
您的操作系统为：UnKnow 架构：aarch64

**Comment by q345665092** [comment]
> 好的，我测试一下
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："q345665092 ***@***.***&gt;; 发送时间：2021年6月7日(星期一) 凌晨3:31 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] A1版本，添加第三方库，不能没有成功。 (#55) ----------------------------------- 1.关于你要提交的问题 Q：是否搜索了issue（包括已关闭的issue） 没有类似的issue Q：是否阅读了常见问题 [x ] 已阅读常见问题，未找到相关说明 Q：是否仔细阅读了教程 [x ] 已仔细阅读教程 2. 使用什么平台？ Linux [x ] Docker 3. 是否用一键脚本部署的？ [x ] Yes No 4. 有没有试过用修复脚本来修复过？ [x ] Yes No 5. 详细叙述 (1) 具体问题 A：A1版本，添加第三方库，没有成功。最开始安装容器时更改过配置文件的绝对路径，改成了/mnt/mmcblk2p4/jd-docker (2) 详细日志 开始更新仓库：/root/jd Fetching origin HEAD is now at [02503a0](https://github.com/lan-tianxiang/JS_TOOL/commit/02503a0e4e46063bd3992393b44c93d714ed1cb1) 更新于 06-06 05:49 Already up to date. 更新成功... 开始更新仓库：/root/jd/scripts Fetching origin HEAD is now at ff59f8c7 修复宠汪汪赛跑 Already up to date. 更新/root/jd/scripts成功... 开始更新仓库：/root/jd/thirdpard/zooPanda_zoo Fetching origin HEAD is now at bd7f5e6 Update zooJointeam01.js Already up to date. 更新/root/jd/thirdpard/zooPanda_zoo成功... jd.sh: line 752: cd: /root/jd/thirdpard/zooPanda_zoo/blob/dev: No such file or directory 检测到有新的定时任务： /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_big_winner.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_cash.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_dreamFactory.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_feedPets.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_reward.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_xtg_help.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_zoo.js 您的操作系统为：UnKnow 架构：aarch64 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬

**Comment by q345665092** [comment]
感谢大佬

**Comment by q345665092** [comment]
> 好的，我测试一下
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："q345665092 ***@***.***&gt;; 发送时间：2021年6月7日(星期一) 凌晨3:31 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[lan-tianxiang/JS_TOOL] A1版本，添加第三方库，不能没有成功。 (#55) ----------------------------------- 1.关于你要提交的问题 Q：是否搜索了issue（包括已关闭的issue） 没有类似的issue Q：是否阅读了常见问题 [x ] 已阅读常见问题，未找到相关说明 Q：是否仔细阅读了教程 [x ] 已仔细阅读教程 2. 使用什么平台？ Linux [x ] Docker 3. 是否用一键脚本部署的？ [x ] Yes No 4. 有没有试过用修复脚本来修复过？ [x ] Yes No 5. 详细叙述 (1) 具体问题 A：A1版本，添加第三方库，没有成功。最开始安装容器时更改过配置文件的绝对路径，改成了/mnt/mmcblk2p4/jd-docker (2) 详细日志 开始更新仓库：/root/jd Fetching origin HEAD is now at [02503a0](https://github.com/lan-tianxiang/JS_TOOL/commit/02503a0e4e46063bd3992393b44c93d714ed1cb1) 更新于 06-06 05:49 Already up to date. 更新成功... 开始更新仓库：/root/jd/scripts Fetching origin HEAD is now at ff59f8c7 修复宠汪汪赛跑 Already up to date. 更新/root/jd/scripts成功... 开始更新仓库：/root/jd/thirdpard/zooPanda_zoo Fetching origin HEAD is now at bd7f5e6 Update zooJointeam01.js Already up to date. 更新/root/jd/thirdpard/zooPanda_zoo成功... jd.sh: line 752: cd: /root/jd/thirdpard/zooPanda_zoo/blob/dev: No such file or directory 检测到有新的定时任务： /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_big_winner.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_cash.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_dreamFactory.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_feedPets.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_joy_reward.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_xtg_help.js /root/jd/thirdpard/zooPanda_zoo/blob/dev/jd_zoo.js 您的操作系统为：UnKnow 架构：aarch64 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬

**Comment by lan-tianxiang** [comment]
已修复，请打开
![image](https://user-images.githubusercontent.com/42911023/121654207-0f156200-cad0-11eb-8cbc-ec6ecdb7d276.png)
