### ISSUE TITLE
安装js_tools之后会清除我原有的cron定时任务

### ISSUE THREAD

**Issue by kettly1260** [lan-tianxiang/JS_TOOL#56]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [x] No

### (1) 具体问题
A：安装js_tools之后会清除我原有的cron定时任务
安装之后我发现我原有的定时任务没有按时运行，检查后发现我原有的cron任务被清除了，重新加入之后依旧会被覆盖。

**Comment by lan-tianxiang** [comment]
试试在面板内，定时设定中的自定义区域添加原来的cron

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："kettly1260 ***@***.***&gt;;
发送时间：2021年6月7日(星期一) 上午10:58
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 安装js_tools之后会清除我原有的cron定时任务 (#56)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：安装js_tools之后会清除我原有的cron定时任务
 安装之后我发现我原有的定时任务没有按时运行，检查后发现我原有的cron任务被清除了，重新加入之后依旧会被覆盖。

**Comment by kettly1260** [comment]
@lan-tianxiang 也就只能从面板添加。但是我原来的定时任务都丢失了。这种覆盖性安装感觉不妥，希望可以解决这个问题。

**Comment by xxp2277** [comment]
> @lan-tianxiang 也就只能从面板添加。但是我原来的定时任务都丢失了。这种覆盖性安装感觉不妥，希望可以解决这个问题。

第15行左右# DIY任务区域，自定义的定时任务添加到这里不会被覆盖。
这个定时任务的文件肯定要随第三方脚本库的增减自动添加或者删除任务的。或者你有什么更巧妙的方法来实现？

**Comment by lan-tianxiang** [comment]
@kettly1260    旧定时文件有备份的

**Comment by lan-tianxiang** [comment]
@kettly1260  关键是本来有过就定时自动添加。容易造成混乱，我在部署里面加一下提示

**Comment by kettly1260** [comment]
@lan-tianxiang @xxp2277 可以添加一个不同的用户。用PM2的话好像也可以定时启动
