### ISSUE TITLE
定时任务和脚本都被清空

### ISSUE THREAD

**Issue by xn408163898** [lan-tianxiang/JS_TOOL#57]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 使用什么平台？

- [x ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x ] Yes
- [ ] No

### (1) 具体问题
A：定时任务和脚本都被清空

### (2) 详细日志
A：定时任务和脚本都被突然清空，然后手动更新脚本，会提示拉取了很多脚本，实际并没有拉取到

**Comment by xxp2277** [comment]
我之前就是这个问题，不过感觉修复了的呀，难道又出现了？https://github.com/lan-tianxiang/JS_TOOL/issues/28

**Comment by xn408163898** [comment]
@xxp2277 应该没有修复  我出现过两次了，同事也出现过两次

**Comment by Soarfree** [comment]
我也遇到过 修复一下就好了

**Comment by xn408163898** [comment]
@anleihn 怎么修复？

**Comment by xxp2277** [comment]
重新拉取一下镜像吧，配置应该不会丢

**Comment by lan-tianxiang** [comment]
10号之后有空，到时候彻底审查一遍代码。到时候有消息在这边通知大家。暂时给大家带来的不便，先说声抱歉！

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xn408163898 ***@***.***&gt;;
发送时间：2021年6月7日(星期一) 下午2:17
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 定时任务和脚本都被清空 (#57)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
[x ] 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
[x ] 已仔细阅读教程 
  
2. 使用什么平台？
  
[x ] Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
[x ] Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
[x ] Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：定时任务和脚本都被清空
 
(2) 详细日志
 
A：定时任务和脚本都被突然清空，然后手动更新脚本，会提示拉取了很多脚本，实际并没有拉取到

**Comment by lan-tianxiang** [comment]
10号之后有空，会彻底审查一遍代码的。到时候有消息在这边通知大家。暂时给大家带来的不便，先说声抱歉！@xxp2277 @xn408163898   @anleihn

**Comment by allenforrest** [comment]
> 10号之后有空，会彻底审查一遍代码的。到时候有消息在这边通知大家。暂时给大家带来的不便，先说声抱歉！@xxp2277 @xn408163898 @anleihn

我感觉和 update 有关，暂时在 crontab 里把 update 任务停了，观察一下。

**Comment by llllllllu** [comment]
我也出现了两次了

**Comment by Tsukasa007** [comment]
经过测试，本地build 镜像会丢失crontab配置，还有冒昧的问问能不能并行账号运行...

**Comment by xn408163898** [comment]
今天晚上又出现了，基本上都是晚上出现清空crontab的问题，这很蛋疼啊@lan-tianxiang

**Comment by allenforrest** [comment]
就是 update 的问题，crontab -e，把 jd.sh update 那一行注释掉就行了，我猜测是 update 前先清空了 crontab，然后更新完任务后，重新添加时候报错了（手工执行 update 能看到最后有一些报错），所以导致没有把新的任务添加进去。我去掉 update 后，跑了一天多了没问题。

**Comment by xn408163898** [comment]
@lan-tianxiang 有人已经发现问题了，在自动更新脚本这个功能上。

**Comment by lan-tianxiang** [comment]
好，收到

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xn408163898 ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 上午8:48
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 定时任务和脚本都被清空 (#57)
-----------------------------------

 

 
***@***.***

**Comment by lan-tianxiang** [comment]
@xn408163898&nbsp; 好的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xn408163898 ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 上午9:09
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 定时任务和脚本都被清空 (#57)
-----------------------------------

 

 
@lan-tianxiang 有人已经发现问题了，在自动更新脚本这个功能上。

**Comment by xn408163898** [comment]
@lan-tianxiang 好像又不是这个问题   刚才我又被清空了   已经注释掉jd.sh update了

**Comment by mashiro-hjl** [comment]
我也出现三次了
