### ISSUE TITLE
这个新版没有git_pull.sh

### ISSUE THREAD

**Issue by fl754536** [lan-tianxiang/JS_TOOL#60]
怎么更新呢

**Comment by lan-tianxiang** [comment]
是的，使用命令  `jd update`

**Comment by lan-tianxiang** [comment]
输入 `jd` 有提示

**Comment by fl754536** [comment]
![image](https://user-images.githubusercontent.com/50579685/121112859-a4e88d00-c843-11eb-9cb6-f51ebe7e0968.png)
这个是什么原因呢

**Comment by lan-tianxiang** [comment]
貌似是没有安装iptables

**Comment by fl754536** [comment]
已经解决了，谢谢

**Comment by fl754536** [comment]
任务火爆是黑号了吗？

**Comment by lan-tianxiang** [comment]
任务火爆 这个分等级 ，一开始黑的叫黑号   。

先前能运行后面火爆了，应该是被系统检测了，推荐暂时先不运行，手动一天后试试

**Comment by fl754536** [comment]
好的，我这个是第二种情况，先手动一天试试
