### ISSUE TITLE
京东账号 用户名 是汉字，扫码登陆获取的cookies，pin项总是乱码，能不能解？

### ISSUE THREAD

**Issue by kbg1024** [lan-tianxiang/JS_TOOL#61]
### 想要增加什么样的功能或者哪里存在不足之处呢？

![261a9ff189c8325b88abcd4b2e65794](https://user-images.githubusercontent.com/63776904/121113814-4c19f400-c845-11eb-95e2-490977f3e333.png)

**Comment by Rosylusi** [comment]
确实，有些是正确的，有些却不正确。

**Comment by lan-tianxiang** [comment]
其实不是乱码，是中午转的url码

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："kbg1024 ***@***.***&gt;;
发送时间：2021年6月8日(星期二) 上午10:36
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 京东账号 用户名 是汉字，扫码登陆获取的cookies后面的pin总是乱码，能不能解？ (#61)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？

**Comment by lan-tianxiang** [comment]
中文转的urlcode，但是乱码不影响使用的！！🤣

**Comment by kbg1024** [comment]
> 中文转的urlcode，但是乱码不影响使用的！！

可能他这个用户名 中文北京特殊，那个 点 就不行，报错

**Comment by lan-tianxiang** [comment]
特殊字符可能不行，汉字是可以的。
为什么不改一下用户名呢🤗

**Comment by kbg1024** [comment]
> 特殊字符可能不行，汉字是可以的。
> 为什么不改一下用户名呢
京东不支持修改用户名啊，注册的时候是啥就是啥，昵称可以改
