### ISSUE TITLE
更新不到最新版本

### ISSUE THREAD

**Issue by xiaojia21190** [lan-tianxiang/JS_TOOL#63]
![image](https://user-images.githubusercontent.com/16084693/121130877-96a96980-c861-11eb-8bc1-a3b2eca0ec1c.png)

**Comment by lan-tianxiang** [comment]
这个有点意思，都更新到6-8号的了

**Comment by lan-tianxiang** [comment]
怎么会是呢

**Comment by lan-tianxiang** [comment]
你输入 `git pull`

**Comment by lan-tianxiang** [comment]
然后再输入更新命令试试

**Comment by xiaojia21190** [comment]
有些东西你没加载gitignore 然后生成的文件冲突了

**Comment by xiaojia21190** [comment]
惊喜牧场 要不要加 
[jd_mc.zip](https://github.com/lan-tianxiang/JS_TOOL/files/6614087/jd_mc.zip)

**Comment by lan-tianxiang** [comment]
jd jd_jxmc

**Comment by xiaojia21190** [comment]
没看到这个定时任务

**Comment by xiaojia21190** [comment]
京喜农场：jd_jxnc.js

**Comment by lan-tianxiang** [comment]
这个可不敢乱放定时，没完成新手教程运行一律黑号哈

**Comment by lan-tianxiang** [comment]
关键很多人暂时不知道

**Comment by lan-tianxiang** [comment]
你先看看能不能运行

**Comment by laoshuaibip** [comment]
> 这个有点意思，都更新到6-8号的了

其他库更新拉不到最新的，把整个文件夹删了重新拉又是最新的
