### ISSUE TITLE
API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by Deepturn** [lan-tianxiang/JS_TOOL#64]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
单独运运行农村，东东萌宠等，暂时知道这两个，会报出API请求失败

### (2) 详细日志
A：
![bug](https://user-images.githubusercontent.com/33342819/121162326-6a511580-c880-11eb-8869-63e18b9d76c6.png)

🔔东东萌宠, 开始!
开始获取东东萌宠配置文件

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/8 下午5:36:30=====================

共1个京东账号

您提供了1个账号的东东萌宠助力码

开始【京东账号1】

"getaddrinfo ENOTFOUND share.turinglabs.net share.turinglabs.net:80"
东东萌宠 API请求失败，请检查网路重试
第1个京东账号将要助力的好友["MTE1NDAxNzgwMDAwMDAwMzk3NDIzODc=","MTAxODEyMjkyMDAwMDAwMDQwMTEzNzA3","MTE1NDUyMjEwMDAwMDAwNDM3NDQzMzU=","MTEzMzI0OTE0NTAwMDAwMDA0Mzc0NjgzOQ=="]
开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTE1NDAxNzgwMDAwMDAwMzk3NDIzODc=
该好友Highdimen已满5人助力，无需您再次助力
开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTAxODEyMjkyMDAwMDAwMDQwMTEzNzA3
该好友Highdimen2已满5人助力，无需您再次助力
开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTE1NDUyMjEwMDAwMDAwNDM3NDQzMzU=
该好友jd_85661808已满5人助力，无需您再次助力
开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTEzMzI0OTE0NTAwMDAwMDA0Mzc0NjgzOQ==
该好友Highdimen5已满5人助力，无需您再次助力

==============📣系统通知📣==============
东东萌宠
【京东账号1】wdAfEwAUkKYWdf
【提醒⏰】3层抽纸巾30包已可领取
请去京东APP或微信小程序查看
点击弹窗即达

**Comment by Deepturn** [comment]
> ## 1.关于你要提交的问题
> Q：是否搜索了issue（包括已关闭的issue）
> 
> * [x]  没有类似的issue
> 
> Q：是否阅读了常见问题
> 
> * [x]  已阅读常见问题，未找到相关说明
> 
> Q：是否仔细阅读了教程
> 
> * [x]  已仔细阅读教程
> 
> ## 2. 使用什么平台？
> * [x]  Linux
> * [ ]  Docker
> 
> ## 3. 是否用一键脚本部署的？
> * [x]  Yes
> * [ ]  No
> 
> ## 4. 有没有试过用修复脚本来修复过？
> * [x]  Yes
> * [ ]  No
> 
> ## 5. 详细叙述
> ### (1) 具体问题
> A：
> 单独运运行农村，东东萌宠等，暂时知道这两个，会报出API请求失败
> 
> ### (2) 详细日志
> A：
> ![bug](https://user-images.githubusercontent.com/33342819/121162326-6a511580-c880-11eb-8869-63e18b9d76c6.png)
> 
> 🔔东东萌宠, 开始!
> 开始获取东东萌宠配置文件
> 
> ====================共1个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：2021/6/8 下午5:36:30=====================
> 
> 共1个京东账号
> 
> 您提供了1个账号的东东萌宠助力码
> 
> 开始【京东账号1】
> 
> "getaddrinfo ENOTFOUND share.turinglabs.net share.turinglabs.net:80"
> 东东萌宠 API请求失败，请检查网路重试
> 第1个京东账号将要助力的好友["MTE1NDAxNzgwMDAwMDAwMzk3NDIzODc=","MTAxODEyMjkyMDAwMDAwMDQwMTEzNzA3","MTE1NDUyMjEwMDAwMDAwNDM3NDQzMzU=","MTEzMzI0OTE0NTAwMDAwMDA0Mzc0NjgzOQ=="]
> 开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTE1NDAxNzgwMDAwMDAwMzk3NDIzODc=
> 该好友Highdimen已满5人助力，无需您再次助力
> 开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTAxODEyMjkyMDAwMDAwMDQwMTEzNzA3
> 该好友Highdimen2已满5人助力，无需您再次助力
> 开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTE1NDUyMjEwMDAwMDAwNDM3NDQzMzU=
> 该好友jd_85661808已满5人助力，无需您再次助力
> 开始助力京东账号1 - wdAfEwAUkKYWdf的好友: MTEzMzI0OTE0NTAwMDAwMDA0Mzc0NjgzOQ==
> 该好友Highdimen5已满5人助力，无需您再次助力
> 
> ==============📣系统通知📣==============
> 东东萌宠
> 【京东账号1】wdAfEwAUkKYWdf
> 【提醒⏰】3层抽纸巾30包已可领取
> 请去京东APP或微信小程序查看
> 点击弹窗即达

**Comment by lan-tianxiang** [comment]
"getaddrinfo ENOTFOUND share.turinglabs.net share.turinglabs.net:80"
东东萌宠 API请求失败，请检查网路重试

这个是脚本作者内置的助力库链接，现在可能失效了，还没修改，但是不影响使用的
