### ISSUE TITLE
关于tg bot配置问题

### ISSUE THREAD

**Issue by xiaorizi01** [lan-tianxiang/JS_TOOL#65]
大佬，我想问下这个配置bot的路径在哪里啊，按照说明 没找到相关的文件啊！

**Comment by allenforrest** [comment]
在 Tg 里做两件事：

- 找到 @BotFather 跟它聊天，创建 bot，获取 API Token
- 找到 @getuseridbot 跟它聊天，获取自己 Tg 账号的数字 ID

然后在 js_tools 的 config/config.sh 配置文件里，做三件事：

- ENABLE_TG_BOT="false" 改成 "true"
- export TG_BOT_TOKEN="" 填写 bot API Token
- export TG_USER_ID="" 填写自己 Tg 账号的数字 ID

完成后，执行 jd.sh jd_bean_change 测试一下，如果成功，会在你创建的 Bot 上给你推送京豆变更通知消息。

**Comment by xiaorizi01** [comment]
这个设置是通知吧。不是要通知，🤣
是想问下，如何配置tg机器人！就是像v4的那种机器人



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allen Xu ***@***.***&gt;
发送时间: 2021年6月9日 09:09
收件人: lan-tianxiang/JS_TOOL ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lan-tianxiang/JS_TOOL] 关于tg bot配置问题 (#65)





 
在 Tg 里做两件事：
  
找到 @Botfather 跟它聊天，创建 bot，获取 API Token 

找到 @getuseridbot 跟它聊天，获取自己 Tg 账号的数字 ID 
 
然后在 js_tools 的 config/config.sh 配置文件里，做三件事：
  
ENABLE_TG_BOT="false" 改成 "true" 

export TG_BOT_TOKEN="" 填写 bot API Token 

export TG_USER_ID="" 填写自己 Tg 账号的数字 ID 
 
完成后，执行 jd.sh jd_bean_change 测试一下，如果成功，会在你创建的 Bot 上给你推送京豆变更通知消息。

**Comment by qq7984225** [comment]
还没支持 等待更新

**Comment by hubing0917** [comment]
> 在 Tg 里做两件事：
> 
> 
> 
> - 找到 @BotFather 跟它聊天，创建 bot，获取 API Token
> 
> - 找到 @getuseridbot 跟它聊天，获取自己 Tg 账号的数字 ID
> 
> 
> 
> 然后在 js_tools 的 config/config.sh 配置文件里，做三件事：
> 
> 
> 
> - ENABLE_TG_BOT="false" 改成 "true"
> 
> - export TG_BOT_TOKEN="" 填写 bot API Token
> 
> - export TG_USER_ID="" 填写自己 Tg 账号的数字 ID
> 
> 
> 
> 完成后，执行 jd.sh jd_bean_change 测试一下，如果成功，会在你创建的 Bot 上给你推送京豆变更通知消息。

我这三步都做了，但还是没成功。
