### ISSUE TITLE
在面板里手动执行脚本，脚本没有执行完毕，自动又重新执行

### ISSUE THREAD

**Issue by xn408163898** [lan-tianxiang/JS_TOOL#66]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
在面板里手动执行脚本，脚本没有执行完毕，自动又重新执行

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
更新完后，重启docket

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xn408163898 ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 上午9:04
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 在面板里手动执行脚本，脚本没有执行完毕，自动又重新执行 (#66)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 在面板里手动执行脚本，脚本没有执行完毕，自动又重新执行
 
(2) 详细日志
 
A：

**Comment by xn408163898** [comment]
@lan-tianxiang 我没用docker啊
