### ISSUE TITLE
update后crontab.list丢失

### ISSUE THREAD

**Issue by 442774765** [lan-tianxiang/JS_TOOL#67]

**Comment by CaelDeng** [comment]
我的也是

**Comment by SKzxsk** [comment]
诶，我今天更新完废了也是这样，其中有这个症状

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/124344700-6c4f8f80-dc06-11eb-826e-b5d57477d9de.png)
好像是这个导致的吧，手动去除这些 "cron"，然后把 crontab 任务复制下粘贴进 crontab 吧
