### ISSUE TITLE
京喜牧场能安排一下么

### ISSUE THREAD

**Issue by zdmisif** [lan-tianxiang/JS_TOOL#68]

**Comment by Rosylusi** [comment]
不是有吗

**Comment by lan-tianxiang** [comment]
有的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 上午10:10
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 京喜牧场能安排一下么 (#68)
-----------------------------------

 

 
不是有吗

**Comment by Rosylusi** [comment]
所以大佬，有没有兴趣再写一点淘宝、拼多多用的脚本，就很棒~~

**Comment by qq7984225** [comment]
宠物狗赛跑助力又凉了

**Comment by zdmisif** [comment]
> 有的
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："easonren ***@***.***&gt;; 发送时间：2021年6月9日(星期三) 上午10:10 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 京喜牧场能安排一下么 (#68) ----------------------------------- 不是有吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

貌似没有牧场的喔，牧场是哪个文件？

**Comment by zdmisif** [comment]
找到了

**Comment by daxinnan** [comment]
请问是要自己添加京喜农场的定时任务吗，我没在清单里看到，还有动物联盟也没在定时任务清单里看到
