### ISSUE TITLE
DIY脚本

### ISSUE THREAD

**Issue by ghost** [lan-tianxiang/JS_TOOL#69]
我想问一下DIY脚本区，已经设置为true，把我想用的脚本放到scripts文件夹内，我想用定时任务，自定义脚本内容写上定时任务会自动执行么？

**Comment by lan-tianxiang** [comment]
写上定时任务不会执行。DIY是指系统每次运行完更新命令后会自动执行DIY里面的内容

**Comment by zp121** [comment]
谢谢回答。

**Comment by lan-tianxiang** [comment]
@zp121  没事的

**Comment by ghost** [comment]
> @zp121 没事的
谢谢回答。
还有一个问题。如果我用单文件下载添加了thirdpard下定时任务。那么我还需要在任务区里添加一次么？应该不需要了吧。那些只是scripts下面定时任务吧？即使不添加应该也可以执行吧？
