### ISSUE TITLE
老哥求教，在安装部署时遇到了问题

### ISSUE THREAD

**Issue by tesengiii** [lan-tianxiang/JS_TOOL#7]
![image](https://user-images.githubusercontent.com/58262656/115201403-e1431b00-a127-11eb-8213-5ca4bd92dd6f.png)
提示这个 有什么解决办法吗 在网上找的办法都试过了

**Comment by ryan016** [comment]
终究还是网络不稳定问题导致的，还是找个好点的代理吧

**Comment by tesengiii** [comment]
一定要翻墙对吧

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/115366772-2b93cd00-a1f8-11eb-84f8-f03619385c02.png)
按照网络上的方法都找不到 会不会是源文件的问题

**Comment by cxaa21** [comment]
解决办法
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/116202272-f7c32500-a76c-11eb-939f-dcb133cd018f.png)
![image](https://user-images.githubusercontent.com/58262656/116202400-1aedd480-a76d-11eb-9f51-aa26a8d6a624.png)

老哥之前那个解决了 现在卡在这里

**Comment by tesengiii** [comment]
要我自己创建？ 我之前有一次突然弄好了 不用我操作的   我也不知道什么原因 现在重新弄又会这样

**Comment by tesengiii** [comment]
![image](https://user-images.githubusercontent.com/58262656/116202633-64d6ba80-a76d-11eb-92d8-aa5cae396929.png)
jing'ru进入root后操作也不行

**Comment by kbg1024** [comment]
apt install -y git curl wget nodejs npm perl moreutils

**Comment by kbg1024** [comment]
先装这个，然后再用那个一件脚本就行了

**Comment by tesengiii** [comment]
> 先装这个，然后再用那个一件脚本就行了

谢老哥 已经解决了
