### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by essential-1** [lan-tianxiang/JS_TOOL#70]
根据步骤配置好了系统，但是不知道在哪里填写cookie及通知推送key，有大神指导下吗，万分感谢

**Comment by zp121** [comment]
登陆到后台第一个用户设定里面。你可以直接点扫码，然后把Cookie复制出来，放在Cookie1=""引号里面，不要去掉引号即可。推送去配置里面看。

**Comment by ghost** [comment]
> 根据步骤配置好了系统，但是不知道在哪里填写cookie及通知推送key，有大神指导下吗，万分感谢

登陆到后台第一个用户设定里面。你可以直接点扫码，然后把Cookie复制出来，放在Cookie1=""引号里面，不要去掉引号即可。推送去“配置设定”里面看。

**Comment by essential-1** [comment]
> > 已知已完成配置的系统，但不知道是否有更新cookie及通知密钥，有大神指导下吗，万分感谢
> 
> 登陆到后台第一个用户设置里面。你可以直接点扫码，然后把Cookie复制出来，把Cookie1=""书签里面，不要去掉书签。去“配置设置”

**Comment by essential-1** [comment]
> > 已知已完成配置的系统，但不知道是否有更新cookie及通知密钥，有大神指导下吗，万分感谢
> 
> 登陆到后台第一个用户设置里面。你可以直接点扫码，然后把Cookie复制出来，把Cookie1=""书签里面，不要去掉书签。去“配置设置”里面看。

谢谢，我去试试

**Comment by essential-1** [comment]
> > 根据步骤配置好了系统，但是不知道在哪里填写cookie及通知推送key，有大神指导下吗，万分感谢
> 
> 登陆到后台第一个用户设定里面。你可以直接点扫码，然后把Cookie复制出来，放在Cookie1=""引号里面，不要去掉引号即可。推送去“配置设定”里面看。

还有一个疑问，我需要一直开着Ubuntu这个软件吗

**Comment by ghost** [comment]
> > > 根据步骤配置好了系统，但是不知道在哪里填写cookie及通知推送key，有大神指导下吗，万分感谢
> > 
> > 
> > 登陆到后台第一个用户设定里面。你可以直接点扫码，然后把Cookie复制出来，放在Cookie1=""引号里面，不要去掉引号即可。推送去“配置设定”里面看。
> 
> 还有一个疑问，我需要一直开着Ubuntu这个软件吗

没明白你想问的。运行起来机器肯定是要一直开着，后台需要设置的时候进去就可以了。

**Comment by essential-1** [comment]
> > > > 根据步骤配置好了系统，但是不知道在哪里填写cookie及通知推送key，有大神指导下吗，万分感谢
> > > 
> > > 
> > > 登陆到后台第一个用户设定里面。你可以直接点扫码，然后把Cookie复制出来，放在Cookie1=""引号里面，不要去掉引号即可。推送去“配置设定”里面看。
> > 
> > 
> > 还有一个疑问，我需要一直开着Ubuntu这个软件吗
> 
> 没明白你想问的。运行起来机器肯定是要一直开着，后台需要设置的时候进去就可以了。

懂了，谢谢大佬解惑
