### ISSUE TITLE
手机上如何一下子全部运行起来，面板上只有一个个的

### ISSUE THREAD

**Issue by ghost** [lan-tianxiang/JS_TOOL#71]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [ ] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
手机输入crond -ipP之后，到点就会自动运行。不用手动点击

**Comment by Curry-wei98** [comment]
电脑如何手动运行所有脚本呢？runall2好像不行，还是我代码错了...

**Comment by 13223486896** [comment]
> 手机输入crond -ipP之后，到点就会自动运行。不用手动点击

电脑版怎么并发运行所有脚本，runall2是顺序运行的呀

**Comment by lan-tianxiang** [comment]
@13223486896  runall2,已经修复，现在是全部并发

**Comment by lan-tianxiang** [comment]
@Curry-wei98  更新试试

**Comment by Curry-wei98** [comment]
我不知道代码是什么，之前用过一次忘记了~能告诉一下吗？如何运行runall2
