### ISSUE TITLE
使用环境建议

### ISSUE THREAD

**Issue by zhangleqin** [lan-tianxiang/JS_TOOL#72]
### 想要增加什么样的功能或者哪里存在不足之处呢？
现有的安装环境都比较难搞
linux系要搞个VPS，或者自备树莓派，价格划不来
安卓系，手机会休眠，常年占内存也不是个事
自己电脑上虚拟机运行，也做不到24小时开机
是否能支持在电视盒子 或者 路由器中运行
轻量化一下 那些东西本来24小时联网开着
为了这个开一个阿里云不值得

**Comment by lan-tianxiang** [comment]
电视盒子 或者 路由器的话
其实很多用户通过路由器都可以安装docker，然后部署这个工具的

**Comment by lan-tianxiang** [comment]
安卓系其实有一个旧手机，常年亮屏就不会休眠的。我用手机测试了很长时间。

**Comment by wjj982** [comment]
我安卓utermux，黑屏也一样后台，打开自动运行，以及utermux的wakelock锁

**Comment by zhangleqin** [comment]
> 安卓系其实有一个旧手机，常年亮屏就不会休眠的。我用手机测试了很长时间。

你这个一说我就明白了 强制不休眠 灭屏 然后电源也就10W可以，旧手机谁都有 感谢

**Comment by zhangleqin** [comment]
废旧安卓手机 最优解
