### ISSUE TITLE
添加第三方仓库提示克隆成功，但是没有文件。

### ISSUE THREAD

**Issue by 442774765** [lan-tianxiang/JS_TOOL#73]

**Comment by lan-tianxiang** [comment]
在thirdpart文件夹里面，不过可能暂时不支持，等我11号修复

**Comment by lan-tianxiang** [comment]
已修复，请打开
![image](https://user-images.githubusercontent.com/42911023/121654207-0f156200-cad0-11eb-8cbc-ec6ecdb7d276.png)
