### ISSUE TITLE
openwrt不能自动更新，手动运行更新时定时任务删除失败，手动删除日志时运行出错无法删除

### ISSUE THREAD

**Issue by happy-peter** [lan-tianxiang/JS_TOOL#75]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

手动运行的话虽然能更新，但是日志结尾会显示
![image](https://user-images.githubusercontent.com/68748434/121347451-cb005100-c959-11eb-8b67-c6659916fa47.png)

手动删除日志会提示
![image](https://user-images.githubusercontent.com/68748434/121347950-5843a580-c95a-11eb-8f42-bc92c3c72ee7.png)

更新完后显示已删除定时任务，但是实际上删除失败，进去看定时任务还在
![image](https://user-images.githubusercontent.com/68748434/121347625-fc791c80-c959-11eb-971a-3f4a824c39ce.png)

麻烦大佬看一下，优化一下，谢谢。

**Comment by lan-tianxiang** [comment]
好的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："happy-peter ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 晚上7:39
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] openwrt不能自动更新，手动运行更新是定时任务删除失败，手动删除日志时运行出错无法删除 (#75)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 
(2) 详细日志
 
A：
 
手动运行的话虽然能更新，但是日志结尾会显示
 
 
手动删除日志会提示
 
 
更新完后显示已删除定时任务，但是实际上删除失败，进去看定时任务还在
 
 
麻烦大佬看一下，优化一下，谢谢。
