### ISSUE TITLE
如何让程序每日定时运行

### ISSUE THREAD

**Issue by ZhengRong-T** [lan-tianxiang/JS_TOOL#76]
### 想要增加什么样的功能或者哪里存在不足之处呢？
现有腾讯云服务器，今天试了下用nohup bash jd.sh runall2 & 放后台运行，速度有点慢，感觉直接运行还快些。然后想问下大佬怎么实现每天自动运行，谢谢大佬

**Comment by lan-tianxiang** [comment]
部署完就能自动运行，你填写一下推送通知就知道了了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："ZhengRong-T ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 晚上8:34
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 如何让程序每日定时运行 (#76)
-----------------------------------

 

 
想要增加什么样的功能或者哪里存在不足之处呢？
 
现有腾讯云服务器，今天试了下用nohup bash jd.sh runall2 &amp; 放后台运行，速度有点慢，感觉直接运行还快些。然后想问下大佬怎么实现每天自动运行，谢谢大佬

**Comment by ZhengRong-T** [comment]
谢谢大佬，感谢
