### ISSUE TITLE
更新后脚本都没了

### ISSUE THREAD

**Issue by shanhai2333** [lan-tianxiang/JS_TOOL#79]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [ ] Yes
- [x] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
更新后脚本都没有了

### (2) 详细日志
A：

**Comment by Soarfree** [comment]
脚本库里脚本清空了 刚去打包了上一个版本的上传上去就好了
https://gitee.com/highdimen/clone_scripts 这是拉取的库 一个小时前更新 里面脚本空了
https://gitee.com/highdimen/clone_scripts/tree/a38137a7defd1a41a5f5438ef8fe0d5becff1982 这是上一个版本的没被清空前 自己去下载吧 覆盖/jd/scripts

**Comment by leeailee77** [comment]
同上，执行bash git_pull.git后，什么都没了。重新拉取安装后也一样，脚本都是空的
![Screenshot_2021-06-10-02-07-47-050_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/80807232/121406550-e2244c00-c923-11eb-90a2-800561b17f2c.jpg)

**Comment by shanhai2333** [comment]
> 脚本库里脚本清空了刚去打包了上一个版本的上传就好了
> https://gitee.com/highdimen/clone_scripts拉取的库一个小时前更新里面脚本空了
> [https://gitee. com/highdimen/clone_scripts/tree/a38137a7defd1a41a5f5438ef8fe0d5becff1982](https://gitee.com/highdimen/clone_scripts/tree/a38137a7defd1a41a5f5438ef8fe0d5becff1982)这是上一个版本的没被清空前自己去下载吧覆盖/jd/scripts

**Comment by lan-tianxiang** [comment]
是的，已经修复了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："shanhai ***@***.***&gt;;
发送时间：2021年6月10日(星期四) 凌晨2:15
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 更新后脚本都没了 (#79)
-----------------------------------

 

  
脚本库里脚本清空了刚去打包了上一个版本的上传就好了
 https://gitee.com/highdimen/clone_scripts拉取的库一个小时前更新里面脚本空了
 https://gitee. com/highdimen/clone_scripts/tree/a38137a7defd1a41a5f5438ef8fe0d5becff1982这是上一个版本的没被清空前自己去下载吧覆盖/jd/scripts
