### ISSUE TITLE
注释掉定时任务自动更新 没用

### ISSUE THREAD

**Issue by Soarfree** [lan-tianxiang/JS_TOOL#81]
脚本库挂了 注释掉定时任务自动更新 每小时的22分钟照旧自动更新了脚本 老得手动覆盖 希望修复一下

**Comment by lan-tianxiang** [comment]
已修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："anleihn ***@***.***&gt;;
发送时间：2021年6月10日(星期四) 凌晨5:37
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 注释掉定时任务自动更新 没用 (#81)
-----------------------------------

 

 
脚本库挂了 注释掉定时任务自动更新 每小时的22分钟照旧自动更新了脚本 老得手动覆盖 希望修复一下
