### ISSUE TITLE
宠汪汪偷好友积分与狗粮

### ISSUE THREAD

**Issue by aburdchen415** [lan-tianxiang/JS_TOOL#82]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [ ] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：

### (2) 详细日志
A：

宠汪汪偷好友积分与狗粮这几天一直失败，无法读取好友列表。。。

**Comment by lan-tianxiang** [comment]
脚本暂时失效了，我试一下能不能修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："aburdchen415 ***@***.***&gt;;
发送时间：2021年6月10日(星期四) 上午8:27
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lan-tianxiang/JS_TOOL] 宠汪汪偷好友积分与狗粮 (#82)
-----------------------------------

 

 
1.关于你要提交的问题
 
Q：是否搜索了issue（包括已关闭的issue）
  
 没有类似的issue 
  
Q：是否阅读了常见问题
  
 已阅读常见问题，未找到相关说明 
  
Q：是否仔细阅读了教程
  
 已仔细阅读教程 
  
2. 使用什么平台？
  
 Linux
 
 Docker
  
3. 是否用一键脚本部署的？
  
 Yes
 
 No
  
4. 有没有试过用修复脚本来修复过？
  
 Yes
 
 No
  
5. 详细叙述
 
(1) 具体问题
 
A：
 
(2) 详细日志
 
A：
 
宠汪汪偷好友积分与狗粮这几天一直失败，无法读取好友列表。。。

**Comment by Rosylusi** [comment]
> 
> 脚本暂时失效了，我试一下能不能修复
> [… ](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："aburdchen415 ***@***.***>; 发送时间：2021年6月10日(星期四) 上午8:27 收件人："lan-tianxiang/JS_TOOL" ***@***.***>; 抄送："Subscribed ***@***.***>; 主题：[lan-tianxiang/JS_TOOL] 宠汪汪偷好友积分与狗粮 ( [#82 ](https://github.com/lan-tianxiang/JS_TOOL/issues/82)) ----------------------------------- 1.关于你要提交的问题 Q：是否搜索了issue（包括已关闭的issue） 没有类似的issue Q：是否阅读了常见问题 已阅读常见问题，未找到相关说明 Q：是否仔细阅读了教程 已仔细阅读教程 2. 使用什么平台？ Linux Docker 3. 是否用一键脚本部署的？ Yes No 4. 有没有试过用修复脚本来修复过？ Yes No 5. 详细叙述 (1) 具体问题 A： (2) 详细日志 A： 宠汪汪偷好友积分与狗粮这几天一直失败，无法读取好友列表。。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，听TG群里说要散了，对咱们的脚本是否有影响？
