### ISSUE TITLE
怎么设置手动执行里运行挂机活动要运行的脚本

### ISSUE THREAD

**Issue by Deepturn** [lan-tianxiang/JS_TOOL#84]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [x] Linux
- [ ] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
每次点击手动执行里的运行挂机活动，都会执行疯狂joy，怎么能设置运行自己指定的

### (2) 详细日志
A：

![demo](https://user-images.githubusercontent.com/33342819/121452752-8d8bda00-c9d2-11eb-9af0-80e6b9aa997f.png)

**Comment by lan-tianxiang** [comment]
不用手动设置的，输入脚本名，点一下执行就可以了

**Comment by Deepturn** [comment]
> 不用手动设置的，输入脚本名，点一下执行就可以了
我知道那个功能，那是只能一次运行一个脚本，运行挂机活动 的主要功能是啥，不太懂
