### ISSUE TITLE
账号被封了 一注册就被标记了  

### ISSUE THREAD

**Issue by QQ1142057049** [lan-tianxiang/JS_TOOL#90]
一直用的是 GitHub Actions  可是现在 要么账号被封 要么就是标记了，
然后就想去安装 WSL Ubuntu   可是应用商店一直 下载不了 错误代码: 0x80070005
都不知道该怎么弄了  windows
docker 也搞不明白 ┭┮﹏┭┮

**Comment by QQ1142057049** [comment]
补充 如果GitHub Actions被禁用了 还能用这个 JS_TOOL 脚本吗

**Comment by QQ1142057049** [comment]
补充 安装好了
![image](https://user-images.githubusercontent.com/67356618/121498118-b336d480-ca0e-11eb-9745-d75039c59639.png)
之后后怎么使用

**Comment by QQ1142057049** [comment]
用了 docker 后只能在本地运行吗  能不能像GitHub Actions 一样 就算人不在 没开电脑都能自动运行

**Comment by shanhai2333** [comment]
你装服务器上或者软路由就不管他

**Comment by QQ1142057049** [comment]
怎么弄到服务器上？

**Comment by Tsukasa007** [comment]
首先你先要有台服务器

**Comment by 13223486896** [comment]
注册阿里云服务器，免费飘一个月

**Comment by Tsukasa007** [comment]
> 注册阿里云服务器，免费飘一个月

学生1年

**Comment by QQ1142057049** [comment]
> > 注册阿里云服务器，免费飘一个月
> 
> 学生1年

怎么领一年的？
