### ISSUE TITLE
依赖未安装完整,请重新运行该脚本且切换良好的网络环境 怎么解决

### ISSUE THREAD

**Issue by lichen780** [lan-tianxiang/JS_TOOL#91]
依赖未安装完整,请重新运行该脚本且切换良好的网络环境！
换成国内源的 也还是这样

**Comment by LvDeShei** [comment]
腾讯云，必须用Ubuntu 20* LTSC的哪个版本，才能安装顺利，如果用Deban的就出现这个问题!
