### ISSUE TITLE
增加功能

### ISSUE THREAD

**Issue by wzal2008** [lan-tianxiang/JS_TOOL#94]
定时任务不会自动运行，任务并发执行jd runall3/runall2也是依次运行，希望加入并发执行和自定义任务的并发执行，最好把自定义任务也加入互助码自动添加功能，如京东到家任务，柠檬等

**Comment by lan-tianxiang** [comment]
并发执行刚刚解决了。
自定义任务也加入互助码自动添加功能，稍等就加

**Comment by Tsukasa007** [comment]
膜拜大佬，等待更新

**Comment by wzal2008** [comment]
厉害！！！！！！！！！！！
