### ISSUE TITLE
想问一下大家，你们一般一天能有多少京豆呀，正常水平应该得多少

### ISSUE THREAD

**Issue by QQ1142057049** [lan-tianxiang/JS_TOOL#95]

**Comment by Curry-wei98** [comment]
我一天才300和一块钱

**Comment by QQ1142057049** [comment]
> 我一天才300和一块钱

6.8第一天有700+   现在我每天才两百多 有时候少的 一百多。。

**Comment by Curry-wei98** [comment]
正常…我现在一天稳定在300，现金很少

QQ1142057049 ***@***.***>于2021年6月10日 周四18:51写道：

**Comment by 13223486896** [comment]
之前用的别的仓库的action，一天有五百度，现在好像一百多
