### ISSUE TITLE
京喜财富岛提现

### ISSUE THREAD

**Issue by daxinnan** [lan-tianxiang/JS_TOOL#96]
### 想要增加什么样的功能或者哪里存在不足之处呢？

貌似得先手动提现成功一次然后才能做？
[https://github.com/zero205/JD_tencent_scf/blob/main/jd_cfdtx.js](url)

**Comment by Curry-wei98** [comment]
怎么体现？活动入口在哪？

**Comment by daxinnan** [comment]
> 怎么体现？活动入口在哪？


你打开京喜财富岛的页面就能看到提现入口
