### ISSUE TITLE
docker版重新安装后互助码不生效呢

### ISSUE THREAD

**Issue by shanhai2333** [lan-tianxiang/JS_TOOL#97]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：
重新安装后，自动生成了互助码，但是不起作用

### (2) 详细日志
A：

**Comment by shanhai2333** [comment]
![QQ截图20210611020530](https://user-images.githubusercontent.com/24859518/121575180-a4294400-ca59-11eb-9866-c091e99e0d3d.png)
都是助力的这几个人

**Comment by lan-tianxiang** [comment]
设置里面的自动助力开了吗？

**Comment by lan-tianxiang** [comment]
开了之后看看日记里面有没有helpcode

**Comment by shanhai2333** [comment]
@lan-tianxiang 我把助力码填配置文件里就可以用了
