### ISSUE TITLE
使用 Docker For 通用1 安装完成后 网络会自动选host

### ISSUE THREAD

**Issue by sdyby2006** [lan-tianxiang/JS_TOOL#99]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否阅读了常见问题
- [x] 已阅读常见问题，未找到相关说明 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 使用什么平台？

- [ ] Linux
- [x] Docker

## 3. 是否用一键脚本部署的？

- [x] Yes
- [ ] No

## 4. 有没有试过用修复脚本来修复过？

- [x] Yes
- [ ] No

### (1) 具体问题
A：使用 Docker For 通用1 安装完成后 网络会自动选host，这是用ip:5678无法进入网页，需要把网络重新改为bridge以后才可以进入网页，不知道是否个人情况。

### (2) 详细日志
A：

**Comment by lan-tianxiang** [comment]
是我写错了，已经修复！
